### ISSUE TITLE
Only approachable via Spotify on computer not via phone

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#100]
<a href="https://github.com/JHoogink"><img src="https://avatars2.githubusercontent.com/u/11311503?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [JHoogink](https://github.com/JHoogink)**
_Saturday Dec 23, 2017 at 08:15 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/269_

----

Since updating both my raspberry and I think the spotify app on my phone (Android), I can no longer approach Librespot directly from my phone. When I setup a connect session via the computer I am able to use my phone as a remote. 

Any ideas? I found out that the Spotify app does the same with Sonos lately

**Comment by sashahilton00** [comment]
<a href="https://github.com/maxx"><img src="https://avatars3.githubusercontent.com/u/2896?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maxx](https://github.com/maxx)**
_Thursday Dec 28, 2017 at 18:44 GMT_

----

If this is occurring with Sonos as well, wouldn't that indicate it's a Spotify issue? It sounds like they've broken casting  on android completely. Did you end up with any solution to this?  I was considering switching back to Android again and this would be sad if this is the case.

**Comment by sashahilton00** [comment]
<a href="https://github.com/maxx"><img src="https://avatars3.githubusercontent.com/u/2896?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maxx](https://github.com/maxx)**
_Thursday Dec 28, 2017 at 19:18 GMT_

----

I suspect this is your issue:

https://community.spotify.com/t5/Other-Partners-Web-Player-etc/Sonos-Bug-Spotify-Connect-is-broken/td-p/3608434
https://community.spotify.com/t5/Android/Spotify-app-won-t-connect-to-Sonos/td-p/3564456

Downgrading the android app should solve your problem. That's a pretty bad bug!

**Comment by ComlOnline** [comment]
As this appears to be a Spotify bug that has since been fixed I'm going to close this issue.

**Comment by Jergol** [comment]
Apparently i have this issue as well. i got librespot running on a pi3 and can not find the device via Android. So this Android-Issue is still a problem. I don't know about the Sonos.

**Comment by sashahilton00** [comment]
Please test with a Sonos and librespot under the same network conditions. There has been another report of trouble connecting, but at this point it's difficult to say whether this is a librespot/Spotify bug, or down to network configuration.

**Comment by Jergol** [comment]
I do not own a Sonos. But i would like to get the pi3/librespot working again for my android. For the PC in the same network it's not a problem to connect at all, and i can start the playback @ librespot via PC and even see and controll forward n stuff via android afterwards. But when it comes to find the device and initiate it from android it's not even possible to find the librespot. 

If there are any infos you need or settings i should try, just give me a hint and i give it a try.

Ty in advance.

**Comment by sashahilton00** [comment]
@Jergol can you confirm whether you see the error message(s) in this issue at all in the console of your librespot device? https://github.com/librespot-org/librespot/issues/67

**Comment by Jergol** [comment]
Hello! I'd like to help but i am a very basic/rookie user and i actually do
not know how to view error-msgs. If you can tell me how i will take a look
at it.

2018-02-12 1:30 GMT+01:00 Sasha Hilton <notifications@github.com>:

**Comment by sashahilton00** [comment]
When you start librespot, there's a bunch of text in the console, the error which you're looking for looks something like this:
```
WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }
```
It will appear within the first 10 lines if it appears at all.

**Comment by Jergol** [comment]
i will check it in a minute, i am running a Raspberry Pi 3 with Libreelec
on it, if that matters. Checking now,

2018-02-12 1:42 GMT+01:00 Sasha Hilton <notifications@github.com>:

**Comment by Jergol** [comment]
Since i do not directly start Librespot via app/addon on Libreelec
(running, managing in background) i can not rly see the msg. I did check
for updates, did deactivate and reactivate, even restartet the whole system
but i can not see any msgs, i also tried to see stuff in debugmode but i
can not find anything fitting to you description. Then again, i am not
experienced in this kinda stuff. Sry that i can not help you there atm.

2018-02-12 1:46 GMT+01:00 Matthias Tatura <faustivus@gmail.com>:

**Comment by sashahilton00** [comment]
No problem. I'm going to close this for now, as I think it is probably issue #67 you're experiencing, indirectly.

**Comment by markubiak** [comment]
I had this issue, and the solution in my case was unrelated to librespot. It turns out that Spotify has a bug in their Android app that unintentionally interferes with ad blockers, as discussed in [this AdAway issue](https://github.com/AdAway/AdAway/issues/1009).

The solution is a fork of AdAway that works around the issue, found [here](https://github.com/c64bob/AdAway/releases/tag/v4.1.0)
