### ISSUE TITLE
cargo error: failed to download `alsa v0.6.0`

### ISSUE THREAD

**Issue by rohoog** [librespot-org/librespot#1016]
I am a total newbie on cargo/rust, so I have no clue to resolve this.

**Comment by rohoog** [comment]
It seems it is downloaded, but the 'edition = "2021"' (whatever that is) in Cargo.toml isn't liked by the librespot build system.

**Comment by rohoog** [comment]
OK it seems the culprit is the version of cargo/rustc that is installed on my system. It is resolved by uninstalling the distro-provided packages and following the install procedure on [rust-lang.org](https://www.rust-lang.org/tools/install). Debian-buster and bullseye are not new enough for alsa v0.6.0.

**Comment by JasonLG1979** [comment]
Generally speaking you should NOT use your distro packaged version Rust to build external projects especially not on Debian where things tend to be pretty far behind upstream.

**Comment by rohoog** [comment]
Right. So much for my first encounter with rust.

**Comment by JasonLG1979** [comment]
It not a Rust failing. That's generally the case with any compiled language. The distro tools are designed to build the packages in the repo.

**Comment by kingosticks** [comment]
Boo for them for not supporting any platform!
