### ISSUE TITLE
Error ENOSPC with S24_3 sample format and alsa backend

### ISSUE THREAD

**Issue by rohoog** [librespot-org/librespot#1017]
I'm not sure it is a librespot or alsa v0.6.0 crate problem.
I use the SA9023 usb audio chip, which should support the S24_3 sample format. If I use a really not supported sample format like S32, I get a different error EINVAL as expected. With S24_3, I get ENOSPC. S16 works fine.

I guess that the sample buffer size used in librespot is not a multiple of the S24_3 frame size (6 bytes), hence the ENOSPC response from the alsa driver.

**Comment by roderickvd** [comment]
Phew it’s a long time ago that I tested `S24_3`. I have never had a hardware device that supported that, so I tested it with `plughw` in the assumption that what works there, would work for hardware devices too. 

The `S24_3` samples are packed as a `[u8; 3]` so that’s six bytes.

Could you investigate with `plughw` and maybe drill down on this thing some more?

**Comment by r-hoogenboom** [comment]
What do you suggest I should try with `plughw`?
My understanding is that plughw 'magically' converts sample formats, sample rates (channels?) the chip doesn't support into what the chip does support in software.
Do you want me to use S32 with plughw, which should likely be converted to S24_3 internally by alsa?
Do you want me to use S24_3 with plughw? Then the plughw doesn't need to do any converting and likely the same error will happen.
I can try something this evening (CET).

**Comment by roderickvd** [comment]
Would be great if you could try outputting `S24_3` to `plughw` and perhaps not only this sound card, but another one as well (if only a speaker or even a dummy). If that works then we know `librespot` puts out 6-byte packets fine.

**Comment by roderickvd** [comment]
Yes, that could be. At least we will have elimated the question of the byte packing. 

@JasonLG1979 did the latest work on the buffer size, he may know more.

**Comment by JasonLG1979** [comment]
As far as size goes the buffer is calculated and set by frame and then we ask alsa how many bytes a period is. Our buffer is 1 period worth of bytes as per alsa.

**Comment by rohoog** [comment]
The exact error message is "ALSA function 'snd_pcm_hw_params' failed with error 'ENOSPC: No space left on device'" (device . hw:CARD=Audio,DEV=0). with plughw:CARD=Audio,DEV=0, the result is exactly the same. With plughw and S32, also the same.

Using the default:CARD=Audio and S24_3 works. I'm not sure if alsa will actually use the 24bit mode of the audio chip then.

**Comment by JasonLG1979** [comment]
That makes me believe that it's not a librespot specific issue. Have you tried aplay?

**Comment by rohoog** [comment]
Correction: the default:CARD=Audio with S24_3 completely freezes the system without any error message.
Indeed this seems more and more a kernel driver issue.
Let me try aplay, but first I need to find something that generates a S24_3 raw stream.

**Comment by JasonLG1979** [comment]
I can't remember off the top of my head if will do 24_3?

**Comment by rohoog** [comment]
speaker-test is great! I didn't know that one, thanks.
There is S24_3LE and S24_3BE. I guess librespot will do ..LE on LE machine, right? -- it has to, because the ..BE is not supported.
And indeed also ENOSPC with hw and plughw, the reported buffer size of 174760 is not divisible by 6.
The default:CARD=Audio does not freeze the system with speaker-test.

**Comment by JasonLG1979** [comment]
Yes LE on LE and BE on BE automatically.

**Comment by rohoog** [comment]
speaker-test 1.1.8

Playback device is hw:CARD=Audio,DEV=0
Stream parameters are 48000Hz, S24_3LE, 2 channels
Using 16 octaves of pink noise
Rate set to 48000Hz (requested 48000Hz)
Buffer size range from 96 to 174762   ----> divisible by 6
Period size range from 48 to 87381
Using max buffer size 174760   ----> not divisible -- why it uses this instead of the advertized?
Periods = 4
Unable to set hw params for playback: No space left on device
Setting of hwparams failed: No space left on device

**Comment by JasonLG1979** [comment]
Sounds like a driver/hardware issue to me.

**Comment by JasonLG1979** [comment]
No idea why it's using the buffer size it is? You'd have to look at the speaker-test source?

**Comment by JasonLG1979** [comment]
Like I said this does not look like a librespot issue

**Comment by JasonLG1979** [comment]
Ok silly question. I googled the chip you mentioned and it's not a standalone DAC it's just a USB input controller. Is your device a commercial product or a DIY project. I ask because if there is no DAC chip connected to it your errors start to make more sense.

**Comment by rohoog** [comment]
I use the spdif output of the SA9023 to drive toslink optical.
No need for a DAC on the I2S.

**Comment by JasonLG1979** [comment]
The next question then becomes does the device on the other end of the cable support 24_3? 24_3 is mostly just used by over USB.

**Comment by rohoog** [comment]
When I try the same device on another (X86_64 instead of aarch64) machine, it works with `speaker-test -D hw:CARD=Audio,DEV=0 -c 2 -F S24_3LE`.
It is not the SA9023, it is likely the `snd_usb_audio` driver in the aarch64 linux kernel.

**Comment by rohoog** [comment]
Yes the S24_3 is over USB, the spdif frame is full 32 bit samples where only 24 bits are used (8 bits 0 padded).

I agree, definitely no librespot issue. Thanks for the good suggestions anyway.

**Comment by JasonLG1979** [comment]
S24_3 is not the same as S24. S24 is 24 bits packed in a 32 bit container (padded) But S24_3 is not. It's 24 bits packed in a 24 bit container (unpadded). I know basically nothing about spdif and if that matters at all? Since it works on x86 it must not?

**Comment by rohoog** [comment]
I created an issue for [raspberrypi/linux](https://github.com/raspberrypi/linux/issues/5075).
