### ISSUE TITLE
Error 'not permitted'

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#102]
<a href="https://github.com/gfro84"><img src="https://avatars1.githubusercontent.com/u/29185828?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gfro84](https://github.com/gfro84)**
_Friday Jan 12, 2018 at 20:41 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/272_

----

Hello,

I can't play music tonight. Phone says it's connected to librespot but no audio. Get the following error message 

WARN:mdns::fsm: error sending packet Error { repr: Os { code: 1, message: "Operation not permitted" } }

Any insights?

Thanks
George

**Comment by sashahilton00** [comment]
<a href="https://github.com/gfro84"><img src="https://avatars1.githubusercontent.com/u/29185828?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gfro84](https://github.com/gfro84)**
_Friday Jan 12, 2018 at 20:43 GMT_

----

I should add worked fine yesterday....

**Comment by ComlOnline** [comment]
@gfro84 is this still an issue?

**Comment by gfro84** [comment]
I gave up on it but got it going again with a reinstall. Changed absolutely nothing but starting to think an OSMC update might have caused it. In any case, issue closed, thanks for asking. George

**Comment by ComlOnline** [comment]
Thanks!
