### ISSUE TITLE
Not working any more? (fixed: related to #972, workaround found there)

### ISSUE THREAD

**Issue by Woodhousemelena** [librespot-org/librespot#1022]
At this time, since appx 15 july I am unable to play any tracks to my librespot instance, part of my moodeaudio set up.
Librespot is visible to Spotify as a player in the network, and I am able to switch to it. It will however not play any sound and will simply skip wildly through the playlist. Sometimes it seems to be playing normally, but no sound from the speakers....

Anyone else having this issue?

**Comment by JasonLG1979** [comment]
You should file a bug report 1st with moodeaudio. If they deem it specifically to be a librespot issue you would then need to provide some basic info like hardware info and logs. Saying "it worked before but now it doesn't." is not useful.

**Comment by Woodhousemelena** [comment]
I understand what you are saying .A bugreport has already been submitted at moode audio. I suspect the spotify people may have made some change. I think many more may be experiencing this problem, but I wanted to check first if any users here have the same problem. It looks like it works properly for you or is that the wrong conclusion?

**Comment by JasonLG1979** [comment]
Based purely on a hunch it's probably related to https://github.com/librespot-org/librespot/issues/972

**Comment by JasonLG1979** [comment]
Also if a bug report has been submitted you link to it in this issue.

**Comment by Woodhousemelena** [comment]
Thank you Jason. I managed to "work around" it through a tip in that thread! 

By adding  104.199.65.124 ap-gew4.spotify.com  to /etc/hosts

**Comment by JasonLG1979** [comment]
> Thank you Jason. I managed to "work around" it through a tip in that thread!
> 
> By adding 104.199.65.124 ap-gew4.spotify.com to /etc/hosts

Then close this as a duplicate.

**Comment by Woodhousemelena** [comment]
Duplicate of https://github.com/librespot-org/librespot/issues/972

**Comment by Woodhousemelena** [comment]
Duplicate of https://github.com/librespot-org/librespot/issues/972
