### ISSUE TITLE
`new-api` is no longer needed in test workflow

### ISSUE THREAD

**Issue by michaelherger** [librespot-org/librespot#1031]
See https://github.com/librespot-org/librespot/blob/e9f3b6d2901be90bc373af0829485e7dcc7ab86b/.github/workflows/test.yml#L6

**Comment by roderickvd** [comment]
Good catch. You want to put in a PR?

**Comment by michaelherger** [comment]
Done - https://github.com/librespot-org/librespot/pull/1032

Do you have a policy of no merge without PR? I would have thought it would be easier for you to just DIY 😀.

Thanks for your ongoing effort! Looking forward to giving latest development a try! I'm using a fork and am updating it with latest dev right now. Will be interesting to see the outcome.

**Comment by roderickvd** [comment]
That was the policy but I’m being a bit more liberal with it myself.

Generally I appreciate all work others can take out of my hands — it’s easy for me to hit the merge button on GitHub and doesn’t require me to have my own development environment with me. 

Really encouraging to hear everyone picking up development and contributing!
