### ISSUE TITLE
Librespot Spotify connection error

### ISSUE THREAD

**Issue by maartenweyns** [librespot-org/librespot#1035]
My librespot installation is unable to play any music and crashes upon connection with the following error:

`could not initialize spirc: Permission denied { Login failed with reason: Try another AP } `

I feel like I'm missing some configuration or something. Can someone point me in the right direction?

I'm using version `0.5.0-dev`

**Comment by roderickvd** [comment]
Would you please post the full verbose logs?

**Comment by hamishlow** [comment]
I have a similar issue using librespot via Volumio, MoOde or balena sound... Here's the error message from balena sound but given the similarity of the problems with Spotify connect across the three different platforms I'm fairly sure this is a librespot issue:

` spotify  [2022-07-30T00:54:27Z INFO  librespot_core::session] Connecting to AP "ap-gae2.spotify.com:4070"
 spotify  [2022-07-30T01:04:28Z WARN  librespot] Connection failed: Cannot create session: early eof
 spotify  [2022-07-30T01:07:16Z INFO  librespot_core::session] Connecting to AP "ap-gae2.spotify.com:4070"
 spotify  [2022-07-30T01:07:17Z INFO  librespot_core::session] Authenticated as "hamish.low" !
 spotify  [2022-07-30T01:07:17Z INFO  librespot_playback::mixer::softmixer] Mixing with softvol and volume control: Linear
 spotify  [2022-07-30T01:07:17Z INFO  librespot_playback::convert] Converting with ditherer: tpdf
 spotify  [2022-07-30T01:07:17Z INFO  librespot_playback::audio_backend::pulseaudio] Using PulseAudioSink with format: S16
 spotify  [2022-07-30T01:07:17Z INFO  librespot_core::session] Country: "NZ"
 spotify  [2022-07-30T01:07:18Z INFO  librespot_playback::player] Loading <Paert: Tabula Rasa, I. Ludus - Con moto> with Spotify URI <spotify:track:5dR2YTRxvWDQFqnd7gKUhu>
 spotify  [2022-07-30T01:07:27Z WARN  librespot_playback::player] Player::pause called from invalid state
 spotify  [2022-07-30T01:07:28Z INFO  librespot_playback::player] <Paert: Tabula Rasa, I. Ludus - Con moto> (632106 ms) loaded
 spotify  [2022-07-30T01:07:28Z WARN  librespot_playback::player] This track will at its peak be subject to 4.80 dB of dynamic limiting.
 spotify  [2022-07-30T01:07:28Z WARN  librespot_playback::player] Please lower pregain to avoid.
 spotify  [2022-07-30T01:07:36Z ERROR librespot_core::session] Connection reset by peer (os error 104)
 spotify  [2022-07-30T01:07:36Z WARN  librespot_audio::fetch::receive] Error from channel for data receiver for range 838972 (+16384).
 spotify  [2022-07-30T01:07:36Z WARN  librespot_audio::fetch::receive] Error from channel for data receiver for range 822588 (+16384).
 spotify  [2022-07-30T01:07:36Z WARN  librespot_audio::fetch::receive] Error from channel for data receiver for range 806204 (+16384).
 spotify  [2022-07-30T01:07:36Z WARN  librespot_audio::fetch::receive] Error from channel for data receiver for range 855356 (+16384).
 spotify  [2022-07-30T01:07:36Z WARN  librespot_audio::fetch::receive] Error from channel for data receiver for range 871740 (+16384).
 spotify  [2022-07-30T01:07:36Z ERROR librespot_connect::spirc] subscription terminated
 spotify  [2022-07-30T01:07:36Z WARN  librespot] Spirc shut down unexpectedly

`

**Comment by roderickvd** [comment]
Typical case of temporary channel errors. If you search this repo you will find many cases like it. 

Since the original poster had not provided the requested feedback, I am closing this issue. Feel free to reopen with the information that I asked.
