### ISSUE TITLE
read from STDIN while playing a track

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#104]
<a href="https://github.com/wijnanb"><img src="https://avatars3.githubusercontent.com/u/506488?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wijnanb](https://github.com/wijnanb)**
_Monday Jan 22, 2018 at 21:28 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/274_

----

I am trying to adapt the [play.rs](https://github.com/plietar/librespot/blob/master/examples/play.rs) example to make it able to be controlled via STDIN.
As my experience with Rust is very minimal i am struggling with handling non-blocking IO.

My code is as follows:

```
loop {
        println!("Waiting for input");
        let stdin = std::io::stdin();
        let l = stdin.lock().lines().next().unwrap().unwrap();
        println!("Received input: {}", line);

        let next_track = SpotifyId::from_base62(&line);

        println!("Playing next track... {}", line);
        core.run(player.load(next_track, true, 0)).unwrap();
        // execution on this thread is blocked?
    }
```
How can we interrupt the execution of `core.run()? 

I have been reading on `core::handle` and `core::remote` but since I am used to node.js I am feeling a bit lost here ... ;-)

Can someone point me in the right direction?

**Comment by ComlOnline** [comment]
Hey @wijnanb, Please see #105 for more information on controlling from the command line. I don't think that this is something that we would be wanting for librespot and it's not meant to be controlled directly.
