### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#105]
<a href="https://github.com/tatoosh"><img src="https://avatars3.githubusercontent.com/u/3670907?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tatoosh](https://github.com/tatoosh)**
_Saturday Jan 27, 2018 at 09:04 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/275_

----

Is there a solution to control music Volumen by command line ?

**Comment by sashahilton00** [comment]
<a href="https://github.com/thekr1s"><img src="https://avatars2.githubusercontent.com/u/8556826?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [thekr1s](https://github.com/thekr1s)**
_Sunday Jan 28, 2018 at 00:03 GMT_

----

I don't think librespot is the place for this. You might have a look at  spotipy (https://github.com/plamere/spotipy) to create a python scrip to control the volume..

**Comment by ComlOnline** [comment]
Just to add for reference [spotcontrol](https://github.com/badfortrains/spotcontrol).
