### ISSUE TITLE
Link to maintained project

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#106]
<a href="https://github.com/Evidlo"><img src="https://avatars1.githubusercontent.com/u/5455841?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Evidlo](https://github.com/Evidlo)**
_Saturday Jan 27, 2018 at 22:41 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/276_

----

The folks at [librespot-org](https://github.com/librespot-org/librespot) have what looks to be a very active and maintained fork.

Perhaps you should link to it in the README?  This is still the first search result that comes up when searching for opensource spotify libs.

**Comment by ComlOnline** [comment]
Closed as this is the new fork
