### ISSUE TITLE
Mapping between Cached-Files and Track-ID

### ISSUE THREAD

**Issue by thomasbuesser** [librespot-org/librespot#1063]
Dear Developer-Team

as a happy user of your library i would like to ask a (silly) question:

is there a possibility to map the cached files back to a Track-ID from Spotify (or vice-versa)? 

Why this question: i would like to convert the stored OGG-Files with a onevent-script to a more "readable" file (from cache/0b/b710c11e795a700fdae62455a3be493fcc2410 to lets say cache/<Album>/<Track 01 - blabla>)

BRs
 Thomas

**Comment by roderickvd** [comment]
Probably. But as it would only give way to piracy, I won't have it. Sorry.
