### ISSUE TITLE
Cargo install SSL error

### ISSUE THREAD

**Issue by matbonucci** [librespot-org/librespot#1064]
Fails at around 20%

`    Updating crates.io index
error: failed to fetch `https://github.com/rust-lang/crates.io-index`

`Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli`
`
Caused by:
  SSL error: received early EOF; class=Ssl (16); code=Eof (-20)
`

x86/x64
Tried on Lubuntu and Elementary OS

**Comment by matbonucci** [comment]
Forgot to mention I have no proxy or VPN

**Comment by roderickvd** [comment]
This is not a `librespot` bug but with `cargo` having a network failure for whatever reason.
