### ISSUE TITLE
--device usage instructions not displayed

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#107]
When running a command such as ```./librespot --name "Librespot" --device ?```, a list of the audio devices should be printed. This is currently not the case, and nothing is printed, though the program will run as expected.

**Comment by ComlOnline** [comment]
From what I can tell this just isn't implemented.

**Comment by sashahilton00** [comment]
I concur

**Comment by plietar** [comment]
It is implemented in the portaudio backend, not in the ones that came afterwards

**Comment by sashahilton00** [comment]
Ah right. Do we want to just update the usage instructions with a note that it's for portaudio, as I don't believe this is applicable for other backends (iirc pulseaudio doesnt allow you to specify an audio device)?

**Comment by sashahilton00** [comment]
Closed by 60996d1
