### ISSUE TITLE
Compile error: playback/src/mixer/softmixer.rs:1:25 unresolved import `std::sync::atomic::AtomicU64`

### ISSUE THREAD

**Issue by pejobo** [librespot-org/librespot#1078]
**Describe the bug**
I use the docker image for cross compile (with the change described in #994) and get a compile error (see below).
**To reproduce**
1. Follow cross compile description in wiki, but patch Dockerfile to use debian:bullseye
2. See error

**Log**

````
   Compiling librespot-playback v0.4.2 (/src/playback)
error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
 --> playback/src/mixer/softmixer.rs:1:25
  |
1 | use std::sync::atomic::{AtomicU64, Ordering};
  |                         ^^^^^^^^^
  |                         |
  |                         no `AtomicU64` in `sync::atomic`
  |                         help: a similar name exists in the module: `AtomicU8`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `librespot-playback` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
````

**Host (what you are running `librespot` on):**
_does not apply_

**Additional context**
_does not apply_

**Comment by roderickvd** [comment]
I don’t know, I don’t use docker. Doesn’t it support 64-bit atomic? What is the host platform? And which Rust version does it run?

**Comment by pejobo** [comment]
The container sources rust from https://sh.rustup.rs, see https://github.com/librespot-org/librespot/blob/dev/contrib/Dockerfile#L29
So I assume it's the latest stable rust version.

**Comment by pejobo** [comment]
Sorry, I rebuild the container and the problem vanished. Closing.
