### ISSUE TITLE
Authentication failure should not panic, but exit without panic and a proper error message

### ISSUE THREAD

**Issue by michaelherger** [librespot-org/librespot#108]
Currently if authentication fails, librespot would panic

```
thread 'main' panicked at 'Authentication failed', /Users/mh/Dropbox/Squeezebox/git/spotty/target/debug/build/librespot-core-3ff3f374b034b2cc/out/lib.rs:388
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

This is ugly, as it's not an unexpected failure, but a very valid and to be expected error state. The panic message leads to many users ignoring the actual message about the authentication failure.

See https://github.com/librespot-org/librespot/blob/5f21c2582887b6f58aeb4a0900c5c28ee634ef98/core/src/connection/mod.rs#L70

**Comment by ComlOnline** [comment]
This is very related to #52.
The error needs to tell us that auth failed or the user is using a free account. 
I'll close that issue.

**Comment by sashahilton00** [comment]
In light of the recent decision to try and separate librespot into the core library, and a more featureful easy to use daemon, I'm inclined to suggest that we leave this be, as panicking is the correct behaviour if an invalid/free account is used. What we could do is add an extra line to the output at an info level which tells people that either their password is bad, or they're using a free account. I'm not sure there is a way to distinguish between auth failed and free accounts, as typically the user would not see the option to use spotify connect when using a free account.

**Comment by ComlOnline** [comment]
As long as it says it could be either in a clear way, I'm sure they will figure it out. (I hope)

**Comment by sashahilton00** [comment]
Have added an error message in PR referenced above. Please let me know if you're satisfied that it's informative enough, then will merge, corrections notwithstanding.

**Comment by ComlOnline** [comment]
Sorry I'm MIA, currently on holiday in Canada, Yeah That works great, Through from the sounds of it Paul thinks it may be possible to actually differentiate between auth failed and not premium. Either way good work!
