### ISSUE TITLE
Librespot stopped being available

### ISSUE THREAD

**Issue by microfx** [librespot-org/librespot#1128]
Hey folks!

Sadly my librespot became unresponsible "suddenly" for the first time. I had to restart the service. It worked minutes before that.

This is the systemd log: 
```
Mar 13 17:19:04 MiCROLABS-P3 librespot[1000]: [2023-03-13T16:19:04Z WARN  libmdns::fsm] couldn't parse packet from 192.168.0.35:5353: query type 65 is invalid 
Mar 13 17:29:41 MiCROLABS-P3 librespot[1000]: [2023-03-13T16:29:41Z INFO  librespot_playback::mixer::softmixer] Mixing with softvol and volume control: Log(60.0) 
Mar 13 17:29:41 MiCROLABS-P3 librespot[1000]: [2023-03-13T16:29:41Z INFO  librespot_playback::convert] Converting with ditherer: tpdf 
Mar 13 17:29:41 MiCROLABS-P3 librespot[1000]: [2023-03-13T16:29:41Z INFO  librespot_playback::audio_backend::rodio] Using Rodio sink with format S16 and cpal host: JACK 
Mar 13 17:29:41 MiCROLABS-P3 librespot[1000]: [2023-03-13T16:29:41Z INFO  librespot_playback::audio_backend::rodio] Using audio device: cpal_client_out-01 
```

Also I saw that the raspberry pi is no longer reachable with its .local address for SSH  (only without the .local). I am trying to understand for month how this DNS stuff works ... I have  no clue still. I am running Shairport and Librespot which both use avahi. And I don't understand how it is supposed to work properly (I recently saw that one is advertising itself with name-2.local). 

Maybe there this is caused by this?

Cheers

**Comment by eladyn** [comment]
I probably can't help with your original issue, only

> I am running Shairport and Librespot which both use avahi.

judging by your logs, your `librespot` isn't using avahi, but [`libmdns`](https://github.com/librespot-org/libmdns). You'd need to enable `with-dns-sd` to make `librespot` use avahi instead. Maybe that information helps you in some way to understand what's going on. :sweat_smile:
