### ISSUE TITLE
Nightly feature flag non existent

### ISSUE THREAD

**Issue by ComlOnline** [librespot-org/librespot#113]
In the master branch of librespot the `nightly` flag does not exist, see [here](https://github.com/librespot-org/librespot/blob/master/Cargo.toml#L63). However in the v0.2 branch from plietar we can see that it is still there, see [here](https://github.com/plietar/librespot/blob/v0.2/Cargo.toml#L76).

In the v0.2 branch this is the nightly flag:
```
nightly = ["serde_derive"]
```

Should it be added back in as an option or is it now unneeded and the wiki changed?

**Comment by sashahilton00** [comment]
i don't believe it does anything in the current version, though @plietar would be the best person to talk to about that. the v0.2 branch was the beginning of a rewrite for librespot, but serde_derive doesn't look to do much, given that Serialize and Deserialize are already in use from the serde_json library...

**Comment by plietar** [comment]
`serde_derive` has been working on Rust stable since 1.16. I'm pretty sure the recommendation in the readme is just a left over from a while ago and can be deleted now.

**Comment by sashahilton00** [comment]
Closing then, as readme has no mention of nightly flag. Reopen if necessary.
