### ISSUE TITLE
Setting up dns-sd failed

### ISSUE THREAD

**Issue by truppelito** [librespot-org/librespot#1138]
**Describe the bug**
I'm on a RaspberryPi 4 using Raspberry Pi OS. All software is up-to-date (I do regular updates, as far as I can tell everything is up-to-date). Librespot is installed but is unable to run due to some DNS error.

**To reproduce**
Run the following command:

```
pi@raspberrypi:~$ librespot --device plughw:CARD=Headphones,DEV=0 --name TEST --initial-volume 50 --enable-volume-normalisation
[2023-03-30T13:37:28Z INFO  librespot] librespot 0.4.2 d6124bc (Built on 2023-03-29, Build ID: gsYlQmIw, Profile: release)
[2023-03-30T13:37:28Z WARN  librespot] Could not initialise discovery: Setting up dns-sd failed: No buffer space available (os error 105)
[2023-03-30T13:37:28Z ERROR librespot] Discovery is unavailable and no credentials provided. Authentication is not possible.
```

**Additional context**
Sometimes (this is not 100% consistent, I think), it seems like librespot works for some time after reboot, then eventually stops showing up on Spotify on my phone or computer, then I try to get it to run again but it produces the error above. I can confirm that the command has worked in the past, and that this is a relatively recent bug (maybe in the last few months).

**Comment by kingosticks** [comment]
From what I can see, Mdns error 105 is probably not a librespot bug. 

https://blog.mphomphego.co.za/blog/2017/06/28/why-am-i-getting-errno105-no-buffer-space-available-when-subscribing-to-multicast-addresses.html looks relevent.

**Comment by truppelito** [comment]
That seems to have fixed it! I'm closing this bug report. In case this problem comes back, I'll open it again.
