### ISSUE TITLE
Playback issue with BlueTooth headphones?

### ISSUE THREAD

**Issue by benmanone** [librespot-org/librespot#1166]
Whenever I use an app which uses librespot (ncspot, gspt, spt) with a pair of BlueTooth headphones there is a noticeable crackling sound, especially when I type. This never happens when using builtin speakers or wired headphones. I'm on a MacBook Air 2019 and the headphones are Beats brand, setup to use 2ch 32-bit Float 48.0kHz.

**Comment by benmanone** [comment]
Works completely fine with everything else. Yes I agree with you it's probably something on my end, do you know what could cause something like this?

**Comment by roderickvd** [comment]
Closing, sorry, can't provide specific help.
