### ISSUE TITLE
Expose AuthenticationError enum

### ISSUE THREAD

**Issue by beaverking1212** [librespot-org/librespot#1167]
**Is your feature request related to a problem? Please describe.**
There is a problem. When calling `Session::connect()` it is hard to determine whether login has failed or another error occurred.

**Describe the solution you'd like**
I want to be able to check whether `Session::connect()` returned error due to failed login.

**Describe alternatives you've considered**
Alternative is converting error to text, it works, but looks fragile.
https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/blob/ea26d0d6d50bc0fd394c8934b14d18266671264b/audio/spotify/src/common.rs#L170

**Additional context**
Problem was noticed in: https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/merge_requests/1195

**Comment by beaverking1212** [comment]
@gdesmott

**Comment by kingosticks** [comment]
FYI this is fixed in dev branch

**Comment by 4310V343k** [comment]
> FYI this is fixed in dev branch

Can you link the commit? I don't think `librespot::core::connection::AuthenticationError` is exported anywhere

**Comment by kingosticks** [comment]
https://docs.rs/librespot-core/0.7.1/librespot_core/authentication/enum.AuthenticationError.html

**Comment by 4310V343k** [comment]
> [docs.rs/librespot-core/0.7.1/librespot_core/authentication/enum.AuthenticationError.html](https://docs.rs/librespot-core/0.7.1/librespot_core/authentication/enum.AuthenticationError.html)

The `AuthenticationError` enum mentioned is located in `librespot::core::connection::AuthenticationError`, not `librespot::core::authentication::AuthenticationError`

**Comment by kingosticks** [comment]
Yep, sorry, you are right. I didn't look hard enough at what you were asking and then lost this one.

I don't think there is a real reason we don't expose it other than it lives in a module we don't generally expose. I think agree it's useful and worth improving. What's the easiest way to expose just that? Can you submit a PR?

**Comment by 4310V343k** [comment]
> What's the easiest way to expose just that?

Similar to this, perhaps?
https://github.com/librespot-org/librespot/blob/a407beaa45e140f492f9cc5b3c5cdd3c7fe2ad69/core/src/lib.rs#L41-L46

**Comment by kingosticks** [comment]
Feel free to submit an appropriate PR. Please include a changelog entry.
