### ISSUE TITLE
Playback stops when playlist ends

### ISSUE THREAD

**Issue by rwjack** [librespot-org/librespot#1170]
**Describe the bug**
It's almost as if this option (screenshot from spotify client) doesn't exist in librespot
![image](https://github.com/librespot-org/librespot/assets/59068073/ce69d2a7-e5f8-47d9-ac90-dc2c3cb4e735)

**Host (what you are running `librespot` on):**
- OS: Linux
- Platform: Home Assistant Container
```
ARG BUILD_FROM
FROM $BUILD_FROM

# Add env
ENV LANG C.UTF-8

RUN \
    apk add --no-cache --virtual .build-dependencies \
        build-base=0.5-r3 \
        cargo=1.60.0-r2 \
        git \
        protobuf-dev=3.18.1-r3 \
        pulseaudio-dev=15.0-r2 \
    \
    && apk add --no-cache \
        pulseaudio=15.0-r2 \
    \
    && cargo install \
        --locked \
        --no-default-features \
        --features pulseaudio-backend \
        --root /usr \
        --bin librespot \
        --version 0.4.2 \
        --verbose \
        -- librespot \
    \
    && apk del --no-cache --purge .build-dependencies \
    && rm -fr \
        /tmp/* \
        ~/.cargo \
        /usr/.crates.toml \
        /usr/.crates2.json

#Install snapcast
RUN sed -i -e 's/v[[:digit:]]\..*\//edge\//g' /etc/apk/repositories && apk add --no-cache snapcast bash

# Copy data for add-on
COPY run.sh /
RUN chmod a+x /run.sh

CMD [ "/run.sh" ]
```

**Comment by eladyn** [comment]
Oh, didn't notice that you are on 0.4.2. At this point, the autoplay option in the official client indeed doesn't affect librespot, and you need to turn `--autoplay on` manually.

**Comment by kingosticks** [comment]
> Interesting. I sure would like to try out the dev branch, but I have no idea how to modify this Dockerfile in order to do so.

The [top few Google hits](https://duckduckgo.com/?t=ffab&q=cargo+install+from+git&atb=v351-1&ia=web) sound pretty promising, maybe:

```
&& cargo install \
        --locked \
        --no-default-features \
        --features pulseaudio-backend \
        --root /usr \
        --bin librespot \
        --git https://github.com/librespot-org/librespot \
        --branch dev \
        --verbose \
        -- librespot \
```

**Comment by rwjack** [comment]
I'm building my container to start librespot with the `--autoplay on` flag. Let me see how it works

**Comment by eladyn** [comment]
@rwjack Indeed, that probably doesn't belong here then, but snapcast [expects `true`](https://github.com/badaix/snapcast/blob/481f08199ca31c60c9a3475f1064e6b06a503d12/server/streamreader/librespot_stream.cpp#L76) instead of `on` for the `autoplay` option.

**Comment by rwjack** [comment]
Well damn, you got me confused here:

> Oh, didn't notice that you are on 0.4.2. At this point, the autoplay option in the official client indeed doesn't affect librespot, and you need to turn --autoplay on manually.

**Comment by roderickvd** [comment]
Pretty sure this is not a librespot bug, so closing, but feel free to continue the discussion here or on Gitter.
