### ISSUE TITLE
Feature Request: loop one song in a playlist

### ISSUE THREAD

**Issue by vikanezrimaya** [librespot-org/librespot#1172]
**Is your feature request related to a problem? Please describe.**
When remotely controlling the librespot CLI, there seems to be no way to make it loop one song only. The only choices are loop playlist or no looping at all.

**Describe the solution you'd like**
Somehow expose the ability to loop one song, if that is possible.

**Describe alternatives you've considered**
 - Using a different client, such as [Spot](https://github.com/xou816/spot), which supports this feature
   - sadly, Spot doesn't seem to have remote control
 - Creating a playlist per-song
   - I did have this thought, but I decided against it as it would be too clunky

**Additional context**
n/a

**Comment by eladyn** [comment]
If I'm not mistaken, this should be #19 and a recent update can be found [here](https://github.com/librespot-org/librespot/issues/19#issuecomment-1263968137).

**Comment by roderickvd** [comment]
Indeed a duplicate.
