### ISSUE TITLE
Play example needs to be updated

### ISSUE THREAD

**Issue by AramZS** [librespot-org/librespot#1215]
**Describe the bug**
The example at: 

https://github.com/librespot-org/librespot/blob/dev/examples/play.rs

No longer reflects the current state of the library and should be updated. Specifically I think `Session::new` no longer works and needs to be replaced with `Session::connect`?

**Comment by eladyn** [comment]
At least for me, compiling and running the example is working fine. What isn't working in your case?

**Comment by gillesB** [comment]
@AramZS I was also confused by this (partly because I am new to Rust). But actually `Session::new` is the newer function which was introduced in the current development cycle. In the latest release `0.4.2` this function does not exist yet.

**Comment by roderickvd** [comment]
All examples up to date now, right?
