### ISSUE TITLE
librespot/snapcast sometimes plays like /dev/random :fearful: 

### ISSUE THREAD

**Issue by cdtx** [librespot-org/librespot#1218]
Hi,

``` text
librespot: 0.4.2
snapserver v0.27.0
``` 

I'm trying to solve an annoying issue in my snapcast/librespot installation.

In a few words : When I move between tracks in spotify OR move to another time in the current track, sometimes it works, sometimes my whole snapclients plays random noise very loud !
I'm not alone with this issue : https://github.com/badaix/snapcast/issues/1170

Guys at snapcast (see above ticket) are wondering if librespot could be the one responsible ?
snapcast collects samples from the librespot STDOUT, and suggestion is that librespot could sometimes emit someting else on it's STDOUT (log) ? Or crash ?

Does this situation rings you sometings ?

Thanks

**Comment by cdtx** [comment]
> Or crash ?

I just see that librespot has the same pid before and after the bug occurs. So I'm sure it does not crash.

**Comment by roderickvd** [comment]
I think that issue over at https://github.com/badaix/snapcast/issues/1170 is raising the right questions to isolate the problem.

librespot doesn't output anything else to stdout, that I know.

**Comment by cdtx** [comment]
> librespot doesn't output anything else to stdout, that I know.

I confirm that I did the test to pipe librespot to vlc then run my "recipe", nothing wrong !
I go back to snapcast for a printf hunt ;-)

Thanks
