### ISSUE TITLE
[Feature Request] Allow downloading of playlists for listening offline

### ISSUE THREAD

**Issue by Diegovsky** [librespot-org/librespot#1243]
I've been visiting a bunch of places without good internet connectivity and I'm wondering if there's a way to ask for playlists to be downloaded like the official client does.

A possible solution would be to add some new API for this. From a super quick reading of [these docs](https://docs.rs/librespot-audio/0.4.2/librespot_audio/enum.AudioFile.html), it seems librespot already supports downloading songs, but only to optimize playback. I suppose adding this would be possible with what `librespot` already has. For example, a new variant called `Downloaded` could be added that holds a `File`, just like `Cached`. 

One problem with this would be that downloaded files need to be encrypted or something to prevent copyright issues.

What do you think?

**Comment by roderickvd** [comment]
Indeed, we won't do offline downloads for reasons of T&Cs.

**Comment by Diegovsky** [comment]
> Indeed, we won't do offline downloads for reasons of T&Cs.

An unfortunate thing but I can live with that
