### ISSUE TITLE
Authentication on all desktop platforms is broken

### ISSUE THREAD

**Issue by lmore377** [librespot-org/librespot#1245]
**Describe the bug**
Attempting to start Spotify Connect from any desktop client results in 403 errors, similar to issue #1179. If started from android or iOS, authentication works fine. If librespot is given credentials with `-u` and `-p` then desktop clients work but only for the logged in user.

**To reproduce**
1. Launch `librespot` without `-u` or `-p`
2. Connect with any desktop client (Windows, Linux, macOS)
3. Click play on any song
4. Console fills with 403 and similar errors

**Log**
This log is from me connecting from a linux client but the output is almost identical to windows & macos. I obfuscated some IDs but the log is otherwise as-is. I ran librespot with `-G -H` to prevent any issues from caching.

[linux.log](https://github.com/librespot-org/librespot/files/13993995/linux.log)

**Host (what you are running `librespot` on):**
- OS: Debian 12
- Platform: x86_64

**Additional context**
This issue is fixed by #1220 but I noticed that the PR seems stale. Could I create my own PR with the same changes?

**Comment by roderickvd** [comment]
> **Additional context** This issue is fixed by #1220 but I noticed that the PR seems stale. Could I create my own PR with the same changes?

Of course, or maybe clone that user's branch, resolve the outstanding review comments and we'd be good to go!
