### ISSUE TITLE
Librespot causing Spocon to pause/not work?

### ISSUE THREAD

**Issue by floodwayprintco** [librespot-org/librespot#1264]
My owntone server will be playing music perfectly, and then it will pause. We will need to either start new playlist/song, go the next song. Nothing we can do will unpause it in Owntone. Logs from two users be seen in my Spocon issue here: https://github.com/spocon/spocon/issues/62

To Reproduce

Play music through Owntone using Spocon. Eventually the music will pause.

Try to unpause it on Owntone, nothing happens.

Expected behavior

It should not pause randomly.

Screenshots
I have a video showing the behaviour but I cannot attach it directly.

Logs
If applicable, execute journalctl -u spocon -f --no-pager and paste the result here

I am running a log now and will see if I can catch anything.

Running on a Rasperry Pi 4B+ with SSD, i thought it might be the SD card but apparently not.

**Comment by floodwayprintco** [comment]
Here is why I think it's Librespot related:

`Jan 10 15:05:11 pi-music-server java[1175]: xyz.gianlu.librespot.audio.AbsChunkedInputStream$ChunkException: java.io.IOException: 404: Not Found
Jan 10 15:05:11 pi-music-server java[1175]:         at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:322) ~[librespot-java-api-v1.6.2.jar:1.6.3]
Jan 10 15:05:11 pi-music-server java[1175]:         at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer.access$1500(CdnManager.java:198) ~[librespot-java-api-v1.6.2.jar:1.6.3]
Jan 10 15:05:11 pi-music-server java[1175]:         at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:398) ~[librespot-java-api-v1.6.2.jar:1.6.3]
Jan 10 15:05:11 pi-music-server java[1175]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Jan 10 15:05:11 pi-music-server java[1175]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Jan 10 15:05:11 pi-music-server java[1175]:         at java.lang.Thread.run(Thread.java:829) [?:?]
Jan 10 15:05:11 pi-music-server java[1175]: Caused by: java.io.IOException: 404: Not Found
Jan 10 15:05:11 pi-music-server java[1175]:         at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer.request(CdnManager.java:338) ~[librespot-java-api-v1.6.2.jar:1.6.3]
Jan 10 15:05:11 pi-music-server java[1175]:         at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer.request(CdnManager.java:328) ~[librespot-java-api-v1.6.2.jar:1.6.3]
Jan 10 15:05:11 pi-music-server java[1175]:         at xyz.gianlu.librespot.audio.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:318) ~[librespot-java-api-v1.6.2.jar:1.6.3]
Jan 10 15:05:11 pi-music-server java[1175]:         ... 5 more`

**Comment by kingosticks** [comment]
Wrong repo: https://github.com/librespot-org/librespot-java
