### ISSUE TITLE
Can't play new songs (released on current day). Automatically skipping.

### ISSUE THREAD

**Issue by piotrdro** [librespot-org/librespot#1268]
**Describe the bug**
When using raspotify with librespot I can't play new songs for a day. If song gets released on 21st March - I can only play it on 22nd March.

**To reproduce**
Launch raspotify + librespot and try to play this song: https://open.spotify.com/track/1y6BLlPX3H2i9ziz4OMZTs 

**Log**
```
Mar 21 16:21:27 DietPi librespot[28436]: [2024-03-21T16:21:27Z WARN  librespot_playback::player] <spotify:track:1y6BLlPX3H2i9ziz4OMZTs> is not available
Mar 21 16:21:27 DietPi librespot[28436]: [2024-03-21T16:21:27Z ERROR librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 676997391702315191474572864541650
03074, audio_type: Track }>: ()
```

**Host (what you are running `librespot` on):**
- OS: dietpi
- Platform: RPi 4B

**Comment by roderickvd** [comment]
Maybe a timezone thing, maybe a logic thing. Please provide full logs _as well as_ your local timezone and local time.

**Comment by roderickvd** [comment]
No feedback, closing.
