### ISSUE TITLE
request a new release

### ISSUE THREAD

**Issue by chenrui333** [librespot-org/librespot#1279]
it has been almost two years, and good to have a new release to include the recent changes. Thanks! ([0.4.2 failed to build against rust 1.78.0](https://github.com/Homebrew/homebrew-core/pull/170649))

**Comment by knedl1k** [comment]
up

**Comment by chenrui333** [comment]
cc @roderickvd

**Comment by roderickvd** [comment]
To cut a release I want to make sure that it’s running well and can get follow up support when issues come in. We owe that to our users who probably run this on thousands of devices. 

I don’t use Spotify or even have an account on it anymore. So what we need are active contributors and maintainers.

I’m leaving on holidays without access to my development chain. If you guys can let me know who’ll be here to support a release when I cut one, it can be as soon as in three weeks.

**Comment by kingosticks** [comment]
Out of interest, what are you people requesting here? Small fixes i.e. v0.4.3 (would have to find what could be easily backported from dev, might not be much). Or a major release from the dev branch with the breaking api changes and major differences that come with it?

**Comment by kingosticks** [comment]
(because one requires minimal support, the other requires loads)

**Comment by chenrui333** [comment]
I would say both, but we can start the former and then move to the latter (maybe some beta releases before the actual major release as well.) generally, the more releases, so that the more people can test and give feedback.

**Comment by roderickvd** [comment]
I'd be up for a release after #1309. My point about depending on you guys remains.

**Comment by bitclick** [comment]
this has become somewhat urgent, given that the previous release seems to have stopped working entirely, see https://github.com/librespot-org/librespot/issues/1322

**Comment by bitclick** [comment]
There is currently no working release. Maybe you could provide snapshot binaries.  

I understand that the new version is not yet ready for a release.  In the current situation, many people are trying to compile `dev` over and over again..  I am sure, many more would be very grateful 🙂

**Comment by roderickvd** [comment]
Yes, we are going to do final touch-up and review of #1309 and then get 0.5 out of the door.

Depending on what @kingosticks can muster up coming days, and when I can find some spare time, target is "soon". As in, I'd love to do it this weekend or some upcoming evening but life is busy.
