### ISSUE TITLE
Librespot starts spamming the new status of the song

### ISSUE THREAD

**Issue by fabirednik** [librespot-org/librespot#1290]
**Describe the bug**
After listening to music for x amount of time, Librespot starts spamming the new status of the song, which causes interruptions in the music and a bugging progress bar on Spotify.

**Log**
Jun 01 14:41:02 rednikbox bash[1838]: [2024-06-01T12:41:02Z TRACE librespot_connect::spirc] ==> kPlayStatusPlay
Jun 01 14:41:02 rednikbox bash[1838]: [2024-06-01T12:41:02Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
Jun 01 14:41:06 rednikbox bash[1838]: [2024-06-01T12:41:06Z TRACE librespot_connect::spirc] ==> kPlayStatusPlay
Jun 01 14:41:06 rednikbox bash[1838]: [2024-06-01T12:41:06Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
Jun 01 14:41:10 rednikbox bash[1838]: [2024-06-01T12:41:10Z TRACE librespot_connect::spirc] ==> kPlayStatusPlay
Jun 01 14:41:10 rednikbox bash[1838]: [2024-06-01T12:41:10Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
Jun 01 14:41:13 rednikbox bash[1838]: [2024-06-01T12:41:13Z TRACE librespot_connect::spirc] ==> kPlayStatusPlay
Jun 01 14:41:13 rednikbox bash[1838]: [2024-06-01T12:41:13Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
Jun 01 14:41:17 rednikbox bash[1838]: [2024-06-01T12:41:17Z TRACE librespot_connect::spirc] ==> kPlayStatusPlay
Jun 01 14:41:17 rednikbox bash[1838]: [2024-06-01T12:41:17Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]

**Host (what you are running `librespot` on):**
- OS: Linux
- Platform: Raspberry pi zero

**Additional context**
Restart helps, but not for long, now maybe this is my 5th such case, and I've been using librespot since yesterday

**Comment by fabirednik** [comment]
> Please provide a full debug log.

There is nothing else about the problem in the logs

**Comment by roderickvd** [comment]
Still, I'd like to see it. Without it, it is anyway unactionable and I will have to close this issue.
Do let me know when you've further isolated it.

From the issue template:

```
**Log**
A full log so we may trace your problem (launch `librespot` with `--verbose`). Format the log as code.
```

**Comment by fabirednik** [comment]
> Still, I'd like to see it. Without it, it is anyway unactionable and I will have to close this issue.
> Do let me know when you've further isolated it.
> 
> From the issue template:
> 
> ```
> **Log**
> A full log so we may trace your problem (launch `librespot` with `--verbose`). Format the log as code.
> ```

Please reopen this issue, I will send logs in few days, now i'm not at home

**Comment by fabirednik** [comment]
@roderickvd
