### ISSUE TITLE
Tidal Connect

### ISSUE THREAD

**Issue by nasawyer7** [librespot-org/librespot#1300]
I love what librespot does, and the kodi addon you guys have created. Recently, I switched to tidal for the higher quality, and I was wondering if there is a plan to support tidal connect streaming in a similar addon, since it is extremely difficult to integrate with kodi otherwise.

Tidal would definitely come with more complications, like streaming flaq instead (and MQA, but no one streams that anyways so that could be skipped), and a different API of course. I was also wondering how and where to start to try to create an addon like this myself, and if you guys would suggest anything I should read or understand before trying to create an addon. This is not meant to be a "please make this im mad post" its more of  a how can I get started on this myself, and wondering if this is ever an idea to consider!

**Comment by shanemeagher** [comment]
I think you are confusing a few different things. This is for the library / program that creates a Spotify Connect device.

The 'Kodi Addon' you are referring to is actually a LibreELEC addon that uses this library, and is separate to Kodi..
https://github.com/LibreELEC/LibreELEC.tv/issues?q=librespot+
https://forum.libreelec.tv/thread/8438-librespot-addon

You will have to request Tidal support there.
