### ISSUE TITLE
add logging hint to check the source sample rate on buffer underruns

### ISSUE THREAD

**Issue by bitclick** [librespot-org/librespot#1310]
**Is your feature request related to a problem? Please describe.**

i was having drop outs regularly and thought - oh my wifi sucks..
but it turns out i had setup librespot via pipe source and never set the sample rate to 44.1khz so i was getting 
a lot of ` next read < 0`  log output

i suffered from this more than 12 months :sweat_smile: 
i did not think further because the log never mentioned "drop out" or "warning" or something like this

**Describe the solution you'd like**
please ad a hint to the log output when buffer underruns occur like
"looks like the source is too slow, i am expecting xxx sample format. is this correct?" 

and maybe a link to this issue or some doc page https://github.com/librespot-org/librespot/issues/340

**Describe alternatives you've considered**
i think the problem is that it kinda works with mismatched sample rates so its not that obvious for the user to check the config.  i always thought the clients had buffer underruns and tweaked my wifi.  if the logs could make the distinction more explicit, this would help a lot of people..

**Comment by kingosticks** [comment]
> i had setup librespot via pipe source

This makes no sense. Are you talking about librespot or something using librespot? 

Either way, as [I said](https://github.com/librespot-org/librespot/issues/340#issuecomment-504499635) in the issue you linked:

> When using the pipe backend, raw PCM is written to the file as quickly as it's downloaded and it's entirely the job of the other side to handle playback 

How could librespot know that the consuming side of the pipe is underruning?

**Comment by bitclick** [comment]
ah sorry wrong project :sweat_smile:  got my tabs confused.  ment to post this here https://github.com/badaix/snapcast
will close this.
