### ISSUE TITLE
"Too many errors"

### ISSUE THREAD

**Issue by zoltan-k81** [librespot-org/librespot#1312]
Since recently, librespot is not visible on the network. when I try to restart, or re-enable the addon, it will show "too many errors".

- OS: [Libreelec 9.2.8]
- Platform: [RPi 4]

**Comment by roderickvd** [comment]
If you think this is a librespot bug, please provide a full verbose log of librespot running stand alone.
If it's with the LibreELEC add-on, please post the issue there.

**Comment by zoltan-k81** [comment]
it's actually the LibreELEC add-on so moving there. Thanks.
