### ISSUE TITLE
AudioFiles not available for some tracks

### ISSUE THREAD

**Issue by x528491x** [librespot-org/librespot#1316]
Use the track 4LRPiXqCikLlN15c3yImP7 as input

```
// spotify:track:4LRPiXqCikLlN15c3yImP7

let x = AudioItem::get_file(&session, track_id).await.unwrap().files;
println!("{:?}", x);

// AudioFiles({})
```

**Comment by x528491x** [comment]
The audiofiles are available for the alternative track listed in the response.

Is this a general thing for Spotify - having to query alternative tracks?

It must also be noted that when the alternative track is queried, it does not list the original queried track as an alternative.

So what must be done in case Spotify had not grouped alternative tracks? How does one get the audiofiles then?

**Comment by kingosticks** [comment]
They will always provide alternate tracks if required. Why would you need a way to access the "original" track that you can't play?

Have you read https://developer.spotify.com/documentation/web-api/concepts/track-relinking ?

The general Spotify principles explained in their officla docs are often relevant to working with librespot.

**Comment by x528491x** [comment]
I'll close this issue, but "always provide alternative tracks if required".

Does that mean that if the track is found to be playable, the alternative track would automatically be empty,

Or does the developer need to check if the track is playable and then loop over the alternative tracks listed if any.

**Comment by kingosticks** [comment]
> Does that mean that if the track is found to be playable, the alternative track would automatically be empty,

I don't remember. But I recall they provide some field to describe the availability.

Look how this is done at https://github.com/librespot-org/librespot/blob/2ea7436e60750d56e747abfca3893be39c0162fd/playback/src/player.rs#L881 ?

**Comment by x528491x** [comment]
> > Does that mean that if the track is found to be playable, the alternative track would automatically be empty,
> 
> I don't remember. But I recall they provide some field to describe the availability.
> 
> Look how this is done at https://github.com/librespot-org/librespot/blob/2ea7436e60750d56e747abfca3893be39c0162fd/playback/src/player.rs#L881 ?

Thanks. That helped. Closing now.
