### ISSUE TITLE
Apply rustfmt to librespot-core and enforce it on travis

### ISSUE THREAD

**Issue by plietar** [librespot-org/librespot#132]
From what I've heard rustfmt is good enough now for this to be possible.
In most places librespot already uses the standard style, so the initial diff shouldn't be that bad.

**Comment by sashahilton00** [comment]
Just had a look at rustfmt, and it looks as though it's good to go on beta and nightly builds, and getting there on rust 1.24.0. Do we think the requirements for rust => 1.24.0 are worth it for adding rustfmt to the project?

**Comment by plietar** [comment]
@sashahilton00 Contributors will either need to have nightly locally so they can run rustfmt, but people who are just building don't need anything.

**Comment by sashahilton00** [comment]
Ok, could we perhaps add a brief note about contributors needing mightly, what rustfmt is, and what contributors need to run to the wiki? I can look at the website and work it out, but I feel like those who are just looking to help here and there probably aren't going to want to learn all about it, but rather have a brief overview of what it does, and what commands they need to run before committing.

**Comment by awiouy** [comment]
To use rustfmt:
Use [atom](https://atom.io/) and run rustfmt from atom as described [here](https://github.com/rust-lang-nursery/rustfmt/blob/master/atom.md).

**Comment by kingosticks** [comment]
It'd be helpful to have a general note for those that don't use atom.

**Comment by sashahilton00** [comment]
Hmmm, I'm still hesitant about this; although Atom is popular (I use it as well), I'm not sure our solution to adding rustfmt and enforcing it on travis should be 'use this IDE or go hunting around the web for some other instructions. Is there no way to execute rustfmt on the cli to show a list of changes that should be made?

**Comment by ComlOnline** [comment]
There is a suggestion to use nightly in the [wiki](https://github.com/librespot-org/librespot/wiki/Development), but something about how to use rustfmt would be handy. 

I use VS-Code and it has an addon for rustfmt as well as a bunch of others I've found after a google (vim, emacs and Sublime) 

As for running from command line have a look [here](https://github.com/rust-lang-nursery/rustfmt#installation).  
But be warned the default mode is overwrite, see [here](https://github.com/rust-lang-nursery/rustfmt#running) for more modes.
