### ISSUE TITLE
Unable to load encrypted file: ChannelError

### ISSUE THREAD

**Issue by rwjack** [librespot-org/librespot#1322]
**Describe the bug**
All of a sudden I can't play any song

**To reproduce**
1. Launch `librespot` with:
```
stream = spotify:///librespot?name=Spotify&devicename=HA_Snapcast&bitrate=320&volume=100&cache=/data/librespot&cache-size-limit=2G&autoplay=true&params=--disable-discovery
```
2. Play any song
3. Librespot starts skipping songs quickly and crashes within a few seconds.

**Log**
```
... SNIP ...
2024-09-02 16-08-33.834 [Info] (librespot_playback::player) Loading <Bliss> with Spotify URI <spotify:track:2wIBOetdiYn4ULg7j4jMg6>
2024-09-02 16-08-33.946 [Error] (librespot_core::channel) channel error: 2 0
2024-09-02 16-08-33.946 [Error] (librespot_playback::player) Unable to load encrypted file: ChannelError
2024-09-02 16-08-33.946 [Warn] (librespot_playback::player) Skipping to next track, unable to load track <SpotifyId { id: 110396896608779253385428011206135924654, audio_type: Track }>: ()
2024-09-02 16-08-33.987 [Info] (librespot_playback::player) Loading <Weightless> with Spotify URI <spotify:track:57bvTWSTYC2HLS3EjmmTgD>
2024-09-02 16-08-34.105 [Error] (librespot_core::channel) channel error: 2 0
2024-09-02 16-08-34.105 [Error] (librespot_playback::player) Unable to load encrypted file: ChannelError
2024-09-02 16-08-34.105 [Warn] (librespot_playback::player) Skipping to next track, unable to load track <SpotifyId { id: 223433050452273652531839940303864379059, audio_type: Track }>: ()
2024-09-02 16-08-34.224 [Info] (librespot_playback::player) Loading <Nara> with Spotify URI <spotify:track:4F8zNOrvP78IJAdrdZCo1z>
2024-09-02 16-08-34.268 [Error] (librespot_core::channel) channel error: 2 0
2024-09-02 16-08-34.268 [Error] (librespot_playback::player) Unable to load encrypted file: ChannelError
2024-09-02 16-08-34.268 [Warn] (librespot_playback::player) Skipping to next track, unable to load track <SpotifyId { id: 203675824406771647439050070553111732737, audio_type: Track }>: ()
2024-09-02 16-08-34.306 [Info] (librespot_playback::player) Loading <Endless Horizon> with Spotify URI <spotify:track:76RFgwdQlwsMi0vfA20gSV>
2024-09-02 16-08-34.432 [Error] (librespot_core::channel) channel error: 2 0
2024-09-02 16-08-34.432 [Error] (librespot_playback::player) Unable to load encrypted file: ChannelError
2024-09-02 16-08-34.432 [Warn] (librespot_playback::player) Skipping to next track, unable to load track <SpotifyId { id: 310556037841223247093127629046494693741, audio_type: Track }>: ()
2024-09-02 16-08-34.432 [Warn] (librespot_connect::spirc) No context to update from!
2024-09-02 16-08-34.544 [Error] (ProcessStream) Error while reading from stderr: End of file
2024-09-02 16-08-34.545 [Error] (AsioStream) Error reading message: End of file, length: 0, ec: asio.misc:2
2024-09-02 16-08-34.646 [Info] (Watchdog) Starting watchdog, timeout: 7800s
2024-09-02 16-08-34.647 [Info] (librespot) librespot 0.4.2 UNKNOWN (Built on 2023-08-01, Build ID: 1690865570, Profile: release)
2024-09-02 16-08-34.691 [Info] (librespot_core::session) Connecting to AP "ap2-gew1.spotify.com:4070"
2024-09-02 16-08-34.767 [Info] (AsioStream) No data since 120 ms, switching to idle
... SNIP ...
```

**Host (what you are running `librespot` on):**
- OS: Debian container, through Snapcast
- Platform: HAOS x86

**Comment by moretea** [comment]
Exact same issue here, on `nixos-23.11`. Will update to latest nixos, to see if it will work.

**Comment by RSKriegs** [comment]
I've just got the same today via raspotify. Funnily enough it seems to work at some random songs. I'm very confused

**Comment by guillaume-duroy** [comment]
Same here, been working for the past 4 years without a hitch and suddenly all songs are skipped due to a channel error.

**Comment by RSKriegs** [comment]
Folks I've attempted recompiling and it works when I connected directly to Librespot, do as described here (just compile to release) https://github.com/librespot-org/librespot/blob/dev/COMPILING.md

**Comment by joeadam** [comment]
I've got the same issue with librespot 0.4.1 88e64bd

**Comment by rwjack** [comment]
Am I the only one that's seriously mad for being monkeyed around, having to re-configure a working setup for the 100th time when a simple email to the Librespot dev team and 2 weeks notice would have sufficed.

Let me tell you a little secret, Spotify, truly, does not give a fuck, about it's customers, and let alone the artists. 

On the other hand look at us, loyal, paying customers, being fucked over for god knows what time in a row, amazing isn't it. 

The main question though, how far are going to let them push this stick up our ass?

How come, there still isn't no decentralized solution for streaming audio, where the artists also get their commission in FULL, no bullshit middleman.

Music is, and always should be by the people, for the people!

**Comment by LiD420** [comment]
Same started a couple of days ago.
ERROR librespot_playback::player] Unable to load encrypted file: ChannelError

**Comment by sowthistle** [comment]
@LiD420 

> My solution: /etc/hosts 0.0.0.0 apresolve.spotify.com 104.199.65.124 ap-gew4.spotify.com

Umm. Any chance of a brief explanation of what this does and why it solves the problem? (BTW, as may be obvious from my request, I know nothing about librespot.)

**Comment by OK9UWU** [comment]
Hello guys.
Suffering from the same issue as y'all do, tried to add the DNS records but to no avail, the error stands solid.
Using librespot on libreelec and armbian. :/

**Comment by codyrap95** [comment]
Having the same issue on raspotify for 2 days already. Yesterday I managed to get it working by setting apresolve.spotify.com to 0.0.0.0, but today nothing seems to be working anymore, not even setting the host for individual APs.

**Comment by kingosticks** [comment]
There's a pre-existing related issue at https://github.com/librespot-org/librespot/issues/972#issuecomment-2320943137. We need to close one of them. But I'll repeat it here, the workaround is dead already, you need to use the latest code from the dev branch where the issue is not present.

**Comment by bitclick** [comment]
> use the latest code from the dev branch where the issue is not present

i can confirm:
- compiled on my desktop follwing the guide in the documentation.
- built with `cargo build --release --no-default-features --features alsa-backend`    (i use the pipe-backend to snapcast)
- tested on desktop - worked immediately
- copied the binary to the soundserver (same architecture)  - works as drop-in for the old version `0.4.1`

**Comment by RSKriegs** [comment]
Adhering to all of the comments related to compiling the dev branch, I'll add that you can also set up Librespot as a service so it runs on startup:
https://github.com/librespot-org/librespot/wiki/Running-as-a-service
Works on Raspbian for me. I run it as an user service. If you compile this & point the compiled file in ExecStart parameter in librespot.service (or whatever you name it) file you should succeed. Basically everything is in Librespot's documentation :) Hope I've saved someone's time and that it will work consistently.

**Comment by MattGesicki** [comment]
> > use the latest code from the dev branch where the issue is not present
> 
> i can confirm:
> 
>     * compiled on my desktop following the guide in the documentation.
> 
>     * built with `cargo build --release --no-default-features --features alsa-backend`    (i use the pipe-backend to snapcast)
> 
>     * tested on desktop - worked immediately
> 
>     * copied the binary to another host (soundserver, same architecture)  - works as drop-in for the old version (`0.4.2` i think)

Hi bitclick,
Thank you for the solution, I experienced the same problem.
Could you please provide me and other 'mortals' a quick guide how to implement a fix?
Where I can find latest dev branch and documentation to follow?
Thanks in advance!

**Comment by RSKriegs** [comment]
@MattGesicki follow the steps just like here https://github.com/librespot-org/librespot/blob/dev/COMPILING.md
If you want to add it as a service so it boots on a startup do the following: https://github.com/librespot-org/librespot/wiki/Running-as-a-service

Note that compilation may take some time

**Comment by MattGesicki** [comment]
@RSKriegs thanks!
I learned a few things today which are obvious for you :) 
I've installed rust and C compiler, added ssh publickey, forked librespot and downloaded it.
One last thing before trying to compile - I'm not sure what audio backend I have. Do they mean a hardware device I use in RaspberryPi?

**Comment by RSKriegs** [comment]
@MattGesicki I didn't dive into that, I used the default one and it's ok.

**Comment by fnndyl** [comment]
Hm. I forked and pulled the dev branch (I hope!) and compiled on my Pi 3B+... still getting channel error same as before. Dang.

**Comment by fnndyl** [comment]
Compiling from dev does seem to have fixed the issue for me :)

**Comment by kosmo2k** [comment]
Compiled from the dev branch on a raspberry pi, worked for me. No issues so far :)

**Comment by lpicanco** [comment]
Having the same issue on moode. I will compile the dev branch and test with it.

```txt
[2024-09-03T22:13:50Z WARN  librespot_core::apresolve] Using fallback "ap.spotify.com:443"
[2024-09-03T22:13:50Z INFO  librespot_core::session] Connecting to AP "ap.spotify.com:443"
...
[2024-09-03T22:24:11Z ERROR librespot_core::channel] channel error: 2 0
[2024-09-03T22:24:11Z ERROR librespot_playback::player] Unable to load encrypted file: ChannelError
[2024-09-03T22:24:11Z WARN  librespot_playback::player] Skipping to next track, unable to load track <SpotifyId { id: 3014....., audio_type: Track }>: ()
[2024-09-03T22:24:11Z DEBUG librespot_connect::spirc] At track 10 of 11 <"spotify:playlist:37i9...."> update [true]
[2024-09-03T22:24:11Z TRACE librespot_connect::spirc] Sending status to server: [kPlayStatusPlay]
```

**Comment by Semmu** [comment]
im running spotifyd 0.3.5 and this issue started happening today for me too, basically my spotify client is completely broken now.

(gotta love it when spotify breaks our clients on their end...)

**Comment by User65k** [comment]
Can confirm,
1. dev branch is working
`cargo install --git https://github.com/librespot-org/librespot.git --branch dev --no-default-features --features alsa-backend`.  
2. `/etc/hosts` changes dont help

**Comment by thomasbuesser** [comment]
login is still not working here...

**Comment by d-a-v** [comment]
Hello, I propose [this fix](https://github.com/dtcooper/raspotify/compare/master...d-a-v:raspotify:raspifix)

You can compile them yourself (`make all`)

Or sillily trust me and download [one of these binaries](https://mega.nz/folder/uQdgjToa#sxXikq3gIRwiBY3LVZBRlw).

I had to make them this way (and not simply recompile upstream librespot branch dev) because my orange-pi-zero is not able to compile anything. It is now running the raspi version.

**Comment by LosTigeros** [comment]
Got it working again in moode player.
1. Create a release build from the `dev` branch following [this](https://github.com/librespot-org/librespot/blob/dev/COMPILING.md), and to build, use this command:
`cargo build --release --no-default-features --features alsa-backend`
2. Backup old & copy new built `librespot` to the `/usr/bin/`:
`sudo mv /usr/bin/librespot /usr/bin/librespot.old && sudo cp target/release/librespot /usr/bin/librespot`
3. Go to the moode renderers -> Spotify connect settings and make sure the `Autoplay` is set to `No`, otherwise `librespot` will just error and stop.
4. Disable the `ap-port` parameter, otherwise it won't be able to resolve all access points:
- `sudo nano /var/www/inc/renderer.php` - line 110
- Change `' --ap-port 13561 '` to empty `''`, or comment it out like this: `''; //' --ap-port 13561 '` so you can restore it once there is a proper fix
![image](https://github.com/user-attachments/assets/8c479cc8-ac85-4e1e-8c89-7f6006793009)
5. Reboot the device:
`sudo reboot`

If you made any changes to the `/etc/hosts` file like recommended above, please remove those entries before rebooting.

**Comment by arthurus** [comment]
Can anyone identify which commit from the dev branch fixes this? It might be possible to backport it to other versions. It's not possible for me to just start using dev now because I have a customized fork for an old MIPS router and the newer versions won't work there.

**Comment by dspearson** [comment]
> Can anyone identify which commit from the dev branch fixes this? It might be possible to backport it to other versions. It's not possible for me to just start using dev now because I have a customized fork for an old MIPS router and the newer versions won't work there.

I hit the issue too and confirm that it is fixed at the tip. I'll try and do a git bisect when I have some time (probably sometime in the next few days) to try and identify the change, since I could not see anything obvious in the commit logs or pull requests that is related. Or maybe one of the devs can chime in if they already know specifically.

**Comment by kingosticks** [comment]
0.4 (master) and 0.5 (dev) use entirely different methods to retrive the audio data. Spotify probably just disabled the old method used in 0.4, just as they disabled user+password auth. It's very different, it's not going to be a simple change to backport. Everyone will need to move to 0.5 (dev) and there will hopefully be a release of that soon, but a lack of release shouldn't be stopping anyone.

**Comment by whisperzer0** [comment]
Can confirm the steps outlined in:

https://github.com/librespot-org/librespot/issues/1322#issuecomment-2328160807

> dev branch is working (for Spotify connect)
cargo install --git https://github.com/librespot-org/librespot.git --branch dev --no-default-features --features alsa-backend

Works for me. - 5th Sept 2024

**Comment by dflvunoooooo** [comment]
> Can confirm the steps outlined in:
> 
> [#1322 (comment)](https://github.com/librespot-org/librespot/issues/1322#issuecomment-2328160807)
> 
> > cargo install --git https://github.com/librespot-org/librespot.git --branch dev --no-default-features --features alsa-backend
> 
> Works for me. - 5th Sept 2024

I can confirm this is working. Connection is slow though. And I get the error 
```
ContextError: Error { kind: InvalidArgument, error: StatusCode(400) }
```
But despite that it is working.

**Comment by ejurgensen** [comment]
Spotify seems to have rolled back the breaking change. Since they didn't announce the change, and since the old protocol only broke partially (just chunk requests?), maybe the change wasn't intentional in the first place.

**Comment by kingosticks** [comment]
My guess it's all related to https://github.com/librespot-org/librespot/discussions/1288

This is exactly what happened when they started deprecating libspotify. Seems they didn't learn much from that mess.

**Comment by roderickvd** [comment]
Probably. I suspect that when it was broken for us, it was broken on all official legacy devices out there.

Still, enough reason to start releasing 0.5.

**Comment by rwjack** [comment]
FYI I'm not getting these errors anymore, with or without the /etc/hosts change. Although I am still having troubles with 1340 ^

**Comment by kingosticks** [comment]
Are you able to reproduce this issue with the very latest (today's) code? If so, please provide full debug log showing it occurring.

**Comment by rwjack** [comment]
@kingosticks How can I test it out?

This is how I get 0.4.2: https://github.com/rwjack/addon-snapserver-spotify/blob/f887f5eba609024cb12993393fb0143241c71837/snapserver/Dockerfile#L18

**Comment by rwjack** [comment]
Anyone?? I'm getting this when trying to build the dev version:
```
921328c5d06b:/# /usr/bin/librespot          
bash: /usr/bin/librespot: cannot execute: required file not found
```

Built like:
```
# Stage 1: Build the Librespot binary
FROM rust:latest AS builder

# Set the working directory
WORKDIR /usr/src/librespot

# Clone the Librespot repository
RUN git clone https://github.com/librespot-org/librespot.git .

# Install necessary dependencies for building
RUN apt-get update && apt-get install -y \
    pkg-config \
    libasound2-dev \
    && rm -rf /var/lib/apt/lists/*

# Build the project
RUN cargo build --release

ARG BUILD_FROM
#FROM $BUILD_FROM
FROM ghcr.io/hassio-addons/base:16.2.1

# Add env
ENV LANG C.UTF-8

# Set shell
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN \
    apk add --no-cache \
        pulseaudio alsa-plugins-pulse bash \
    && rm -fr \
        /tmp/*

RUN apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community/ snapcast-server=0.29.0-r0

# Copy the built binary from the builder stage
COPY --from=builder /usr/src/librespot/target/release/librespot /usr/bin/librespot

#RUN apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/ librespot=0.4.2-r4

RUN \
    wget https://github.com/badaix/snapweb/releases/download/v0.8.0/snapweb.zip && \
    unzip -o snapweb.zip -d /usr/share/snapserver/snapweb/ && \
    rm snapweb.zip

# Copy data for add-on
COPY run.sh /
RUN chmod a+x /run.sh

CMD [ "/run.sh" ]

```
