### ISSUE TITLE
Version 5 dev (2ea7436) --initial-volume 0 results in full volume

### ISSUE THREAD

**Issue by moodeaudio** [librespot-org/librespot#1325]
**Describe the bug**
The option `--initial-volume 0` results in full (100%) volume when iPhone client connects and then starts playback. 

The volume slider on the client appears to get set differently depending on whether the client was already playing locally before librespot is started followed by client connecting.
1.  Already playing locally: Slider gets set  to 0 position after librespot starts and stays at 0 after connecting, output volume = full
2. Not playing locally: Slider gets set  to 0 position after librespot starts but then goes to almost 100% after connecting + play, output volume = full

In either case actual output volume is full volume (100%)

**To reproduce**
1. Launch `librespot` with
```
sudo librespot --name "Moode9 Spotify" --bitrate 320 --format S16 --mixer softvol --initial-volume 0 --volume-ctrl log --volume-range 60 --cache /var/local/www/spotify_cache --disable-audio-cache --backend alsa --device "_audioout" --onevent /var/local/www/commandw/spotevent.sh -v > /var/log/moode_librespot.log 2>&1
```

2. In Spotify iPhone App playback should be stopped
4. Connect to "Moode9 Spotify"
5. Observe App volume slider position
6. NOTE: Be sure downstream volume control is set very low!
7. Start playback
8. Observe App volume slider position and actual output volume

**Log**
Its ginormous so maybe a link is best :-)
[moode_librespot.log](https://moodeaudio.org/test/moode_librespot.log)

 **Host (what you are running `librespot` on):**
- OS: RaspiOS Bookworm
- Platform: Pi5

**Additional context**
- Audio device: Allo Boss DAC

**Comment by kingosticks** [comment]
And to be explicit, this is a regression compared to 0.4, yes?

Related to https://github.com/librespot-org/librespot/issues/41

**Comment by roderickvd** [comment]
Certainly possible because I rewrote the way it takes the volume from the initial handshake in 0.5.

This would be a good "first issue" for someone to jump and in contribute. The logic should not be difficult to find and fix.

**Comment by moodeaudio** [comment]
@kingosticks, yes it appears to be a regression compared to 0.4.

I should also mention that setting `--initial-volume` to a value greater than 0 seems to work fine.

**Comment by roderickvd** [comment]
Any takers before releasing 0.5 maybe this weekend?

**Comment by BeeJay28** [comment]
I'll take care of it in the spirit of hacktober if that's okay :)
