### ISSUE TITLE
Librespot 20.0.130 Kodi

### ISSUE THREAD

**Issue by bdgra** [librespot-org/librespot#1329]
Hi,

I'm still using Librespot 20.0.130 on a Kodi system. Reason is that from version 20.5 and later 21.1.1. Discovery mode isn't working anymore and it stops after the album has been finished. With 20.0.130 this all works fine. However the artwork of an album has been zoomed in and isn't clearly visible. Is there a way to solve this? I only have this with this addon. And already tried to change the system resolution. But unfortunately without any luck. 

Hope someone can help with this matter.

**Comment by kingosticks** [comment]
Those version numbers are meaningless here I'm afraid, we don't know anything at all about the Kodi plugin. You would need to get support from the plugin maintainer for a start. If they can't help with that (they should) then you need to return here with the version of the librespot library you're using and also a librespot debug log file.

**Comment by bdgra** [comment]
@kingosticks first of all thanks for your reply. This is what I could find regarding the version number. 

 [2024-09-08T08:09:03Z INFO  librespot] librespot 0.3.1 0989b9836a (Built on 2022-04-28, Build ID: ILkusV0o, Profile: release)

**Comment by kingosticks** [comment]
0.3 is very very old and not supported. Please request the kodi plugin maintainer updates to the latest version. Technically that's v0.4 but it'll very soon be v0.5

**Comment by michaelherger** [comment]
librespot doesn't handle artwork at all, does it? This has likely nothing to do with librespot, but is a Kodi integration/implementation issue.

**Comment by roderickvd** [comment]
dev provides some logic to get the URL, I think. But indeed, this is Kodi and an old version, so closing.
