### ISSUE TITLE
Support for Podcasts

### ISSUE THREAD

**Issue by funtax** [librespot-org/librespot#133]
Spotify's Podcasts do work in another way than normal tracks.
I haven't yet found a way to load the track, but maybe someone with better knowledge of the Spotify-Analyzer can provide some useful information to get this implemented.

**Comment by shanemeagher** [comment]
Have a look at issue #90 where it is already being discussed.

**Comment by sashahilton00** [comment]
There's already an issue for this, found here: https://github.com/librespot-org/librespot/issues/90
