### ISSUE TITLE
Cache size limit is ignored

### ISSUE THREAD

**Issue by rwjack** [librespot-org/librespot#1363]
**Describe the bug**

Cache is sitting at 5.5G and growing. I ran librespot through Snapcast with:

```
[stream]
stream = spotify:///librespot?name=Spotify&devicename=HA_Snapcast&bitrate=320&volume=100&cache=/data/librespot&cache-size-limit=2G&autoplay=true&params=--disable-discovery
```

![image](https://github.com/user-attachments/assets/d32b6d3c-2606-4bb8-aff0-32f33e299c5a)

**Host (what you are running `librespot` on):**
- OS: HAOS
- Platform: x86

Is anyone else having this issue, or could it be that the parameter is improperly parsed by Snapcast?

**Comment by kingosticks** [comment]
This isn't a librespot bug.

Snapcast doesn't understand that param. The params it understands are documented at https://github.com/badaix/snapcast/blob/develop/doc/configuration.md#available-parameters

You can pass arbitrary other params via 'params` but you'll have to ensure you urlencode them properly.
