### ISSUE TITLE
Documentation about OAuth2

### ISSUE THREAD

**Issue by ManiArasteh** [librespot-org/librespot#1372]
Now that new version released, it's good to add a documentation about how to implement OAuth2, I think.
Close this issue if it is implemented in existing functions/library (Don't close this issue without leaving a comment).

**Comment by kingosticks** [comment]
There's comprehensive Spotify OAuth documentation at https://developer.spotify.com/documentation/web-api/concepts/authorization as well as our documentation at https://github.com/librespot-org/librespot/wiki/Options#oauth and https://github.com/librespot-org/librespot/wiki/Options#access-token. You can [see for yourself ](https://github.com/librespot-org/librespot/blob/09e4c3e12b557519d94ca29e3850a7723cc98e78/oauth/Cargo.toml#L13) we use an existing "oauth2" library, it is well documented. 

I consider this issue closed but if you have a concrete documentation enhancement request then feel free to make it.

**Comment by ManiArasteh** [comment]
Thanks.

**Comment by ManiArasteh** [comment]
This is command-line arguments.
I mean code, not CLI

**Comment by kingosticks** [comment]
https://docs.rs/oauth2/latest/oauth2/
