### ISSUE TITLE
Cache path option not working

### ISSUE THREAD

**Issue by fjromerom** [librespot-org/librespot#1376]
### Description
Hi,

I'm using raspotify and I see the following warning in the logs.

```
WARN  librespot] Without a `--cache` / `-c` path, and/or if the `--disable-audio-cache` / `-G` fl
```

I have enabled the following options:

- LIBRESPOT_DISABLE_AUDIO_CACHE=off
- LIBRESPOT_CACHE_SIZE_LIMIT="1G"

Why does the service print out the warning? is the cache not working?

### Version
```
$ librespot -V
librespot 0.5.0 84d28e8 (Built on 2024-10-17, Build ID: NYHYOuGX, Profile: release)
```

### How to reproduce
Using raspotify provide the previous options.

### Log
Provided before.

### Host (what you are running `librespot` on):
Linux raspberrypi 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l

**Comment by kingosticks** [comment]
You've seemingly not enabled the cache and then also disabled the audio cache? That seems like an odd thing to try and do and worth warning about, no?

**Comment by roderickvd** [comment]
1. You're asking if the cache is not working -- well, is the cache not working? (do you see files in your cache dir?)
2. You believe this is a librespot issue or should it be reported to raspotify?

**Comment by kingosticks** [comment]
Provide the full log, as very clearly requested in the issue template.

**Comment by fjromerom** [comment]
Apologies for my late reply!

> Edit, sorry I misread , that warning does seem wrong but it's also an odd collection of options. If you want to use caching you need to actually turn it on, where did you do that ?

I have enabled the option `LIBRESPOT_CACHE_SIZE_LIMIT="1G"`. I haven't seen any other option to enable it, how do you typically enable cache? Or maybe it's something you do not care about.

> You're asking if the cache is not working -- well, is the cache not working? (do you see files in your cache dir?)
You believe this is a librespot issue or should it be reported to raspotify?

No, there are no files. I believe it's a librespot isssue since raspotify is passing the parameter to librespot.

How do you enable cache in librespot? So I can verify it's aligned with my config.

**Comment by kingosticks** [comment]
Options are fully documented at https://github.com/librespot-org/librespot/wiki/Options and when you run with `--help`.

So something like `LIBRESPOT_CACHE="/some/path/on/your/filesystem"`

**Comment by fjromerom** [comment]
Yes, I have defined CACHE options as follows:

```
$ grep CACHE /etc/raspotify/conf
# if you don't limit the cache size with LIBRESPOT_CACHE_SIZE_LIMIT.
LIBRESPOT_DISABLE_AUDIO_CACHE=off
LIBRESPOT_DISABLE_CREDENTIAL_CACHE=on
LIBRESPOT_CACHE_SIZE_LIMIT="1G"
LIBRESPOT_CACHE="/tmp/librespot"
```

**Comment by roderickvd** [comment]
To isolate the issue can you please run it with vanilla librespot, no raspotify or anything? Then report back with verbose log.

**Comment by kingosticks** [comment]
> Yes, I have defined CACHE options as follows:
> 
> ```
> $ grep CACHE /etc/raspotify/conf
> # if you don't limit the cache size with LIBRESPOT_CACHE_SIZE_LIMIT.
> LIBRESPOT_DISABLE_AUDIO_CACHE=off
> LIBRESPOT_DISABLE_CREDENTIAL_CACHE=on
> LIBRESPOT_CACHE_SIZE_LIMIT="1G"
> LIBRESPOT_CACHE="/tmp/librespot"
> ```

Ok, that wasn't in your first message... When you do retry with normal librespot as requested, please provide the full log.

**Comment by kingosticks** [comment]
It's in the big table. Some are flags and are either present or not. Others are options and take a value. The difference isn't explicit, that could be improved. If I remember correctly, if you do what you did on the command line it will error. Seems the env variable handling doesn't have the same abilities.
