### ISSUE TITLE
error: failed to run custom build command for `aws-lc-sys v0.22.0`

### ISSUE THREAD

**Issue by Cylac** [librespot-org/librespot#1380]
trying to install in Windows Powershell and I keep on getting this error:

` Compiling ppv-lite86 v0.2.20

error: failed to run custom build command for `aws-lc-sys v0.22.0`

Caused by:
  process didn't exit successfully: `C:\Users\Cylac\AppData\Local\Temp\cargo-installuwXhPO\release\build\aws-lc-sys-87ae87f17106e7d5\build-script-main` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_PREFIX
  cargo:rerun-if-env-changed=AWS_LC_SYS_PREGENERATING_BINDINGS
  cargo:rerun-if-env-changed=AWS_LC_SYS_EXTERNAL_BINDGEN
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_ASM
  cargo:rerun-if-env-changed=AWS_LC_SYS_CFLAGS
  cargo:rerun-if-env-changed=AWS_LC_SYS_PREBUILT_NASM
  cargo:rerun-if-env-changed=AWS_LC_SYS_C_STD
  cargo:rustc-cfg=x86_64_pc_windows_msvc
  cargo:rerun-if-env-changed=AWS_LC_SYS_CMAKE_BUILDER
  cargo:rerun-if-env-changed=AWS_LC_SYS_STATIC
  default_for Target: 'x86_64-pc-windows-msvc'
  cargo:rerun-if-env-changed=AWS_LC_SYS_STATIC
  cargo:rerun-if-env-changed=CMAKE

  --- stderr
  Missing dependency: cmake
  thread 'main' panicked at C:\Users\Cylac\.cargo\registry\src\index.crates.io-6f17d22bba15001f\aws-lc-sys-0.22.0\builder/main.rs:320:40:
  called `Result::unwrap()` on an `Err` value: "Required build dependency is missing. Halting build."
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `librespot v0.5.0`, intermediate artifacts can be found at `C:\Users\Cylac\AppData\Local\Temp\cargo-installuwXhPO`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.`

not too sure how to proceed around this.. rebooted, made sure I had rust installed.

Windows 10

**Comment by Luk4h** [comment]
Can confirm, on a clean Windows + Rust install, Librespot does not compile on `v0.5.0`.

For now run `cargo install librespot@0.4.2`.

**Comment by kingosticks** [comment]
You should be able to set env variable AWS_LC_SYS_PREBUILT_NASM=1 for x86 windows. See details/alternatives at https://aws.github.io/aws-lc-rs/requirements/windows

**Comment by fivebanger** [comment]
Please have a look at https://github.com/librespot-org/librespot/issues/1346#issuecomment-2397522950. You have to install NASM and CMake in addition to make it compile on Windows. 

I'm just wondering if the additional steps needed to be done in order to make librespot compile on Windows should be documented somehow here in the project? I know that those dependencies are not related directly to librespot but since librespot depends on a lib that makes those steps necessary, maybe a user would like to see an appropriate HowTo in librespot's Compiling Wiki or at least the link mentioned above?

**Comment by kingosticks** [comment]
I think so. Anyone can edit it so if you know what would be helpful to put, I say go for it.

**Comment by fivebanger** [comment]
I have updated the [Wiki](https://github.com/librespot-org/librespot/wiki/Compiling) accordingly.

**Comment by Cylac** [comment]
installing [NASM](https://nasm.us/) and [CMake](https://cmake.org/download/) prior to running "cargo build" has solved my issue (this was a fresh install)! 

I didn't get any errors this time around!

thanks everyone for the help!
