### ISSUE TITLE
librespot fails to build on FreeBSD after recent update to 0.6

### ISSUE THREAD

**Issue by driesmp** [librespot-org/librespot#1393]
https://pkg-status.freebsd.org/beefy22/data/141amd64-default/203aa1081a24/logs/librespot-0.6.0_1.log

**Comment by driesmp** [comment]
Hello, so apparently after updating the port to the newest edition, it doesn't quite build. Could you help troubleshoot?

**Comment by kingosticks** [comment]
There are existing (closed) issues relating to these sorts of build problems. Please check those don't solve your issue.

**Comment by kingosticks** [comment]
There are existing (closed) issues relating to these sorts of build problems. Please check those don't solve your issue.

**Comment by pstumpf** [comment]
#1382 is the issue that solves the problem for good.  Not closed yet.

**Comment by kingosticks** [comment]
Great point. You could wait for that, if you like.

Or solve it now by satisfying the current dependencies. It's also at  https://github.com/librespot-org/librespot/wiki/Compiling#linuxmacoswindows if your search the recent issues is somehow fruitless.

**Comment by thomasbuesser** [comment]
Any news from this? I was still unable to build the current release on FreeBSD...


Am 16. November 2024 um 23:49 schrieb "Roderick van Domburg" ***@***.*** ***@***.***?to=%22Roderick%20van%20Domburg%22%20%3Cnotifications%40github.com%3E >:

**Comment by kingosticks** [comment]
Can you clarify, are still unable to build even after fixing the build environment to satisfy the new dependencies?

**Comment by thomasbuesser** [comment]
tried the ports-version this morning and failed with the warning / error below on FreeBSD 13.4-RELEASE

Same error on building the git-checkout with "cargo build --release --no-default-features" 
As recomended in the librespot/COMPILING.md i installed the build-essentials, upgraded gcc to 13.3 

[code]
  --- stdout
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_PREFIX
  cargo:rerun-if-env-changed=AWS_LC_SYS_PREGENERATING_BINDINGS
  cargo:rerun-if-env-changed=AWS_LC_SYS_EXTERNAL_BINDGEN
  cargo:rerun-if-env-changed=AWS_LC_SYS_NO_ASM
  cargo:rerun-if-env-changed=AWS_LC_SYS_CFLAGS
  cargo:rerun-if-env-changed=AWS_LC_SYS_PREBUILT_NASM
  cargo:rerun-if-env-changed=AWS_LC_SYS_C_STD
  cargo:rerun-if-env-changed=AWS_LC_SYS_CMAKE_BUILDER
  cargo:rerun-if-env-changed=AWS_LC_SYS_STATIC
  cargo:rerun-if-env-changed=CMAKE
  cargo:warning=Building with: CMake
  cargo:warning=Symbol Prefix: Some("aws_lc_0_22_0")
  cargo:rerun-if-env-changed=CMAKE
  cargo:warning=CMAKE environment variable set: cmake
  cargo:warning=Generating bindings - external bindgen. Platform: x86_64-unknown-freebsd

  --- stderr
  Consider installing the bindgen-cli: `cargo install --force --locked bindgen-cli`
  See our User Guide for more information about bindgen:https://aws.github.io/aws-lc-rs/index.html
  Failure invoking external bindgen! External bindgen command failed.
  thread 'main' panicked at /usr/ports/multimedia/librespot/work/librespot-0.6.0/cargo-crates/aws-lc-sys-0.22.0/builder/main.rs:566:5:
  aws-lc-sys build failed. Please enable the 'bindgen' feature on aws-lc-rs or aws-lc-sys.For more information, see the aws-lc-rs User Guide: https://aws.github.io/aws-lc-rs/index.html
  stack backtrace:
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
*** Error code 101

[/code]


Am 21. November 2024 um 11:51 schrieb "Nick Steel" ***@***.*** ***@***.***?to=%22Nick%20Steel%22%20%3Cnotifications%40github.com%3E >:

**Comment by kingosticks** [comment]
> The usage of [aws-lc-sys](https://crates.io/crates/aws-lc-sys) as a dependency may require additional steps in order to compile for different target systems. Further [reading](https://aws.github.io/aws-lc-rs/requirements/index.html) is recommended,

**Comment by driesmp** [comment]
Should be fixed https://cgit.freebsd.org/ports/commit/?id=1d85a07a2cf7c35c7a43eb8a96d526adadf9a192
