### ISSUE TITLE
Support discovery on Windows

### ISSUE THREAD

**Issue by michaelherger** [librespot-org/librespot#140]
Neither mdns nor dns-sd currently compile on Windows. Both seem to have some expectations which are rather unixy. There's been a pull request which tried to bring mdns to Windows:

https://github.com/plietar/rust-mdns/pull/11/files

Unfortunately it mixes in other Linux related changes which makes things break on the latter for me. Maybe somebody could pick up some pieces anyway?...

**Comment by sashahilton00** [comment]
mdns support all good, so windows is technically supported now albeit without any backends other than pipe iirc. Once cpal support is added, there should be a fully featured cross compiled windows version available. Closing this as #145 tracks remaining functionality that should be added.
