### ISSUE TITLE
Dockerfile: Install necessary dependencies for pulseaudio

### ISSUE THREAD

**Issue by floli** [librespot-org/librespot#142]
Currrently, the crosscompile setup at https://github.com/librespot-org/librespot/wiki/Cross-compiling gives instruction how to compile for the portaudio backend and I have no intentions to change the default.
However, it would be nice to also add the dependencies needed to build for pulseaudio, e.g. so  that
```docker run -v /tmp/librespot-build:/build librespot-cross cargo build --release --target arm-unknown-linux-gnueabihf --no-default-features --features pulseaudio-backend``` works. Currently there is libraries not found ```-lpulse -lpulse-simple``` at linking.

**Comment by awiouy** [comment]
You need  `libpulse-dev`
Add it after https://github.com/librespot-org/librespot/blob/master/contrib/Dockerfile#L25

**Comment by sashahilton00** [comment]
We just need to add this to the Dockerfile dependencies to compile right? If so, create a PR and will test/merge to make sure it doesn't drastically increase docker image build time, then merge.

**Comment by floli** [comment]
Adding this line
```
RUN apt-get install -y libpulse-dev libpulse-dev:arm64 libpulse-dev:armel libpulse-dev:armhf libpulse-dev:mipsel
```
gives me 
```
The following packages have unmet dependencies:
 libpulse-dev:arm64 : Depends: libglib2.0-dev:arm64 but it is not going to be installed
 libpulse-dev:armhf : Depends: libglib2.0-dev:armhf but it is not going to be installed
 libpulse-dev:armel : Depends: libglib2.0-dev:armel but it is not going to be installed
 libpulse-dev:mipsel : Depends: libglib2.0-dev:mipsel but it is not going to be installed
```
when I add the same line for ```libglib2.0-dev```, I get conflicts
```
The following packages have unmet dependencies:
 libglib2.0-dev : Conflicts: libglib2.0-dev:arm64 but 2.50.3-2 is to be installed
                  Conflicts: libglib2.0-dev:armhf but 2.50.3-2 is to be installed
                  Conflicts: libglib2.0-dev:armel but 2.50.3-2 is to be installed
                  Conflicts: libglib2.0-dev:mipsel but 2.50.3-2 is to be installed
 libglib2.0-dev:arm64 : Conflicts: libglib2.0-dev but 2.50.3-2 is to be installed
                        Conflicts: libglib2.0-dev:armhf but 2.50.3-2 is to be installed
                        Conflicts: libglib2.0-dev:armel but 2.50.3-2 is to be installed
                        Conflicts: libglib2.0-dev:mipsel but 2.50.3-2 is to be installed
```
but honestly, I do just some cargo cult changes here, no idea what I am actually doing.

**Comment by plietar** [comment]
Unfortunately not all debian packages support side by side installation of multiple architecures. Seems like that's the case here.

**Comment by sashahilton00** [comment]
You might be able to use a Docker ARG to enable the passing of a ```--build-arg arch=arm64``` for example the conditionally install dependencies depending on which architecture you want to build...

**Comment by awiouy** [comment]
`libpulse-dev` installs with `debian-sid`:
```
--- a/contrib/Dockerfile
+++ b/contrib/Dockerfile
@@ -13,7 +13,7 @@
 # $ docker run -v /tmp/librespot-build:/build librespot-cross cargo build --release --target arm-unknown-linux-gnueabi --no-default-features --features "alsa-backend"
 #
 
-FROM debian:stretch
+FROM debian:sid
 
 RUN dpkg --add-architecture arm64
 RUN dpkg --add-architecture armhf
@@ -23,6 +23,7 @@ RUN apt-get update
 
 RUN apt-get install -y curl git build-essential crossbuild-essential-arm64 crossbuild-essential-armel crossbuild-essential-armhf crossbuild-essential-mipsel
 RUN apt-get install -y libasound2-dev libasound2-dev:arm64 libasound2-dev:armel libasound2-dev:armhf libasound2-dev:mipsel
+RUN apt-get install -y libpulse-dev libpulse-dev:arm64 libpulse-dev:armel libpulse-dev:armhf libpulse-dev:mipsel
 
 RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
 ENV PATH="/root/.cargo/bin/:${PATH}"
```

**Comment by floli** [comment]
I can confirm that it build and runs just fine with your patch. I just build the armhf version for my Raspi 3 running with Raspian.

**Comment by sashahilton00** [comment]
Why don't we just implement the updates to the dockerfile as @awiouy mentions above? Given that this is a build image, I don't see many problems with running unstable debian when building for cross compilation.

**Comment by plietar** [comment]
What's wrong with switching the build image to unstable? Debian's notion of unstable is definitely good enough for us

**Comment by awiouy** [comment]
Workaround indicates that the problem will likely be solved by a stretch upgrade or a buster release. In other words the issue will solve itself.
Building on sid might break or break system dependencies of the compiled code.

**Comment by plietar** [comment]
I doubt this is the sort of thing that gets backported, and a buster release is at least a year or two away.
Does this work on current buster?

**Comment by unimatrix27** [comment]
I have tried to apply this patch to cross compile for Raspberry Pi but there I still get missing -lpulse - I tried to add libpulse-dev_11.1-5+b1_armhf.deb as an additional dependency from Raspbian into the build script for PI, but that did not help. I also tried the other version that I found on raspbian.Mirror.

Any ideas?

**Comment by mfeif** [comment]
The patch works; the compile works, but it's compiled against glibc 2.27, which is not available on my distro (current version of "DietPi") which is at 2.24 
:-(
