### ISSUE TITLE
Librespot does not play when sent to null device, skips tracks repeatedly

### ISSUE THREAD

**Issue by SmatMan** [librespot-org/librespot#1429]
### Description
I am trying to run Librespot in a docker container to output audio to a null ALSA device. I have the device setup fine (as far as I can tell) and audio should be outputting there fine. When I connect to my device from spotify on another device, however, the songs each play for 1 second, then they skip to the next. While this is happening, gibberish is being outputted into my terminal for the duration of the playback, like below:

```
▒␋⎼␉┤␍⎽-┌␋┼┐-⎼⎻␋-⎽⎻⎺├␋°≤-1  ≠ ��        ��      ��  ��  ��   ���  �����������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������...
```
I am using the `alsa` backend, outputting to device "null".

My asound.conf:
```
pcm.!default {
    type plug
    slave.pcm "null"
}

pcm.null {
    type null
}

ctl.!default {
    type null
}
```

Audio devices from inside the container:

```
/$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Dummy [Dummy], device 0: Dummy PCM [Dummy PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
```

My goal here is to run librespot in a docker container such that it acts as a working Spotify connect client, however it functions without a real sound device. Any input or advice would be greatly appreciated :)

### Version
v0.60.0-dev
v0.50.0 (however on this version no gibberish was outputted, skip issue still occured)

### How to reproduce
Launching librespot using the following command:
```/usr/bin/librespot -v --name "Headless" --backend alsa --device null --bitrate 320 --disable-audio-cache --enable-volume-normalisation --verbose```

### Log
Logs are pure gibberish as per above.

Before playback:
```
[2024-12-21T03:44:18Z INFO  librespot] librespot 0.6.0-dev d82d94b (Built on 2024-12-21, Build ID: H8NVuDzy, Profile: release)
[2024-12-21T03:44:18Z INFO  librespot_playback::mixer::softmixer] Mixing with softvol and volume control: Log(60.0)
[2024-12-21T03:44:18Z INFO  librespot_playback::convert] Converting with ditherer: tpdf
[2024-12-21T03:44:18Z INFO  librespot_playback::audio_backend::pipe] Using StdoutSink (pipe) with format: S16
```

### Host (what you are running `librespot` on):
- OS: Debian 12
- Platform: Docker on Linux PC

**Comment by kingosticks** [comment]
The "gibberish" is the audio data being output on stdout (I.e. pipe backend), you can see that in the log. Did you compile with the alsa backend feature?

Librespot outputs audio as fast as the backend will take it, it relies on the consuming backend for pacing. In the case of output to stdout console, there's no back pressure so dumps it there as fast as it's downloaded and the track finishes as soon as that's done. Won't your null alsa device have a similar issue? What rate do you expect these tracks to 'play' at? Ok the face of it, this appears a weird thing to do...

**Comment by kingosticks** [comment]
Also, your aplay output shows no device called null. Use librespot `--device ?` argument to see what's available and see https://github.com/librespot-org/librespot/wiki/Audio-Backends#alsa

**Comment by SmatMan** [comment]
> The "gibberish" is the audio data being output on stdout (I.e. pipe backend), you can see that in the log. 

> Librespot outputs audio as fast as the backend will take it, it relies on the consuming backend for pacing. In the case of output to stdout console, there's no back pressure so dumps it there as fast as it's downloaded and the track finishes as soon as that's done.

Ahhh that explains a lot. That's pretty interesting how that works! I guess I expected 'pacing' to be controlled by the casting app.

> Did you compile with the alsa backend feature?

Yes. I'm not sure why but librespot was always being started with pipe instead of ALSA; I think the startup script I was using (rather, copied from another source) was messed up in some way. I rewrote it myself exactly to my specifications based on the Audio-Backends wiki page you linked and it seems to be working amazing now. Thank you :)

If you were wondering, my use case for this is to sync Plexamp playback with Spotify to integrate Plexamp with some integrations that only support Spotify. Very niche, I know, but a lot of fun. Thank you so much for your help.

**Comment by kingosticks** [comment]
Great to hear It's working now and interesting use case!
