### ISSUE TITLE
Add cpal Sink to librespot

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#145]
Currently, discussion to get Windows support is under way. Hopefully rust-mdns will be updated to work with Windows soon (#140), at which point, to ease running on Windows (and other systems), it would be good to implement a https://github.com/tomaka/cpal Sink for playback, which will remove the dependency on portaudio/pulseaudio, somewhat reducing the inconvenience of (cross) compiling for Windows.

**Comment by awiouy** [comment]
I have come across these today:
- http://libsound.io/
- https://github.com/klingtnet/rsoundio
What do you think?

**Comment by sashahilton00** [comment]
It looks to do a similar job to cpal, except that it's implemented by another library which has rust bindings, whilst cpal is pure rust. Is there a benefit to using libsound over cpal?

**Comment by mfeif** [comment]
One benefit is keeping Pulseaudio, which is the de-facto sound stack on all modern linux (I think).

**Comment by willstott101** [comment]
Since #277 got merged I guess this can be closed now?

Taking this opportunity to mention that the README is now out of date.

**Comment by sashahilton00** [comment]
Yup. Updated the readme. Closing.
