### ISSUE TITLE
Gapless playback

### ISSUE THREAD

**Issue by cortegedusage** [librespot-org/librespot#16]
With all the new progress on the Librespot front, I'd thought i'd point this out once again.
It would still be nice to have gapless playback available.
I know it has been requiested before
https://github.com/plietar/librespot/issues/18

But was there ever any progress on this?

Cheers, and happy listening!

**Comment by sashahilton00** [comment]
No progress on it afaik, unless Paul implemented it in the v0.2 branch. I agree it would be nice to have. In the meantime, I think we should track the preload/gapless requests as one issue, here: #21. Closing this in the meantime as a dupe.
