### ISSUE TITLE
LibreSpot 8.2.108 not (auto)starting properly

### ISSUE THREAD

**Issue by JHBonarius** [librespot-org/librespot#169]
After installing out-of-the-box LibreSpot 8.2.108 (from the default repo) on out-of-the-box LibreElec 8.2.3 (Kodi Krypton 17.8), everything worked fine. After a reboot the device is not discoverable. By using the Kodi GUI My Addons -> Services -> LibreSpot en selecting "update", the service seems to be started again (even though I 'updated' to the same version). I have to repeat this every (re)boot.
Same occurs after playing another source: LibreSpot cannot be discovered until "updated".

I don't know how to debug this, so please let me know how I can support.

**Comment by awiouy** [comment]
Discuss the Librespot addon for LibreELEC at the LibreELEC forum
This issue is addressed [here](https://forum.libreelec.tv/thread/8438-librespot-addon/?postID=82812#post82812)
