### ISSUE TITLE
Crosscompiling with PortAudio fails

### ISSUE THREAD

**Issue by TheBigFatTony** [librespot-org/librespot#174]
I want to compile librespot-org from my Fedora 27 to my Raspberry Pi Model B Rev 2 with the PortAudio backend using this command:
`docker run -v /tmp/librespot-build:/build:Z librespot-cross cargo build --release --target arm-unknown-linux-gnueabi --no-default-features --features portaudio-backend`
But it fails with this error:
```
error: failed to run custom build command for `portaudio-sys v0.1.1`
process didn't exit successfully: `/build/release/build/portaudio-sys-ec384f39d055f1f8/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Cross compilation detected. Use PKG_CONFIG_ALLOW_CROSS=1 to override', /build/cache/registry/src/github.com-1ecc6299db9ec823/portaudio-sys-0.1.1/build.rs:8:19
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
Full output: https://pastebin.com/Y3C5GQ3c

How can I set PKG_CONFIG_ALLOW_CROSS to 1?

Can anyone help me fix this?
(If I set `--features` to `alsa-backend`, it compiles and runs on the Raspberry Pi, although there is no sound just weird beeps. Full output: https://pastebin.com/ezi5B76e)

**Comment by sashahilton00** [comment]
Run the docker command like this: 
```
docker run -v /tmp/librespot-build:/build:Z librespot-cross PKG_CONFIG_ALLOW_CROSS=1 cargo build --release --target arm-unknown-linux-gnueabi --no-default-features --features portaudio-backend
```
