### ISSUE TITLE
Porting `tokio-core` to `tokio`

### ISSUE THREAD

**Issue by dbischof90** [librespot-org/librespot#178]
As `tokio-core` is depreceated and both the `futures` and the `tokio` crate are getting overhauled for version 0.2, there will be a necessity in the medium term to port the code to `tokio`.

This is not pressing but will be more important at one point.

**Comment by brain0** [comment]
It seems that the tokio API is not quite stable yet. It's probably best to wait until futures 0.2 is stable and a tokio version compatible to futures 0.2 is stable as well. Some things have changed drastically and this is likely a bigger task.

**Comment by ashthespy** [comment]
@marcelbuesing @leshow 
Moved here for the discussion. I've opened up a new [project](https://github.com/librespot-org/librespot/projects/2) to track this, while we figure out the best way to tackle this?

My .2 cents - Core is turning out to be quite a nightmare, if we get core/mercury up and running, then it should be easier to start isolating the rest and writing simple test wrappers for them.. 
What do you all think?

**Comment by brain0** [comment]
The problem I see is that nobody really has the full overview of the librespot project (I personally have only touched a few areas). I would even prefer writing it (the library) in an executor-agnostic way, if that is even possible.

In any case, librespot should use std's futures and much of it could probably be rewritten using async.

**Comment by ashthespy** [comment]
>The problem I see is that nobody really has the full overview of the librespot project (I personally have only touched a few areas). I would even prefer writing it (the library) in an executor-agnostic way, if that is even possible.

Pretty much in the same boat, but figuring out more as I refactor :-) We're quite deeply intertwined already with Tokio (as we use `hyper` and `libmdns`) so rewriting for use with `async-std` or `smol` is going to be hard (at this stage)

**Comment by sashahilton00** [comment]
No longer relevant - PR in progess. #606

**Comment by Siilwyn** [comment]
For anybody trying this out I've found using `smol` & `async_compat` to work with librespot. :)

```rust
use async_compat::Compat;
use librespot_core::authentication;
use librespot_core::config;
use librespot_core::session;

fn main() {
    let credentials = authentication::Credentials::with_password(
        env::var("SPOTIFY_USERNAME").expect("Environment variable SPOTIFY_USERNAME not set"),
        env::var("SPOTIFY_PASSWORD").expect("Environment variable SPOTIFY_PASSWORD not set"),
    );

    smol::block_on(Compat::new(async {
        let user_session =
            session::Session::connect(config::SessionConfig::default(), credentials, None)
                .await
                .unwrap();
        println!("Connected as {}", user_session.username());
    }));
}
```
