### ISSUE TITLE
How would I move my fork from plietar/librespot to librespot-org/librespot?

### ISSUE THREAD

**Issue by michaelherger** [librespot-org/librespot#18]
I have a fork of plietar/librespot which I've modified. Now I'd like to base it off librespot-org/librespot. Anybody knows how I would do this? I would like to be able to post pull requests here (if there ever was one :-))

**Comment by alin23** [comment]
You can make another fork and cherry-pick your commits to the new fork ¯\_(ツ)_/¯

**Comment by ComlOnline** [comment]
There's no easy way to do this as there could be conflicts etc. After you have forked a new repo from librespot-org you could create pull requests into it and do it that way. (Hey @alin23, you dropped this ;) \\ )

**Comment by sashahilton00** [comment]
@michaelherger like @ComlOnline there's no easy way. I just had a look at a few of your branches, it looks like you created a few. If you explain a little about which ones you added and what they do, I'd be happy to start copy-pasting stuff if you want a hand migrating.

**Comment by michaelherger** [comment]
I don't think there's much of general interest in my branches as of today (there was one which got merged a while back). They mostly deal with my Spotty plugin for [Logitech Media Server (LMS)](https://github.com/Logitech/slimserver). I needed a way to talk from librespot/spotty to LMS. At least two branches deal with my more or less successful attempts for this feature. Another one (refactor-0817) tries to bring my changes up to speed with the re-factoring started by @plietar back in August of last year (and now continued here). I'll probably just live with the current situation until that latest branch is ready to be merged into my spotty branch. Then I'll create a new fork and try to push that fork only. Thanks for all your input!

**Comment by michaelherger** [comment]
FWIW: I can submit pull requests even from my existing, old fork, without forking librespot-org/librespot again. I merged changes from the latter on top of my existing master, pushed to my origin. From where I was able to submit this pull request https://github.com/librespot-org/librespot/pull/111
