### ISSUE TITLE
Getting "Could not write audio: Invalid argument" although other audio sources work

### ISSUE THREAD

**Issue by MarcelKr** [librespot-org/librespot#180]
When starting playback, I get the error ``Could not write audio: Invalid argument``. Other audio sources such as mopidy or kodi do work. I use pulseaudio as backend. Below is what I get calling librespot (See [this file](https://github.com/librespot-org/librespot/files/1777414/output-v.txt) for the output with -v option)

```
[marcel@NAS ~]$ librespot --name nas
INFO:librespot: librespot 8e0d758 (2018-02-26). Built on 2018-02-26. Build ID: BFjJS6fG
INFO:librespot_core::session: Connecting to AP "gew1-accesspoint-b-kd8g.ap.spotify.com:4070"
INFO:librespot_core::session: Authenticated as "xxxx" !
INFO:librespot_core::session: Country: "DE"
INFO:librespot_playback::player: Loading track "The Underworld"
INFO:librespot_playback::player: Track "The Underworld" loaded
ERROR:librespot_playback::player: Could not write audio: Invalid argument
```

SW versions in use:
  * linux kernel 4.15.6
  * pulseaudio 11.1
  * rust 1.24

It's probably me being too stupid to get it running. Any help would be appreciated.

**Comment by awiouy** [comment]
Try disabling option "keep audio sink alive" in Kodi.

**Comment by MarcelKr** [comment]
I didn't hear any audio output before since I wasn't in the ``audio`` group, arghs. I noticed this by doing ``pacmd list-sinks``, which only showed a dummy output.
So this is a duplicate of #158 now. I have the exact same symptoms.
