### ISSUE TITLE
librespot hangs on compilation

### ISSUE THREAD

**Issue by Wqrld** [librespot-org/librespot#200]
```
pi@raspberry:~/spotifix/librespot $ sudo cargo build --release
    Updating registry `https://github.com/rust-lang/crates.io-index`
```

it doesnt seem to continiue after that, are there precompiled binaries available for me to use?
edit: raspberry pi 
edit: eyy issue 200

**Comment by ashthespy** [comment]
It takes quite a while to build on the pi*, especially the first build. I'd suggest using the docker images to cross compile instead.

*I have managed on the pi3, takes about 30+mins.

**Comment by Wqrld** [comment]
i have gotten this to work by using raspotify

**Comment by ComlOnline** [comment]
It could be related to the re connection issue. If librespot is disconnected from the internet it will crash.

**Comment by Wqrld** [comment]
for the other people this was an issue with portaudio so i will try to rework that while adding my new soundcard

(with no frkin tutorial on how to set it up in software)
