### ISSUE TITLE
Trying to get the example working

### ISSUE THREAD

**Issue by kbrah** [librespot-org/librespot#201]
I'm new to rust and this library and I'm trying to get the example working but facing following error:
```
error[E0599]: no method named `load` found for type `(librespot::<unnamed>::player::Player, futures::sync::mpsc::UnboundedReceiver<librespot::<unnamed>::player::PlayerEvent>)` 
in the current scope
  --> src/main.rs:43:21
   |
43 |     core.run(player.load(track, true, 0)).unwrap();
```

What am I doing wrong?

**Comment by michaelherger** [comment]
How do you call it?

**Comment by kbrah** [comment]
It also seems that the build in librespot with command `cargo build --example play` fails with the same error.

**Comment by kbrah** [comment]
figured out the reason of the error: creating new player should be `let (player, _) = ...` instead of `let player = ...`

This should be updated in the example i guess.

**Comment by michaelherger** [comment]
Good find! Please submit a pull request. Thanks!
