### ISSUE TITLE
Crashes when connecting from the Spotify client

### ISSUE THREAD

**Issue by alesny** [librespot-org/librespot#204]
librespot version: 03de235 (2018-04-12)
Each connect from the official Spotify client ends with the following crash: 

Apr 21 11:01:03 music librespot[606]: INFO:librespot_playback::audio_backend::alsa: Using alsa sink
Apr 21 11:01:06 music librespot[606]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SpotifyIdError', libcore/result.rs:945:5
Apr 21 11:01:06 music librespot[606]: stack backtrace:
Apr 21 11:01:06 music librespot[606]:    0:   0x99105b - <unknown>
Apr 21 11:01:06 music librespot[606]:    1:   0x98adb7 - <unknown>
Apr 21 11:01:06 music librespot[606]:    2:   0x98facb - <unknown>
Apr 21 11:01:06 music librespot[606]:    3:   0x98f6af - <unknown>
Apr 21 11:01:06 music librespot[606]:    4:   0x98ff6f - <unknown>
Apr 21 11:01:06 music librespot[606]:    5:   0x98fdd3 - <unknown>
Apr 21 11:01:06 music librespot[606]:    6:   0x98fd57 - <unknown>
Apr 21 11:01:06 music librespot[606]:    7:   0x98fcef - <unknown>
Apr 21 11:01:06 music librespot[606]:    8:   0x9ddb7f - <unknown>
Apr 21 11:01:06 music librespot[606]:    9:   0x50dcaf - <unknown>
Apr 21 11:01:06 music librespot[606]:   10:   0x4f2333 - <unknown>
Apr 21 11:01:06 music librespot[606]:   11:   0x4f0d23 - <unknown>
Apr 21 11:01:06 music librespot[606]:   12:   0x4d447b - <unknown>
Apr 21 11:01:06 music librespot[606]:   13:   0x4cdbf7 - <unknown>
Apr 21 11:01:06 music librespot[606]:   14:   0x4c4c0b - <unknown>
Apr 21 11:01:06 music librespot[606]:   15:   0x4cdf63 - <unknown>
Apr 21 11:01:06 music librespot[606]:   16:   0x4b8bc3 - <unknown>
Apr 21 11:01:06 music librespot[606]:   17:   0x4bb2e7 - <unknown>
Apr 21 11:01:06 music librespot[606]:   18:   0x4b8603 - <unknown>
Apr 21 11:01:06 music librespot[606]:   19:   0x4b886f - <unknown>
Apr 21 11:01:06 music librespot[606]:   20:   0x4b663f - <unknown>
Apr 21 11:01:06 music librespot[606]:   21:   0x4b2143 - <unknown>
Apr 21 11:01:06 music librespot[606]:   22:   0x4d622b - <unknown>
Apr 21 11:01:06 music librespot[606]:   23:   0x4c37fb - <unknown>
Apr 21 11:01:06 music librespot[606]:   24:   0x98fc27 - <unknown>
Apr 21 11:01:06 music librespot[606]:   25:   0x99f39b - <unknown>
Apr 21 11:01:06 music librespot[606]:   26:   0x990397 - <unknown>
Apr 21 11:01:06 music librespot[606]:   27:   0x4d6e13 - main
Apr 21 11:01:06 music librespot[606]:   28: 0xb6d08677 - __libc_start_main
Apr 21 11:01:06 music systemd[1]: raspotify.service: Main process exited, code=exited, status=101/n/a
Apr 21 11:01:06 music systemd[1]: raspotify.service: Unit entered failed state.
Apr 21 11:01:06 music systemd[1]: raspotify.service: Failed with result 'exit-code'.
Apr 21 11:01:16 music systemd[1]: raspotify.service: Service hold-off time over, scheduling restart.
Apr 21 11:01:16 music systemd[1]: Stopped Raspotify.
Apr 21 11:01:16 music systemd[1]: Starting Raspotify...
Apr 21 11:01:16 music systemd[1]: Started Raspotify.
Apr 21 11:01:17 music librespot[623]: INFO:librespot: librespot (raspotify) 03de235 (2018-04-12). Built on 2018-04-20. Build ID: j42hUaKh

**Comment by sashahilton00** [comment]
Unfortunately there isn't much we can do about this as the raspotify binary is stripped, thus we can't see what's causing the error. @dtcooper is there any chance you could avoid stripping raspotify binaries, or is it an operational requirement?

**Comment by l3d00m** [comment]
You may not have seen it @sashahilton00, but he disabled it in his recent build: https://github.com/dtcooper/raspotify/commit/0fa44d052692681d767af983025aa765d30ecffc

So this shouldn't be an issue here anymore in the future

**Comment by ashwinvandijk** [comment]
I got the same error, did a fresh pull from git with a fresh build.

`INFO:librespot_core::session: Country: "NL"
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
stack backtrace:
   0:     0x562e3d6a4553 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h09c1ee131a74b1c4
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x562e3d69e644 - std::sys_common::backtrace::_print::h47a337b62b6d5e9e
                               at libstd/sys_common/backtrace.rs:71
   2:     0x562e3d6a303d - std::panicking::default_hook::{{closure}}::h945a649c9017832e
                               at libstd/sys_common/backtrace.rs:59
                               at libstd/panicking.rs:380
   3:     0x562e3d6a2d42 - std::panicking::default_hook::hcc534c2d30fbcda3
                               at libstd/panicking.rs:396
   4:     0x562e3d6a34b0 - std::panicking::rust_panic_with_hook::h09a7a3a353dc2f38
                               at libstd/panicking.rs:576
   5:     0x562e3d6a336e - std::panicking::begin_panic::h8327f16bde15df70
                               at libstd/panicking.rs:537
   6:     0x562e3d6a3269 - std::panicking::begin_panic_fmt::h42ff1d37404632d6
                               at libstd/panicking.rs:521
   7:     0x562e3d6a31f2 - rust_begin_unwind
                               at libstd/panicking.rs:497
   8:     0x562e3d6ed360 - core::panicking::panic_fmt::h0bd854df201d1baf
                               at libcore/panicking.rs:71
   9:     0x562e3d27c9f8 - core::result::unwrap_failed::h5a09cf05b18a98d3
  10:     0x562e3d29f095 - <librespot_playback::audio_backend::pipe::StdoutSink as librespot_playback::audio_backend::Open>::open::h9bfda9875bf4b9fa
  11:     0x562e3d29014e - librespot_playback::audio_backend::mk_sink::h824474c1db1d88e0
  12:     0x562e3d2024a3 - std::sys_common::backtrace::__rust_begin_short_backtrace::heb3aa9b6b596e9b9
  13:     0x562e3d1f6d08 - std::panicking::try::do_call::he087878015e93967
  14:     0x562e3d6b203e - __rust_maybe_catch_panic
                               at libpanic_unwind/lib.rs:102
  15:     0x562e3d1f972d - <F as alloc::boxed::FnBox<A>>::call_box::h7fbc5ef2078e0c1b
  16:     0x562e3d6a9efb - std::sys::unix::thread::Thread::new::thread_start::h711c51a13a158afa
                               at /checkout/src/liballoc/boxed.rs:798
                               at libstd/sys_common/thread.rs:24
                               at libstd/sys/unix/thread.rs:90
  17:     0x7f87536127fb - start_thread
  18:     0x7f875333fb5e - clone
  19:                0x0 - <unknown>`

**Comment by User65k** [comment]
Hi, I also get an error when I connect a spotify client to a fresh build (using `cargo build --release --features "alsa-backend"`)

`librespot -n test --backend pipe`
`librespot -n test --backend alsa`

ALSA and Pipe backend each end up with:
```
INFO:librespot: librespot 21f1ccf (2018-05-15). Built on 2018-05-15. Build ID: OCGItlJk
INFO:librespot_core::session: Connecting to AP "gew1-accesspoint-b-2zkp.ap.spotify.com:4070"
INFO:librespot_core::session: Authenticated as "xxxxx" !
INFO:librespot_playback::audio_backend::alsa: Using alsa sink
INFO:librespot_core::session: Country: "DE"
INFO:librespot_playback::player: Loading track "A Question Of Time" with Spotify URI "spotify:track:5IT87UZK81t6dQ9gKU9TiX"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: WireError(InvalidEnumValue(14))', libcore/result.rs:916:5
stack backtrace:
   0:     0x563c10924a1b - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h79684051ac41db78
   1:     0x563c1092eb7e - std::sys_common::backtrace::print::h9921892c7d251199
   2:     0x563c1091de70 - std::panicking::default_hook::{{closure}}::hb1ef6f271daa5072
   3:     0x563c1091d9a6 - std::panicking::default_hook::h2b67894d489b9efc
   4:     0x563c1091e2bb - std::panicking::rust_panic_with_hook::h41c9d3408267e857
   5:     0x563c1091e10e - std::panicking::begin_panic::h831f3212b8c92f84
   6:     0x563c1091e07a - std::panicking::begin_panic_fmt::h6b11c1b1e86a67d8
   7:     0x563c1091e012 - rust_begin_unwind
   8:     0x563c1094e670 - core::panicking::panic_fmt::h53107fe7defdc8ff
   9:     0x563c104ff6c8 - core::result::unwrap_failed::he53022e081cf9148
  10:     0x563c104da7b8 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &'a mut F>::call_once::h7867533c1350634a
  11:     0x563c10500a53 - <futures::stream::map::Map<S, F> as futures::stream::Stream>::poll::hc3f0803cc3de6211
  12:     0x563c104dfd43 - <librespot_connect::spirc::SpircTask as futures::future::Future>::poll::h027424058774a76d
  13:     0x563c104cc911 - <librespot::Main as futures::future::Future>::poll::h2199e3ff23baa689
  14:     0x563c104c12ca - futures::task_impl::std::set::ha023258ce278254e
  15:     0x563c104cb730 - <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll::h2f62799807da35ef
  16:     0x563c104c11aa - futures::task_impl::std::set::h37e0f3f222e08868
  17:     0x563c104d449c - <std::thread::local::LocalKey<T>>::with::h7e7b710918453d2f
  18:     0x563c104d4162 - <std::thread::local::LocalKey<T>>::with::h2987dad893f4e60c
  19:     0x563c104d3ffc - <std::thread::local::LocalKey<T>>::with::h1952563f22ba5a79
  20:     0x563c104b9b58 - tokio_core::reactor::Core::run::hf58dc6e2100278f5
  21:     0x563c104cf2f9 - librespot::main::h0630283bdccf60ed
  22:     0x563c104bab02 - std::rt::lang_start::{{closure}}::hfd4a457f7ff285fe
  23:     0x563c1091df77 - std::panicking::try::do_call::haff1458bb210fa61
  24:     0x563c1094404e - __rust_maybe_catch_panic
  25:     0x563c10924686 - std::rt::lang_start_internal::h68d48e763626282f
  26:     0x563c104d0173 - main
  27:     0x7f8933b66b96 - __libc_start_main
  28:     0x563c104b4399 - _start
  29:                0x0 - <unknown>
```

**Comment by l3d00m** [comment]
The fix was added on 18-5-2018, your build is from 15-5-2018 (see log)

**Comment by User65k** [comment]
nice to know and good to hear.
fix confirmed :heart_eyes:

awesome project! :thumbsup:

**Comment by ComlOnline** [comment]
Closing this issue as its fixed. Thanks
