### ISSUE TITLE
 --onevent PROGRAM 

### ISSUE THREAD

**Issue by leszekb** [librespot-org/librespot#209]
Program called onevent parameters becoms zombie, this behavior creates long list zombies after long time using librespot

**Comment by leszekb** [comment]
Solution:
change .spawn() to .status() in src/player_event_handler.rs line 11.

**Comment by ComlOnline** [comment]
Hi @leszekb could you submit a pull request for this?

**Comment by leszekb** [comment]
The pull request (No. 221) about this error is waiting 21 days for acceptance :-)

**Comment by leszekb** [comment]
The pull request (No. 221) about this error is waiting 21 days for acceptance :-)

**Comment by leszekb** [comment]
#221

**Comment by ComlOnline** [comment]
Opps, Sorry about that.

**Comment by erkia** [comment]
Pull request #254 fixes this without blocking.

**Comment by StopMotionCuber** [comment]
This seems to be fixed, I'd request the issue to be closed
