### ISSUE TITLE
No sound output after the first selected song - pulseaudio backend (same problem with portaudio though)

### ISSUE THREAD

**Issue by thekingofjibs** [librespot-org/librespot#219]
Raspberry Pi 3 Ubuntu-Mate

Everything is fine for the first song that I pick and I can scrub within that as normal, but then when a new song starts it appears to load properly (using verbose mode) and pulseaudio still detects a sink-input but there is no sound output

**Comment by ComlOnline** [comment]
Hi @thekingofjibs Do you still have this issue?

**Comment by thekingofjibs** [comment]
Hi @ComlOnline I have recloned and recompiled the latest version and unfortunately this is still an issue
