### ISSUE TITLE
Panic does not exit

### ISSUE THREAD

**Issue by maufl** [librespot-org/librespot#226]
I noticed that when ever a panic is thrown, librespot stops working completely but does not exit.
This is unfortunate, as it would be restarted by systemd in my setup if it exits.

**Comment by plietar** [comment]
Librespot has a few threads, and a panic on one does not always cause others to stop.

You should be able to make all panics into process aborts by adding to `Cargo.toml` (assuming you're building with `--release`):
```toml
[profile.release]
panic = "abort"
```

Let me know if that works. This seems like a reasonable thing to do, so I could add it here.

**Comment by maufl** [comment]
Doesn't that also mean that the stack is not unwound and we won't get any stack traces if it panics? I actually added 

```Cargo.toml
[profile.release]
debug = true
```
just to get nice stack traces. (Debug build is not performant enough to smoothly play music)

**Comment by maufl** [comment]
Ok, I tried it. Strangely, now when librespot crashes, it seems to hang with 100% CPU utilization. Also, I don't get a stack trace.

**Comment by michalfita** [comment]
@wfraser You seem to be very fluent in all this multiprocess/multithreading task - could you try to solve this issue? Reproduction requires disconnection of broadband during playing - should be easy to reproduce on virtual machine.

**Comment by roderickvd** [comment]
This behaviour is known to me e.g. when the player thread panics. @JasonLG1979 is putting quite a lot of effort in error handling in #823, let's see how that goes.

**Comment by roderickvd** [comment]
Can you test and report back now that #823 has been merged?

**Comment by uSpike** [comment]
I find that with v0.3.1 librespot will exit after a crash.
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', connect/src/spirc.rs:1155:29
...
[2021-11-17T14:28:17Z DEBUG librespot_connect::spirc] drop Spirc[0]
[2021-11-17T14:28:17Z DEBUG librespot_playback::player] Shutting down player thread ...
[2021-11-17T14:28:17Z DEBUG librespot_playback::player] drop PlayerInternal[0]
[2021-11-17T14:28:17Z DEBUG librespot_playback::player] PlayerInternal thread finished.
[2021-11-17T14:28:17Z DEBUG librespot_core::session] drop Session[0]
[2021-11-17T14:28:17Z DEBUG librespot_core::mercury] drop MercuryManager
[2021-11-17T14:28:17Z DEBUG librespot_core::session] drop Dispatch
$
```

**Comment by JasonLG1979** [comment]
> I find that with v0.3.1 librespot will exit after a crash.

That would be happening here:

https://github.com/librespot-org/librespot/blob/dev/connect/src/spirc.rs#L1155

**Comment by roderickvd** [comment]
So that means we can close this issue?

**Comment by JasonLG1979** [comment]
> So that means we can close this issue?

No. That means we need to make sure this isn't zero:

https://github.com/librespot-org/librespot/blob/dev/connect/src/spirc.rs#L1141

**Comment by JasonLG1979** [comment]
We're trying to grab the 1st thing (index 0) from a thing with a length of 0.

**Comment by JasonLG1979** [comment]
I'm not exactly sure of the context of what exactly the thing is but the return type is an option. Provided whatever is asking for it actually checks it and doesn't just unwrap we can just return None if the len is 0.

**Comment by uSpike** [comment]
> So that means we can close this issue?

Yes, in my opinion this issue has been solved (not exiting on panic).

> > So that means we can close this issue?
> 
> No. That means we need to make sure this isn't zero:
> 
> https://github.com/librespot-org/librespot/blob/dev/connect/src/spirc.rs#L1141

I'd suggest that be opened as a separate issue.

**Comment by roderickvd** [comment]
I agree. Thanks to @JasonLG1979 so that we can now close this issue, and @uSpike for reporting back on it. Do file that new issue with steps how to reproduce that.
