### ISSUE TITLE
Automatically reconnect after connection loss

### ISSUE THREAD

**Issue by djmaze** [librespot-org/librespot#230]
When internet connectivity is lost, librespot (running under a snapcast server) outputs:

```
2018-05-31 16-46-33 [Info] (Spotify) ERROR:librespot_core::session: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
```

When connectivity returns, the librespot device just disappears from the device list in Spotify and does not return. The Spotify connection in librespot is permanently lost. I have to restart the app in order get it working again.

We could just try to periodically reconnect when the connection fails?

**Comment by ComlOnline** [comment]
Hi @djmaze, This is annoying a well known bug see #134. I would follow that Issue for updates.

Many thanks
