### ISSUE TITLE
TRACK_ID Format ? 

### ISSUE THREAD

**Issue by rperrot** [librespot-org/librespot#232]
Hi, 

first of all, I'd like to thanks all dev for their valuable work.

I'm trying to use the --onevent to get information about the currently played track. 

To do this I'm using TRACK_ID environment variable in a python script. However, when querying the Spotify API I got an error result indicating that the track id is invalid. I think there's a transformation (encoding ?) between the spotify track ID and the exported environment one. 

for example a valid track in spotify (using official app) 5Fhn1eNY4Eexndp9DWHZnn, is exported in the environment variable TRACK_ID value "ba292267a139477c86f108d66f4f9cc5" which is an invalid spotify track id. 

I can't find a hint about how to decode the environment variable TRACK_ID. Does anybody can give me a clue to get the correct value ?

**Comment by rperrot** [comment]
Ok, I found it looking into the code. (is it possible to add it in the doc ?)

TRACK_ID is in base16 so I need to decode it then encode it in base62 to use spotify api.

**Comment by StopMotionCuber** [comment]
I guess this is somewhat confusing if spotify uses base62 for its official app.
I would propose to change the TRACK_ID environment variable to base62 in this case.

**Comment by rperrot** [comment]
I don't want to suggest the change (if it's like that, there must be a reason), however I would suggest to document it.

**Comment by kingosticks** [comment]
It sounds wrong, the change sounds good. It's supposed to be a format you can easily use.

**Comment by sashahilton00** [comment]
Agreed, it should be changed to base62 to bring it inline with the other Spotify clients.
