### ISSUE TITLE
Read Only RPi

### ISSUE THREAD

**Issue by giggywithit** [librespot-org/librespot#233]
Hello

I am attempting to use raspotify on Raspian Lite and have been successful at creating images that are [read only](https://learn.adafruit.com/read-only-raspberry-pi/overview). The only function missing upon creating the working image is raspotify and librespot. Everything else works, network, ssh etc.. Raspotify is a front end to librespot.

Ideas?

**Comment by sashahilton00** [comment]
This tracker isn't really the place for raspotify questions, as it deals with issues with the librespot library. please ask questions via raspotify's support channels.
