### ISSUE TITLE
Where to jump in when a device is connected/disconnected?

### ISSUE THREAD

**Issue by itsmebasti** [librespot-org/librespot#235]
I'm trying to switch my amplifier on and off whenever a device is connected with my pi-musicbox (using this library). So my question is where is the best spot to jump in. I found a play/pause state machine where I could trigger my stuff, but I would prefer a connection based trigger.

**Comment by ashthespy** [comment]
Missed this, you would be looking for `MessageType::kMessageTypeLoad` 
Take a look a [ashthespy/librespot](https://github.com/ashthespy/librespot/blob/f67905a4eeaf5a387107054080f64ac0a85c8ae4/connect/src/spirc.rs#L546-L554) for an implementation idea.
