### ISSUE TITLE
Is this project alive / librespot stop being visible without error

### ISSUE THREAD

**Issue by michalfita** [librespot-org/librespot#240]
Since 18 May there is no commits to main repository - plenty of forks are alive and active, but raspotify uses code from here. Is this project alive?

I have serious issues with librespot that annoys whole family. Suddenly without any error message in logs it stops being visible as Spotify Connect device. I have to login and restart the whole service to get it back.

Would be nice if it at least crashes, so systemd would be able to restart. Any hints or predictions when it could be fixed? Maybe one of forkers already have a solution for that?

**Comment by ComlOnline** [comment]
Sorry, I have beeing working at a summer camp for the last few months, that all ends in a few days so Ill have a lot more time to look after this.

Do you have anymore information about your install? What version are you using?

Many Thanks

**Comment by SirJson** [comment]
Might be related to #172? I frequently run into this bug and if no one else fixes it by the time I get librespot working with my application again then I will maybe fix that...

**Comment by michalfita** [comment]
So, my symptoms are like in #241. The log shows:
```
Aug  6 19:22:41 malina librespot[11050]: INFO:librespot_playback::player: Track "Translucent" loaded
Aug  6 19:41:15 malina librespot[11050]: ERROR:librespot_core::session: Os { code: 110, kind: TimedOut, message: "Connection timed out" }
```
I started to think about writing a log filter in Python to restart the librespot on each occurrence of the time out.

libresport doesn't have --version option, so I can't display it's version. It's coming from most recent raspotify as of today. All running on regularly updated Raspbian Stretch.

**Comment by sashahilton00** [comment]
The project is still alive, though there hasn't been much activity in the past couple of months, as the core maintainers have been/are busy, and there haven't been many pull requests. I note there are lots of forks adding functionality, if people want that added to the main repo, feel free to open a PR.

**Comment by sashahilton00** [comment]
Closing as main question resolved. For secondary question, refer to #172

**Comment by michalfita** [comment]
Another session error causing trouble:
```
Aug  6 22:45:57 malina librespot[16608]: ERROR:librespot_core::session: Os { code: 104,
 kind: ConnectionReset, message: "Connection reset by peer" }
```
Again, only restart helps.
