### ISSUE TITLE
How can I tell libresport to use 6 channels

### ISSUE THREAD

**Issue by Jean-PhilippeD** [librespot-org/librespot#252]
Hi,

I'm trying to make my 6 channels device to work.

With `speaker-test -Dplug:surround51 -c6 -twav` I got the 6 channels working fine, but I can't make them work through librespot.

**Comment by rage2dev** [comment]
Hey Jean,

what do you want to achieve with it? 
- Stereo -> 5.1 ... ?  
Why don't output 2.0 and let your AV-Reciever take the task of duplicating channels?

**Comment by kingosticks** [comment]
> -c6 aka use card 6

-c in the context of speaker-test is channels, not card index. I don't think your alsamixer support will help here.

librespot has 2 channels of audio data. It you want 6 you need to have something external that takes those 2 channels and replicates/filters them into something resembling 5:1. I think it's reasonable to say that this is not librespot's job. Either do it in some kind of alsa plugin or externally as @rage2dev suggests.

**Comment by ashthespy** [comment]
doh. yes of course - Never mind my previous comment.

You could manually map the 2 channel audio to 6 channels with `ttable` in `asound.conf`  check out the Arch wiki for some examples.

**Comment by Jean-PhilippeD** [comment]
Ok I've made some tests with ttables.

I can forward the 2 front speakers onto the 2 rear speackers, it works fine with mpg321 or aplay.
I've overwritten the default conf with this kind of asoundrc file:

> pcm.!default {
>     type route;
>       slave.pcm "hw:2,0"
>       slave.channels 6
>       ttable.0.0 1
>       ttable.1.1 1
>       ttable.0.2 1
>       ttable.1.3 1
>       ttable.0.4 1
>       ttable.1.4 1
>       ttable.2.5 1
>    }
> }
> 

But no matter what I specify in librespot, the sound refuse to play on rear speakers, I've tried many with --device and I can't get it works.. :(

**Comment by sashahilton00** [comment]
Closing this as it's not an issue with librespot, but rather alsa config, which is outside the scope of the project.
