### ISSUE TITLE
Change librespot to support free accounts

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#261]
Spotify have changed their policy on Connect being restricted to premium accounts only as detailed in a number of publications:

https://developer.spotify.com/community/news/2018/09/14/updates-mobile-platform/

@plietar would you mind detailing the 1 line change you mentioned earlier that removes the requirement for a premium account?

EDIT: Updated link to point to Spotify dev blog.

**Comment by ashthespy** [comment]
Probably more relevant:
https://developer.spotify.com/community/news/2018/09/14/updates-mobile-platform/

**Comment by kingosticks** [comment]
There are still numerous differences between free and premium:
* Audio quality
* *Adverts*
* 'unlimited skips'
This change makes librespot a target, I don't see the point.

**Comment by sashahilton00** [comment]
@kingosticks good points. Will email one of the devs and ask about that.

**Comment by awiouy** [comment]
Make it an option?

**Comment by plietar** [comment]
I agree with @kingosticks. Unless someone goes through the effort of reverse engineering and implementing the Spotify free features (mostly adverts), I don't think it's acceptable to do this.

Even if we do it, it becomes trivial for someone to modify librespot to remove the ads, producing a version which is not compliant with the restrictions imposed by the free service, putting us at risk.

**Comment by sashahilton00** [comment]
I've sent an email to one of the Spotify devs. We'll see what they say w/ regards to free accounts.

**Comment by szymonmatuszczak** [comment]
Why would you bother with a Spotify's devs statement? If they want to provide a adverted API, they should do it. This is a open source project and shouldn't implement "security by obscurity" manners. If they want to cap the bitrate, they should do it server side, if they want to force ads, they should implement such thing server side, like sending URL of advert and sending 403 when trying to obtain any other audio data during the ad. I own my computer and I should decide what software running on it does, and they own their servers and they should decide what their computers does. As simple as that. I would probably fork this project as really libre alternative.

**Comment by sashahilton00** [comment]
> Why would you bother with a Spotify's devs statement? If they want to provide a adverted API, they should do it.
Because they may not have the resources to maintain a public library, and because if we circumvent their TOS, then they'll block the project as they have done previously.
> This is a open source project and shouldn't implement "security by obscurity" manners.
It doesn't...
> If they want to cap the bitrate, they should do it server side, if they want to force ads, they should implement such thing server side, like sending URL of advert and sending 403 when trying to obtain any other audio data during the ad.
If you actually look at the code and how the protocol works, then you'd know that isn't feasible.
> I own my computer and I should decide what software running on it does, and they own their servers and they should decide what their computers does.
That's already the case. Don't like it? Don't run it. You're welcome to reverse engineer the protocol further, bypass the free restrictions and then deal with Spotify trying to shut your project down. That's not what this project is about. $10/month for unlimited music is not expensive. For the number of hours you spent trying to reverse engineer their protocol and work around their restrictions, you could probably get a job and just pay for premium for several years.
> As simple as that. I would probably fork this project as really libre alternative.
Go ahead, just change the identifiers from librespot as we're not interested in being caught in the crossfire when your derestricted version gets banned.

**Comment by pedrogonsilva** [comment]
Hi 

Any news regarding this?

**Comment by JustMyGithub** [comment]
@sashahilton00 It's been half a year since you wrote that email - Spotify should have replied, didn't say? If not, would you mind reminding them?

**Comment by sashahilton00** [comment]
I've heard nothing back from Spotify on this. We're not going to be reverse engineering limited skips and ads anytime soon. If someone else wants to do that and PR, we can look into supporting free accounts, but until then, I'm closing this issue.

**Comment by probonopd** [comment]
> limited skips and ads

Are the requirements known?

**Comment by mirh** [comment]
I mean, if you don't want to be booted out for foul play/piracy, I guess like they are. 
Though arguably desktop clients would be already fine with just ads.

**Comment by probonopd** [comment]
There is a (closed source?) SDK from Spotify for device manufacturers that probably implements all of this.
Would it be an option to `dlopen()` that binary library and use it for the ads and stuff, if a user is using a Free account? This way nothing would have to be reverse engineered, it would just use the official SDK from Spotify.

**Comment by devgianlu** [comment]
@probonopd I believe you have to make a request to use that SDK and they'll make a contract with you. I don't think they'll be okay with sharing it with the open source community, given that I would love to get my hands on it to reverse engineer it.

**Comment by probonopd** [comment]
Well. I am not working for Spotify but I would assume that they share the binary library of the SDK under an NDA that prevents you from reverse-engineering it. But why would anyone want to. For paid accounts, librespot works as-is, and for Free accounts, it could call into that binary blob. At least in theory. (I do not know what strings are attached with getting a license for the binary blob.)
