### ISSUE TITLE
Implement 'unshuffle' functionality

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#264]
Currently when one shuffles the songs, the local queue in librespot is shuffled. when shuffle is disabled, the queue is not unshuffled. We should retrieve the original playlist on unshuffle, and then replace queue will all tracks after the index of the one currently playing.

**Comment by kingosticks** [comment]
Indeed. We need to look up the context for this. In cases where this is no context, I'm not sure what you do.

**Comment by ashthespy** [comment]
If we can keep track of the seed, the [Fisher–Yates](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle) algorithm might be a way to shuffle - unshuffle lists with small overheads?

**Comment by sashahilton00** [comment]
Not sure it's an official algorithm, just made it up to be what I thought a sensible way to do things. How you shuffle the integer array initially is up to you

**Comment by kingosticks** [comment]
I think when I was experimenting the official app just didn't let you unshuffle. However, most of the time you do have a context so you just don't notice. That to me seems fine, the less complicated the better. But maybe its changed, someone should investigate.

**Comment by sashahilton00** [comment]
> That to me seems fine, the less complicated the better. But maybe its changed, someone should investigate.

What is `that` in this sentence?

**Comment by sashahilton00** [comment]
Now this is interesting, Spotify filed a patent for a weighted playlist shuffling algorithm: https://patentimages.storage.googleapis.com/d2/65/e2/8d6d3df46e77da/US20170244770A1.pdf and the weights are included with the tracks in a playlist, when retrieved via a uri such as `hm://playlist/user/spotify/playlist/37i9dQZF1DWWjGdmeTyeJ6?revision=1542071134%2C0000008f00000166ef91c8b900000166eb2e5322&handlesContent=`

More food for thought, I don't think we need to implement the same level of complexity, something like fisher yates or a random shuffle and context retrieval should be plenty.

**Comment by kingosticks** [comment]
The problem with the non-context case is when some other client shuffles the tracks and sends them in an update, all you have it those tracks. You have no way to unshuffle them. The other client may have shuffled a hundred time before librespot joined the connect session so it really has no idea.

> What is that in this sentence?

Not letting you unshuffle tracks without a context. Or, rather, making it a no-op.

**Comment by sashahilton00** [comment]
Have just experimented, Spotify is syncing shuffle state across clients. If you shuffle on one client, skip a song, connect from another client and take over listening, you can go back to the previous song. However, if you shuffle a playlist on `client 1`, switch playback to `client 2` as in the previous scenario, then kill `client 1` and try to go back to the previous shuffled song on `client 2`, you can't. So it looks like there's some sort of shuffle state passed from `client 1` to `client 2` that is lost when one closes `client 1`. Additionally shuffle and repeat features are not available on dailymixes, which makes me think that there is some sort of additional protocol for communicating shuffle state that hasn't been upgraded to support dailymixes yet.

**Comment by kingosticks** [comment]
I'm not sure I follow what you are saying here. The (shuffled) track list and current track index give you all the state you need to skip backwards. This is all already implemented in librespot, yes?

**Comment by kingosticks** [comment]
Yes, exactly. That's how it all works already and that's what we support in the original shuffle/repeat/queue work.

**Comment by sashahilton00** [comment]
sure, but that doesn't explain why you can skip back/forwards when the client that originally shuffled it is open, but when you move clients and close the previous, you lose the ability to skip back

**Comment by sashahilton00** [comment]
it's a minor issue, i'm not bothered if we can't skip back after switching clients on a shuffled playlist, but just thought i'd note it.

**Comment by kingosticks** [comment]
I found the behaviour was inconsistent between phone and desktop clients. It might just be their buggy software.
