### ISSUE TITLE
Shuffle and Repeat turn off when a new song is selected

### ISSUE THREAD

**Issue by ndbeals** [librespot-org/librespot#266]
As the title suggests, Whenever I have shuffle and repeat functionality turned, whenever I select a new song, it turns those options off. Here's a quick clip of it happening:

![2018-11-17_11-07-24](https://user-images.githubusercontent.com/850796/48663128-68709e00-ea59-11e8-879c-cd0b9ae8c458.gif)

This only started happening a few weeks ago.

**Comment by faabmaster** [comment]
I'm also affected by this issue. Has anyone found a solution to this, considering it's been a year since it was first reported?

**Comment by ndbeals** [comment]
> I'm also affected by this issue. Has anyone found a solution to this, considering it's been a year since it was first reported?

My solution was to stop using librespot in general.

TBH, I'd forgotten about this issue. Hard to believe it's been an entire year with literally zero activity on it.

**Comment by faabmaster** [comment]
> > I'm also affected by this issue. Has anyone found a solution to this, considering it's been a year since it was first reported?
> 
> My solution was to stop using librespot in general.
> 
> TBH, I'd forgotten about this issue. Hard to believe it's been an entire year with literally zero activity on it.

Did you find a good alternative? Not only was I affected by the shuffle and repeat issue, it also only seemed to play about 20 songs in the playlist, ones that were particularly close to each other in the list. I really like the functionality Librespot gives but if there's a good alternative I'd love to hear it.

**Comment by devgianlu** [comment]
You could try librespot-java, it has some issues (depending on the branch you use), but it works.

**Comment by faabmaster** [comment]
I'll definitely look into it, thankyou.

**Comment by willstott101** [comment]
I've made a PR #386 which seems to resolve this issue for me. Please try it out if you have the time.
