### ISSUE TITLE
When adding tracks they get added after the current playing track

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#27]
<a href="https://github.com/wezzynl"><img src="https://avatars2.githubusercontent.com/u/5656741?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [wezzynl](https://github.com/wezzynl)**
_Thursday Feb 11, 2016 at 20:45 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/45_

----

Playing works like a charm, thanks for that. When adding tracks they get added after the currently playing track in stead of after the last item in the playlist.

**Comment by ComlOnline** [comment]
Hi @wezzynl As far as I am am aware this is the way that it should work. Feel free to comment if this is still an issue.
