### ISSUE TITLE
python-librespot does not compile with this repo

### ISSUE THREAD

**Issue by taixzo** [librespot-org/librespot#287]
The python interface, https://github.com/plietar/python-librespot does not build with this fork. As far as I can tell it was never updated past the changes in the original repo which removed MetadataManager, MetadataTrait etc. I've gone through and fixed the name resolution errors in a local copy of the code, but now there are some errors due to things being implemented differently, which I don't know how to fix.

**Comment by sashahilton00** [comment]
This library has come a ling way since then, the python-librespot library is pretty old. It would probably be quicker to write a new wrapper tbh.
