### ISSUE TITLE
Use pulseaudio native volume management

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#29]
<a href="https://github.com/paradis"><img src="https://avatars1.githubusercontent.com/u/4386641?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [paradis](https://github.com/paradis)**
_Tuesday Apr 19, 2016 at 18:44 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/75_

----

Hello,

When using pulseaudio backend it would be nice to delegate volume management to pulse audio sink. Besides having a logarithmic scale natively, it would also allow to manage librespot volume in one place and avoid several volume alteration (librespot, pulseaudio sink, pulseaudio output).

However, it would be necessary to move volume management from the player to the audio_backend.

What do you think?

**Comment by sashahilton00** [comment]
<a href="https://github.com/joerg-krause"><img src="https://avatars2.githubusercontent.com/u/6870896?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joerg-krause](https://github.com/joerg-krause)**
_Saturday Aug 27, 2016 at 23:58 GMT_

----

I'd like to see this for the ALSA backend, too!

**Comment by brain0** [comment]
Using pulseaudio's volume control requires using the asynchronous pulseaudio API instead of the "simple" API. This is very complex, since nobody has done this in Rust yet. I have started a prototype for a pulseaudio API binding for tokio, but haven't worked on it for a while now.

**Comment by mirko** [comment]
I'd really like to see the native volume management being used as well. I'm aware of the API change using PulseAudio and its necessary effort, though..

**Comment by roderickvd** [comment]
#685 implements what you ask for (logarithmic and cubic mappings, transparently for all backends), without the need to implement the asynchronous PulseAudio API.

If you feel like you don't want bits touched by volume controls in several places, then either set `librespot` or PulseAudio volume fixed to 100% and it will bypass touching any samples.
