### ISSUE TITLE
Switching tracks no longer working correctly

### ISSUE THREAD

**Issue by IsaacWoods** [librespot-org/librespot#290]
I've recompiled an application using librespot after a while (it used to work perfectly).

Most of it still works (can still successfully connect, load tracks and stream audio), but switching tracks no longer works correctly. Instead, something like this happens:

1) Switch to the device using librespot using Connect
2) A correct `PlayerCommand::Load` is received
3) Select another track using official client
4) Another `PlayerCommand::Load` is received, but for the previous track (the one already playing, not the one just selected).

**Comment by thusly** [comment]
I'm having the same issue, although I actually assumed it was because I hadn't recompiled in ages. This problem started occurring for me yesterday, with a librespot binary that was compiled months ago and had been working fine, otherwise.

I just recompiled to see if the issue would be resolved, and it's still occurring (and here I am). I'm assuming something changed on Spotify's end.

**Comment by forslund** [comment]
Think this is the same issue as I reported in #288

**Comment by IsaacWoods** [comment]
This is indeed connected to #288 (I didn't realise at first it was to do with the URI stuff).

This is fixed by changing [this line](https://github.com/librespot-org/librespot/blob/master/connect/src/spirc.rs#L217) to:
```
let uri = format!("hm://remote/user/{}/", session.username());
```

I have no idea why this stopped working (maybe API v2 was deprecated internally and so they moved the endpoint, but this seems to fix it, so closing).

**Comment by AxelNilsson** [comment]
This should be reopened, since the master isn't fixed.

**Comment by dtcooper** [comment]
Getting a lot of reports of this re: [raspotify#183](https://github.com/dtcooper/raspotify/issues/183), but unobserved myself

**Comment by kingosticks** [comment]
If #288 also fixes this then we don't need two open issues for what is essentially the same thing.

**Comment by sashahilton00** [comment]
as @kingosticks said, this is a duplicate. continue discussion in #288.
