### ISSUE TITLE
possibility to have a passthrough option when using pipe

### ISSUE THREAD

**Issue by philippe44** [librespot-org/librespot#295]
Is this possible to bypass the Vorbis decoder when using the pipe output so that the untouched Vorbis encoded data is sent onto the pipe

**Comment by michaelherger** [comment]
Now that's a question I'd be very much interested in, too. Obviously :-)

**Comment by kingosticks** [comment]
Out of interest, what's the usecases for this? The one I can think of isn't a great direction for this project.

**Comment by michaelherger** [comment]
It's not what you think. I'm using a [modified version of librespot](https://github.com/michaelherger/spotty) to stream to the Squeezebox players. The Squeezebox can play ogg directly. Which means that the transcoding is unnecessary overhead - which _can_ be a problem when users are running it on under-powered systems like some NAS.

**Comment by sashahilton00** [comment]
If you want to submit a PR to add it as a runtime flag, be my guest. Spotify is suitably disengaged from the developer community to the extent that if they're not providing that functionality, I don't have a problem with librespot providing it, so long as it's not just dumping it into a file for obvious reasons. I'm sure Spotify will be in touch if they have a problem with it 🙃

**Comment by sashahilton00** [comment]
This is currently in progress in PR #569, hence closing in favour of that.
