### ISSUE TITLE
Build is broken (fail on arc-swap)

### ISSUE THREAD

**Issue by sxwsxwsxwsxw** [librespot-org/librespot#301]
Currently building does not work anymore, although it still worked 2 weeks ago.

git status:
On branch master
Your branch is up-to-date with 'origin/master'.

cargo build --release
.........
..........
.........
   Compiling arc-swap v0.3.7
error: the struct `#[repr(align(u16))]` attribute is experimental (see issue #33626)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/arc-swap-0.3.7/src/debt.rs:19:1
   |
19 | #[repr(align(64))]
   | ^^^^^^^^^^^^^^^^^^

error: non-string literals in attributes, or string literals in top-level positions, are experimental (see issue #34981)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/arc-swap-0.3.7/src/debt.rs:19:1
   |
19 | #[repr(align(64))]
   | ^^^^^^^^^^^^^^^^^^

error: the struct `#[repr(align(u16))]` attribute is experimental (see issue #33626)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/arc-swap-0.3.7/src/gen_lock.rs:47:1
   |
47 | #[repr(align(64))]
   | ^^^^^^^^^^^^^^^^^^

error: non-string literals in attributes, or string literals in top-level positions, are experimental (see issue #34981)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/arc-swap-0.3.7/src/gen_lock.rs:47:1
   |
47 | #[repr(align(64))]
   | ^^^^^^^^^^^^^^^^^^

error: slice pattern syntax is experimental (see issue #23121)
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/arc-swap-0.3.7/src/lib.rs:1030:32
     |
1030 |                 .fold([0, 0], |[a1, a2], s| {
     |                                ^^^^^^^^

error: slice pattern syntax is experimental (see issue #23121)
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/arc-swap-0.3.7/src/lib.rs:1031:25
     |
1031 |                     let [v1, v2] = s.snapshot();
     |                         ^^^^^^^^

error: aborting due to 6 previous errors

error: Could not compile `arc-swap`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by willstott101** [comment]
2 days ago the minimum rust toolchain version was bumped to 1.26 from 1.23 in #284

I expect this is the cause of your issue, can you try updating your rust installation?

**Comment by sxwsxwsxwsxw** [comment]
You were right......

Now building with rustc v1.32 and that works.
