### ISSUE TITLE
Time offset in playback position

### ISSUE THREAD

**Issue by D54** [librespot-org/librespot#310]
The connect-client's playback position is approximately 50s behind the real one.
So when the playback is at 3m 0s, the player shows 2:10.
When the playback is paused, the offset is gone.

Additional symptoms:
- When the client gets negative position, it shows the seekbar and time as the track would be ending right now (position = duration) until the end of the current song.
- Songs end when the seekbar shows 50s remaining.

**Librespot version**: ef28df6
built with: `--no-default-features --features alsa-backend --release`
**Client version:**
1.0.98.78 (Linux)
Webclient is also affected.

**Comment by devgianlu** [comment]
Check that your device time is aligned with any NTP server.

**Comment by sashahilton00** [comment]
@devgianlu there is almost certainly some time sync going on between clients. I found a `core.clock_delta` variable earlier in the client, I imagine they are keeping time synced across instances.

**Comment by devgianlu** [comment]
That makes sense since the original client isn't effected by this issue, but I think that synchronizing with an NTP server by shifting the system time is enough for our purpose.

I think that implementing it in `librespot` shouldn't be very difficult as it's already relaying on [custom function](https://github.com/librespot-org/librespot/blob/ef28df63018eeb4bae6bb8ea5d4eb14ed36a962a/connect/src/spirc.rs#L60) to get the time.

**Comment by plietar** [comment]
Packet 0x4 (https://github.com/librespot-org/librespot/blob/master/core/src/session.rs#L170)  contains a timestamp as the payload.
Client replies with a 0x49 packet, and finally the server sends a 0x4a back.

I suspect this sequence of packets is used for time synchronization

**Comment by devgianlu** [comment]
The `Ping (0x4)` packet seems to have the server timestamp as a payload. `PongAck (0x4a)` will reply with anything that is sent with `Pong (0x49)`.

**Comment by D54** [comment]
I can confirm time-synchronization solved the problem, but I think this is not the optimal solution.
There should be some info about this requirement until the official protocol is implemented.
Anyway, thanks for the help and the possible future implementation!

**Comment by mfeif** [comment]
It doesn't seem to be the same behavior, though it could be the same bug. For example, my clients don't stop paying before the song ends, or based on erroneous UI settings.

But I dug in and looked into the clocks...

The device and my laptop (where the clients are) were within 1 second of one another; close enough that I can't tell without running some kind of sync script between them. When I sync'd them both to the same ntp server, one was off by -0.011 seconds, the other by +0.041 ... so a total mismatch of 5 one hundredths of a second. Neither was off from "real" time (where presumably the spotify servers live) by even that much.

The device also does an ntp sync every day, at midnight or some such, so a manual force shouldn't be required.

But indeed, forcing a resync to ntp on the device where librespot was playing, then killing librespot and starting again did make these problems go away.

Seems like 0.05s is a little tight for tolerance :-[

**Comment by sashahilton00** [comment]
#321 should fix this.
