### ISSUE TITLE
Unable to change song?

### ISSUE THREAD

**Issue by solars** [librespot-org/librespot#330]
Hi there,

I noticed that when using spotify playback, I'm unable to change songs.
I can only add them to the Queue and klick next, but if I click on a different song, it will just start the current song over.
It works if I switch playback to my phone, change it, and go back to the player.

Is anyone experiencing the same?
I'm using moodeaudio which includes librespot, but I have no idea how to get the librespot version, there doesn't seem to be a command line option for it?

Thank you,
Christoph

**Comment by ashthespy** [comment]
Your probably running a version pre 9b6b55ee7d692ad626591ec3064b6e6b74a6d360 try updating it!

**Comment by solars** [comment]
Thank you, I will try to upgrade!

**Comment by Csierra099** [comment]
> Your probably running a version pre [9b6b55e](https://github.com/librespot-org/librespot/commit/9b6b55ee7d692ad626591ec3064b6e6b74a6d360) try updating it!

Hello, can you tell me how to update it, please! Thank you :)

**Comment by solars** [comment]
closing this meanwhile as the problem is fixed for me

**Comment by Csierra099** [comment]
> closing this meanwhile as the problem is fixed for me

How did you fixed it?

**Comment by solars** [comment]
> > closing this meanwhile as the problem is fixed for me
> 
> How did you fixed it?

I upgraded - but I upgraded moodeaudio which includes the new version.
If standalone then I guess you have to rebuild it according to the instructions

**Comment by Csierra099** [comment]
> > > closing this meanwhile as the problem is fixed for me
> > 
> > 
> > How did you fixed it?
> 
> I upgraded - but I upgraded moodeaudio which includes the new version.
> If standalone then I guess you have to rebuild it according to the instructions

Sorry for the dumb question but how do I do that? Im also using moodeaudio but how can I update it? Thank you in advance!

**Comment by solars** [comment]
Ah sorry, here is the thread:
http://moodeaudio.org/forum/showthread.php?tid=1268

I just fetched the version 5, RC1 image and replaced my installation.
I'm not sure how to update only librespot
