### ISSUE TITLE
Possibility to reauthenticate after device goes idle for a while?

### ISSUE THREAD

**Issue by yyjhao** [librespot-org/librespot#331]
I have been using raspotify on my Raspberry Pi at home and control it with the spotify web API again through my Raspberry pi. I have noticed that frequently, if I use spotify at work on a laptop, the web API will fail to switch the playback to librespot when I come back home as the librespot device will not appear in the device list.

There are 2 ways I can fix this:
1. Use an official spotify client to connect to the device again - this sometimes causes the play queue to be lost as it's replaced by the one on the official app.
2. Restart raspotify/librespot on my raspberry pi - this takes a while and is rather cumbersome.

However, I wonder if it's possible that this can be fixed by 're-register' or 're-authenticating' in librespot given that 2 works. If so that will be much faster than having to restart raspotify or go through the official spotify app.

**Comment by michalfita** [comment]
Oh, that's actually interesting. I didn't realize that until I read your comment, but same happens to me.

**Comment by yyjhao** [comment]
I made https://github.com/librespot-org/librespot/pull/376 for this.

**Comment by Ja83La** [comment]
Same problem here - device disapears from devices list after a while. As a consequence a can no longer control the device via the web-api. Until now, i found no workaround.

**Comment by janek** [comment]
I'm experiencing the same problem and would appreciate any tips toward solving it. I'm trying to use Spotify+Raspi as a musical alarm clock, but if I'm idle for too long during the day, it won't work in the morning. 

The information that I can restart raspotify/librespot to mitigate this is new to me - thank you for that @yyjhao (and for creating this issue). 

Have you made an issue on the raspotify repo yet? Maybe that would be a better place to handle this? (basing this proposition off of a comment by @kingosticks in #376)

**Comment by schickling** [comment]
@sashahilton00 given you've closed this issue, could you please leave a comment whether this was somehow addressed/fixed in librespot or whether it's still an issue?

**Comment by roderickvd** [comment]
Situation is the same. Groundwork was laid down in `new-api` to make it better, but I’ve had little time as of late.
