### ISSUE TITLE
No method to get playback position

### ISSUE THREAD

**Issue by skykooler** [librespot-org/librespot#332]
There seems to be no method to directly retrieve the playback position of a librespot_playback::player::Player object. The internal state (Playing/paused/etc) is not exposed either so I can't just count time since playback started (as playback may start several seconds after the load() call due to buffering). Would it be possible to add such a utility method?

**Comment by ashthespy** [comment]
You could get by with something along these lines that I started working on for prefetch e1ab35bdf0cbad7976e58b73518af9b63fa2a19f : 
https://github.com/librespot-org/librespot/blob/e1ab35bdf0cbad7976e58b73518af9b63fa2a19f/audio/src/lewton_decoder.rs#L27-L32
