### ISSUE TITLE
Not playing/hangs on next song

### ISSUE THREAD

**Issue by peterdk** [librespot-org/librespot#336]
In one of my playlists I keep hitting the issue that the last 3 songs of my playlist fail to play. On Spotify OSX I have selected Librespot running on my RPi. When it reaches the song  in the interface before the failing ones it just doesn't go to the next and keeps hanging on the last one. When I select the next song it starts 'playing', but Librespot doesn't log the new song and though the progressbar moves in Spotify, there is no audio.
I also tried running Librespot with --verbose, but nothing is outputted.

Is this due to CDN for example? Can I get more debug output out of Librespot?

I am using Raspotify compiled with the current master of Librespot.

**Comment by peterdk** [comment]
`INFO:librespot_playback::player: Track "nyepi" loaded
DEBUG:librespot_audio::fetch: File e78b42a721592a2de8436a6c3b94ea2a78f478f5 complete
DEBUG:librespot_core::session: Session[0] strong=3 weak=4
DEBUG:librespot_core::session: Session[0] strong=3 weak=4
DEBUG:librespot_connect::spirc: At track 11 of 15 <"spotify:user:peterdekr:playlist:7wxwjYJQXDjhtE3kdd1ZmV"> update [true]
DEBUG:librespot_playback::player: command=Load(SpotifyId(u128!(267662077716844162978646694263632685810)), true, 0)
INFO:librespot_playback::player: Loading track "City Gardens" with Spotify URI "spotify:track:67YlhgBxHM8uZAANzSPnc6"
DEBUG:librespot_audio::fetch: Downloading file b48e835716bd7e41dce43c612f0eed109bdf690d
DEBUG:librespot_playback::player: Normalisation Data: NormalisationData { track_gain_db: -3.550003, track_peak: 0.8924745, album_gain_db: -4.459999, album_peak: 0.91598123 }
DEBUG:librespot_playback::player: Applied normalisation factor: 0.66450745
INFO:librespot_playback::player: Track "City Gardens" loaded
DEBUG:librespot_audio::fetch: File b48e835716bd7e41dce43c612f0eed109bdf690d complete
DEBUG:librespot_core::session: Session[0] strong=3 weak=4
DEBUG:librespot_core::session: Session[0] strong=3 weak=4
DEBUG:librespot_core::session: Session[0] strong=3 weak=4`

Here it played the first song ok, and then hangs at the end in Spotify and won't go to the new one. Nothing in the log indicating that something goes wrong.

**Comment by michaelherger** [comment]
What bitrate are you using? I've got a report of a track which would not play if librespot was told to stream in 320kbps, but the track wasn't available in that bitrate (for whatever reason). What if you run librespot with `--bitrate=96`? Would it get past your tracks?

**Comment by peterdk** [comment]
I indeed am using 320kbps. I switched to 96kbps and it actually seems to solve the issue. It now progresses to the next track. Will test a bit more. Unfortunately it's not a solution since I want to keep using 320kbps, but definitely a hint to what is causing it.

**Comment by peterdk** [comment]
@michaelherger I added the mentioned track to my playlist, but at 320kbps there seems no issue with that specific track.

**Comment by michaelherger** [comment]
Correct: the user who reported the issue to me confirmed that it started working again after a few days.

**Comment by gddl** [comment]
I had a similar issue when booting up the (headless) RPi and when skipping songs too fast. The progress bar in the spotify app was moving but librespot just hung. Sometimes it took minutes to load the track and to start playing.
Then I noticed that the kernel ran out of entropy for the /dev/random RNG which is probably used by librespot for Diffie-Hellman key generation (reading from /dev/random blocks until enough entropy is available). I could solve the issue by installing _rng-tools_ and setting up _rngd_ (it uses RPi's HW-RNG to feed the kernel entropy pool).

**Comment by willstott101** [comment]
I believe this should be properly fixed since https://github.com/librespot-org/librespot/pull/381 as we noticed this issue more consistently with podcasts which often don't have high qualities available.

My solution was: https://github.com/librespot-org/librespot/pull/381/files#diff-f582d878256027ce3c970a26de626b55R544

**Comment by peterdk** [comment]
Great, I compiled and now it runs perfectly on those songs. Thanks for your work!
