### ISSUE TITLE
Could not compile `librespot-audio`

### ISSUE THREAD

**Issue by jtonk** [librespot-org/librespot#337]
I'm getting an error on latest version on an RPI, OSX and Ubuntu for Windows.
any idea why?

~/librespot $ cargo build --release

Compiling librespot-audio v0.1.0 (file:///opt/librespot/librespot/audio)
error[E0407]: method `source` is not a member of trait `error::Error`
  --> audio/src/lewton_decoder.rs:78:5
   |
78 | /     fn source(&self) -> Option<&(dyn error::Error + 'static)> {
79 | |         error::Error::source(&self.0)
80 | |     }
   | |_____^ not a member of trait `error::Error`

**Comment by bodiroga** [comment]
+1

**Comment by kingosticks** [comment]
The build instructions in the readme state that at least rust v1.30.0 is required.

**Comment by bodiroga** [comment]
Ouch, sorry, I have upgraded my rust and cargo version to 1.3.5 and now everything works correctly. Give it a try @jtonk and let us know :wink:

**Comment by kingosticks** [comment]
No worries, glad it's working for you now (I assume you meant v1.35.0). 

And if you still have problems @jtonk please provide more details (e.g. your version numbers).

**Comment by jtonk** [comment]
that resolved the issue on osx, couldn't test yet with other OS, but I think we can close this. Tnx!
