### ISSUE TITLE
Where does the reporting happen?

### ISSUE THREAD

**Issue by michaelherger** [librespot-org/librespot#342]
I've had a report of a user who happens to be an artist, too. He claims that when he's listening to his own music using my implementation of librespot, the tracks would not be reported. This is definitely not what I want to happen, therefore I'm a bit concerned. 

And I must admit I've been wondering why my kids' listening habits hadn't polluted my profile yet... (but I was less concerned about that :-D).

Is there code in librespot which actively does report when a track has been listened to? I was assuming that telling librespot to play a track would do all the magic for me.

I'm using a slightly modified fork of librespot (https://github.com/michaelherger/librespot), and I'm not sure whether one of my modifications is causing this mis-behavior or not.

**Comment by michaelherger** [comment]
Anyone?

**Comment by devgianlu** [comment]
How can we test whether the playback history is being recorded or not? I am willing to fix this issue for librespot-java, but I need a way to test it properly.

**Comment by michaelherger** [comment]
That's a good point and something I'll try to do: you can get the recently played tracks using the web API (the call is still beta... hopefully that won't confuse even more...).

https://developer.spotify.com/documentation/web-api/reference/player/get-recently-played/

**Comment by devgianlu** [comment]
@michaelherger I've checked and it seems that tracks played from librespot aren't reported by that endpoint. I will investigate this further.

**Comment by michaelherger** [comment]
Thanks for the confirmation!

**Comment by devgianlu** [comment]
Unluckily I don't see any specific call to report that a track is playing. I am afraid that it is done via the `event-service` endpoint which hasn't been reversed engineered at all. The only (mercury) packet that has the track uri in it is the following:

```
0078  # Changes every time, not incremental

5549496e746572616374696f6e # "UIInteraction"

0935  # Padding + "5"

0909  # Double padding
706c61796c697374  # "playlist"

09  # Padding
73706f746966793a6170703a706c61796c697374  # "spotify:app:playlist"

0909  # Double padding
32  # "2", could be track index in playlist

09  # Padding
73706f746966793a747261636b3a3367696379666945564d474f4e677a796770576a4e54  # Track uri

0909  # Double padding
6c6973742d6974656d2d73656c6563746564  # "list-item-selected"

09  # Padding
31353637303834303738323536  # Timestamp in millis
```

There's no reporting in the HTTP API either. I'll look at Android next.

**Comment by ashthespy** [comment]
@devgianlu There is also an `activity-manager` endpoint that I recall seeing, but didn't investigate further.

**Comment by devgianlu** [comment]
> @devgianlu There is also an `activity-manager` endpoint that I recall seeing, but didn't investigate further.

I did not see any of that. Maybe it has been deprecated when they upgraded the protocol.

**Comment by ashthespy** [comment]
This was from an older version indeed. I need to find my notes. 
Also might be of interest:
```
hm://played-state/v1/items
hm://played-state/v1/updates
hm://played-state/v1/unsubscribe
hm://played-state/v1/items?fromTimestamp=%Lu
```

**Comment by devgianlu** [comment]
I think that's for episodes only.

**Comment by ashthespy** [comment]
You are probably right again, its been a while I looked at this!

**Comment by caba8685** [comment]
Any updates on this?

**Comment by devgianlu** [comment]
We are stuck on trying to find a way to check if the changes on the client work.

**Comment by sashahilton00** [comment]
It’s probably handled via the events service. I’d be surprised if Spotify does the play reporting client side, would make it too easy to abuse

**Comment by ashthespy** [comment]
I was thinking about this some time back, and I guess they probably have metrics based on client type, and since we report `librespot` they could just not be propagating those metrics?

**Comment by devgianlu** [comment]
From the [get-recently-played](https://developer.spotify.com/documentation/web-api/reference/player/get-recently-played/) docs:
> Returns the most recent 50 tracks played by a user. Note that a track currently playing will not be visible in play history until it has completed. A track must be played for more than 30 seconds to be included in play history. Any tracks listened to while the user had “Private Session” enabled in their client will not be returned in the list of recently played tracks.

I can confirm that reporting doesn't work for `librespot-java`. When using the original client, as soon as the song ends, it appears in the list.

**Comment by michaelherger** [comment]
Could it be librespot downloading too fast, leaving Spotify to think we didn't listen to the track? (seems like an odd design, but who know?...)

FWIW: I've worked with many streaming services. Many of them would require you to manually report playback from the client's side. It's not uncommon.

**Comment by ashthespy** [comment]
> > Returns the most recent 50 tracks played by a user. Note that a track currently playing will not be visible in play history until it has completed. A track must be played for more than 30 seconds to be included in play history. Any tracks listened to while the user had “Private Session” enabled in their client will not be returned in the list of recently played tracks.

This duration seems to be passed to the client:
```xml
<ab_recently_played_feature_time_filter_threshold>
com.spotify.gaia=30,driving-mode=120,spotify%3Ainternal%3Astartpage=30
</ab_recently_played_feature_time_filter_threshold>
```

**Comment by devgianlu** [comment]
The following `hm://event-service/v1/events` seems interesting (number 15 in the attached dump):

`.Z372	1	01a5ba17d8411f92a5b6601e872da877	spotify:track:3mof6Z6vz6gonsuIEQXank	0	[[0,254896]]`

It has been sent once the track (`spotify:track:3mof6Z6vz6gonsuIEQXank`) finished. `[[0,254896]]` is the interval of the song that has been played in milliseconds. `01a5ba17d8411f92a5b6601e872da877` is probably the device id.

[reporting.zip](https://github.com/librespot-org/librespot/files/3892253/reporting.zip)

**Comment by devgianlu** [comment]
I am working on reverse engineering the `event-service` endpoint (https://github.com/librespot-org/librespot-java/pull/155). As always, I crawl for help.

**Comment by devgianlu** [comment]
More work has been done and I finally got it working. There is still some work to do as they don't pick up tracks that end because of pressing some button (aka works only with `trackdone`).

**Comment by devgianlu** [comment]
Just a quick question on the topic. Do you think it is better to send an event with some standard values that I didn't figure out or just not send it because it is not needed?

**Comment by Shinoby92** [comment]
its better to send them if they are generated to behave like a original client.
is something happened here?

**Comment by devgianlu** [comment]
> is something happened here?

What do you mean?

**Comment by Shinoby92** [comment]
does librespot now sends correctly the playing track to the endpoint? because it seems like that still hearing a song, does not appearing to the endpoint of the artist

**Comment by ashthespy** [comment]
No, only `librespot-java` does it..

**Comment by Shinoby92** [comment]
im using librespot-java and there is still something not working regarding that endpoint. listening to a song does not appear on the artist site as someone is listening. or does that not work, and it only work that a song without pressing any button like above mentioned (only via trackdone)
