### ISSUE TITLE
Spotify Connect repeats current playing track when new track selected

### ISSUE THREAD

**Issue by tonydevitt** [librespot-org/librespot#354]
Using librespot-0.1.1-1.fc25.x86_64, controlling from WIndows 8.1. When another track or album is selected and 'play' is clicked the current playing track restarts. The only way to change to new track is to 'Add to Queue' and then click 'play'.

**Comment by roderickvd** [comment]
Please test on the latest `librespot` and report back. I'm closing this for now because if this were wide-spread, then I think it would gather a _lot_ of issues.
