### ISSUE TITLE
unable to build due to broken dependency: rand 

### ISSUE THREAD

**Issue by zeraien** [librespot-org/librespot#355]
Commit: 1f75479170d71d82085510b2b6f34ce0756a0e8d

pi@retropie:~/librespot $ cargo build --release
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/tomaka/rodio`
    Updating git repository `https://github.com/plietar/rust-tremor`
    Updating git repository `https://github.com/plietar/rust-mdns`
    Updating git repository `https://github.com/plietar/dns-parser`

error: no matching package named `getrandom_package` found (required by `rand`)
location searched: registry https://github.com/rust-lang/crates.io-index
version required: ^0.1.1```

**Comment by hermann4** [comment]
Had the same issue,
do `rustup update` first, this should solve your problem

**Comment by zeraien** [comment]
My issue was that I was using the native `rustc` and `cargo` packages from the raspbian repo, rather than the manually installed rustup. When i installed rustup from the rustup page, the build went fine.
