### ISSUE TITLE
credentials.json is world-readable

### ISSUE THREAD

**Issue by sigvei** [librespot-org/librespot#360]
Librespot caches credentials in `$cache/credentials.json`. On my system (Arch Linux; using Librespot through spotifyd) the file seems to be created world- and group-readable (644).

The file stores an authentication token, not the password, so I guess this is not a very serious security issue. It should probably at least be mentioned in the docs that the cache dir should be kept secure (700). As it stands, users might (sensibly!) assign /tmp as a cache dir, which would expose the token to all users on the system.

**Comment by cip123** [comment]
I would like to start working on this one but I am completely new to Rust so I would like to ask  somebody opinion on the implementation.

I took a quick look at the code and the main problem that I see is the portability between Windows and Unix. 

i.e I could do something like this in `authentication.rs`
```    
        use std::os::unix::fs::OpenOptionsExt;

        let mut options = OpenOptions::new();
        options.write(true).create(true).truncate(true);
        
        if cfg!(unix) {
            options.mode(0o600);
        }
        
        let mut file = options.open(path.as_ref()).unwrap();
        self.save_to_writer(&mut file)
```
but the tricky part would be to conditionally compile `std::os::unix::fs::OpenOptionsEx`. 
My first thought is to separate the logic into different files with a trait or an interface  and then load that specific file conditionally with `#[cfg(target_os = "<unix|windows>")]`

**Comment by sashahilton00** [comment]
Added a note in the `README.md`
