### ISSUE TITLE
Pipe backend is gone?

### ISSUE THREAD

**Issue by mfeif** [librespot-org/librespot#364]
As of 1ce0706, Librespot doesn't seem to have a pipe backend, at least as compiled by default.

Am I missing something? Maybe it just doesn't need to be compiled, since it's so simple, but I can't find a way to choose it from the librespot command line (it ignores --backend pipe).

**Comment by kingosticks** [comment]
You can see what backends are available in your build:
```
./librespot --name foo --backend ?
```
As it happens, the pipe backend is not optional and always compiled. It certainly works for me:
```
./librespot --name foo --backend pipe
[2019-08-20T21:02:31Z INFO  librespot] librespot 1ce0706 (2019-08-19). Built on 2019-08-20. Build ID: EOMA2Vr0
```

**Comment by mfeif** [comment]
Thank you, I did try that, but I wasn't getting backends output; I must have had a typo in another command line switch.

I'll close this!

**Comment by kingosticks** [comment]
It is a bit weird because you do always have to specify the `--name` argument, even if you only want a list of backends. The error message does tell you but it's really easy to overlook.
