### ISSUE TITLE
onevent OPTION doesnt appear to start script

### ISSUE THREAD

**Issue by Tyfui90** [librespot-org/librespot#367]
**SUMMARY:**
I have been having issues with the --onevent triggering a script. Below is my current test steps to check if the script is even being ran, and it appears like it is not.

**ISSUE:**
--onevent is not running the scripts that are called in the raspotify file.

In my /etc/default/raspotify I have

    OPTIONS="--onevent /etc/default/bashScriptTest.sh"

with the 'bashScriptTest.sh' Script

    #!/bin/bash
    if [ "$PLAYER_EVENT" = "start" ]; then
      sudo touch /home/pi/start.py
    elif [ "$PLAYER_EVENT" = "stop" ]; then
      sudo touch /home/pi/stop.py
    else
      sudo touch /home/pi/eelse.py
    fi

The file has chmod 775, and creates the 'eelse.py' file when ran from command line with

    sudo ./etc/default/bashScriptTest.sh

But when I start spotify connect to the Pi this script doesnt start as evidenced by no dummy file being created.

Is this a defect, or am I misunderstanding how --onevent is supposed to trigger?

**Comment by Tyfui90** [comment]
The file permissions are ok when im running as user pi. But after checking logs using

    journalctl --system _SYSTEMD_UNIT=raspotify.service

Im finding that when the raspotify service is running the script it doesnt have the permission to access

    Sep 15 18:42:24 raspberrypi librespot[9607]: INFO:librespot::player_event_handler: Running [/etc/default/bashScriptTest.sh"] with environment variables {"PLAYER_EVENT": "start", "TRACK_ID": "xxxxxxxxxxxxxxx"}

    Sep 15 18:42:24 raspberrypi librespot[9607]: We trust you have received the usual lecture from the local System
    Sep 15 18:42:24 raspberrypi librespot[9607]: Administrator. It usually boils down to these three things:
    Sep 15 18:42:24 raspberrypi librespot[9607]:     #1) Respect the privacy of others.
    Sep 15 18:42:24 raspberrypi librespot[9607]:     #2) Think before you type.
    Sep 15 18:42:24 raspberrypi librespot[9607]:     #3) With great power comes great responsibility.
    Sep 15 18:42:24 raspberrypi librespot[9607]: sudo: no tty present and no askpass program specified
    Sep 15 18:42:24 raspberrypi librespot[9607]: sudo: no tty present and no askpass program specified
    Sep 15 18:42:24 raspberrypi sudo[9621]: pam_unix(sudo:auth): conversation failed
    Sep 15 18:42:24 raspberrypi sudo[9621]: pam_unix(sudo:auth): auth could not identify password for [raspotify]
    Sep 15 18:42:24 raspberrypi sudo[9621]: raspotify : user NOT in sudoers ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/touch /home/pi/start.py

This means that this issue isnt an issue, but is in fact user error. I'll close this ticket

**Comment by HippieWithGuns** [comment]
could you help me understand what your issue was? i'm having the exact same problem as you, execpt that entering 
`journalctl --system _SYSTEMD_UNIT=raspotify.service`
is not returning an error, nor does the follwing command:
`tail -f  /var/log/daemon.log`
using this command i can execute my script with the raspotify user to eliminate the user rights problem, but somehow my raspotify does not trigger the onevent command for me
`sudo /usr/local/scripts/oneevent.sh -s /bin/sh raspotify`
please help kind stranger :)

**Comment by herrwusel** [comment]
> I'm having the exact same problem as you, execpt that entering ...

I think you might have a different problem. Maybe share your raspotify config.
```
Sep 15 18:42:24 raspberrypi sudo[9621]: raspotify : user NOT in sudoers ; TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/touch /home/pi/start.py
```
This line is explaining it: the script tries to run a `sudo` command but the user isn't allowed to. This is why OP's onevent wasn't working.

**Comment by HippieWithGuns** [comment]
thank you for taking the time to reply and look into this, i'll gladly include my raspotify config:
`# /etc/default/raspotify -- Arguments/configuration for librespot

# Device name on Spotify Connect
#DEVICE_NAME="spotipi"

# Bitrate, one of 96 (low quality), 160 (default quality), or 320 (high quality)
#BITRATE="320"

# Additional command line arguments for librespot can be set below.
# See `librespot -h` for more info. Make sure whatever arguments you specify
# aren't already covered by other variables in this file. (See the daemon's
# config at `/lib/systemd/system/raspotify.service` for more technical details.)
#
# To make your device visible on Spotify Connect across the Internet add your
# username and password which can be set via "Set device password", on your
# account settings, use `--username` and `--password`.
#
# To choose a different output device (ie a USB audio dongle or HDMI audio out),
# use `--device` with something like `--device hw:0,1`. Your mileage may vary.
#
#OPTIONS="--username tschäppelers --password 123456 --onevent /usr/local/scripts/oneevent.sh"

# Uncomment to use a cache for downloaded audio files. Cache is disabled by
# default. It's best to leave this as-is if you want to use it, since
# permissions are properly set on the directory `/var/cache/raspotify'.
#CACHE_ARGS="--cache /var/cache/raspotify"

# By default, the volume normalization is enabled, add alternative volume
# arguments here if you'd like, but these should be fine.
#VOLUME_ARGS="--enable-volume-normalisation --linear-volume --initial-volume=100"

# Backend could be set to pipe here, but it's for very advanced use cases of
# librespot, so you shouldn't need to change this under normal circumstances.
#BACKEND_ARGS="--backend alsa"`

let me know if another file would be of help
thanks again in advance

**Comment by herrwusel** [comment]
Can you post the journalctl from when the script should be launched and the script as well?

**Comment by HippieWithGuns** [comment]
Here is the log from `journalctl --system _SYSTEMD_UNIT=raspotify.service`
```
-- Logs begin at Sun 2020-03-08 19:54:59 CET, end at Sun 2020-03-08 19:57:16 CET. --
Mar 08 19:55:29 raspberrypi librespot[341]: [2020-03-08T18:55:29Z INFO  librespot] librespot (raspotify v0.14.0) 3672214 (2020-01-30). Built on 2020-02-16. Build ID: 7pZDd
Mar 08 19:55:31 raspberrypi librespot[341]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 19, kind: Other, message: "No such device" }
Mar 08 19:55:31 raspberrypi librespot[341]: stack backtrace:
Mar 08 19:55:34 raspberrypi librespot[341]:    0:   0x93e3a4 - backtrace::backtrace::libunwind::trace::hb1e9954dcc6e7c1f
Mar 08 19:55:34 raspberrypi librespot[341]:                        at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
Mar 08 19:55:34 raspberrypi librespot[341]:    1:   0x93e3a4 - backtrace::backtrace::trace_unsynchronized::h1b198a73034a9734
Mar 08 19:55:34 raspberrypi librespot[341]:                        at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
Mar 08 19:55:34 raspberrypi librespot[341]:    2:   0x93e3a4 - std::sys_common::backtrace::_print_fmt::hf691518b63d0b79d
Mar 08 19:55:34 raspberrypi librespot[341]:                        at src/libstd/sys_common/backtrace.rs:84
Mar 08 19:55:34 raspberrypi librespot[341]:    3:   0x93e3a4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he6a16924c7e1913e
Mar 08 19:55:34 raspberrypi librespot[341]:                        at src/libstd/sys_common/backtrace.rs:61
Mar 08 19:55:35 raspberrypi librespot[341]:    4:   0x960ca4 - core::fmt::write::hc426988e4c4119a8
Mar 08 19:55:35 raspberrypi librespot[341]:                        at src/libcore/fmt/mod.rs:1025
Mar 08 19:55:35 raspberrypi librespot[341]:    5:   0x938ff0 - std::io::Write::write_fmt::h34e90dde595ba7cd
Mar 08 19:55:35 raspberrypi librespot[341]:                        at src/libstd/io/mod.rs:1426
Mar 08 19:55:35 raspberrypi librespot[341]:    6:   0x940954 - std::sys_common::backtrace::_print::h406863a8800396cd
Mar 08 19:55:35 raspberrypi librespot[341]:                        at src/libstd/sys_common/backtrace.rs:65
Mar 08 19:55:35 raspberrypi librespot[341]:    7:   0x940954 - std::sys_common::backtrace::print::hec570bc9fdd6a536
Mar 08 19:55:35 raspberrypi librespot[341]:                        at src/libstd/sys_common/backtrace.rs:50
Mar 08 19:55:35 raspberrypi librespot[341]:    8:   0x940954 - std::panicking::default_hook::{{closure}}::hf187be78db8e291b
Mar 08 19:55:35 raspberrypi librespot[341]:                        at src/libstd/panicking.rs:193
Mar 08 19:55:35 raspberrypi librespot[341]:    9:   0x9405b4 - std::panicking::default_hook::h9634e45fc0d61ba6
Mar 08 19:55:35 raspberrypi librespot[341]:                        at src/libstd/panicking.rs:210
Mar 08 19:55:35 raspberrypi librespot[341]:   10:   0x941030 - std::panicking::rust_panic_with_hook::h35923fdea5783220
Mar 08 19:55:35 raspberrypi librespot[341]:                        at src/libstd/panicking.rs:471
Mar 08 19:55:35 raspberrypi librespot[341]:   11:   0x940c48 - rust_begin_unwind
Mar 08 19:55:35 raspberrypi librespot[341]:                        at src/libstd/panicking.rs:375
Mar 08 19:55:35 raspberrypi librespot[341]:   12:   0x95cac0 - core::panicking::panic_fmt::hd74e307162bc16e5
Mar 08 19:55:35 raspberrypi librespot[341]:                        at src/libcore/panicking.rs:84
Mar 08 19:55:35 raspberrypi librespot[341]:   13:   0x95cbac - core::result::unwrap_failed::h36f73057b442c0eb
Mar 08 19:55:35 raspberrypi librespot[341]:                        at src/libcore/result.rs:1188
Mar 08 19:55:35 raspberrypi librespot[341]:   14:   0x4785e0 - librespot::main::h0ed06a728ac2479f
Mar 08 19:55:35 raspberrypi librespot[341]:   15:   0x479980 - std::rt::lang_start::{{closure}}::h3ecc962e3fb4564b
Mar 08 19:55:35 raspberrypi librespot[341]:   16:   0x940ac4 - std::rt::lang_start_internal::{{closure}}::hc02935a73664ebd0
Mar 08 19:55:35 raspberrypi librespot[341]:                        at src/libstd/rt.rs:52
Mar 08 19:55:35 raspberrypi librespot[341]:   17:   0x940ac4 - std::panicking::try::do_call::h9ca5184b6b3cc62d
Mar 08 19:55:35 raspberrypi librespot[341]:                        at src/libstd/panicking.rs:292
Mar 08 19:55:35 raspberrypi librespot[341]:   18:   0x948220 - __rust_maybe_catch_panic
Mar 08 19:55:35 raspberrypi librespot[341]:                        at src/libpanic_unwind/lib.rs:78
Mar 08 19:55:35 raspberrypi librespot[341]:   19:   0x941484 - std::panicking::try::hc53e4a11b02f3299
Mar 08 19:55:35 raspberrypi librespot[341]:                        at src/libstd/panicking.rs:270
Mar 08 19:55:35 raspberrypi librespot[341]:   20:   0x941484 - std::panic::catch_unwind::ha972c7f8a413a94c
Mar 08 19:55:35 raspberrypi librespot[341]:                        at src/libstd/panic.rs:394
Mar 08 19:55:35 raspberrypi librespot[341]:   21:   0x941484 - std::rt::lang_start_internal::hdf6cc497202d2594
Mar 08 19:55:35 raspberrypi librespot[341]:                        at src/libstd/rt.rs:51
Mar 08 19:55:35 raspberrypi librespot[341]:   22:   0x478dc4 - main
Mar 08 19:55:35 raspberrypi librespot[341]:   23: 0xb6cdd718 - __libc_start_main
Mar 08 19:55:46 raspberrypi librespot[568]: [2020-03-08T18:55:46Z INFO  librespot] librespot (raspotify v0.14.0) 3672214 (2020-01-30). Built on 2020-02-16. Build ID: 7pZDd
Mar 08 19:57:14 raspberrypi librespot[568]: [2020-03-08T18:57:14Z INFO  librespot_core::session] Connecting to AP "gew1-accesspoint-b-1zzl.ap.spotify.com:4070"
Mar 08 19:57:15 raspberrypi librespot[568]: [2020-03-08T18:57:15Z INFO  librespot_core::session] Authenticated as "tschäppelers" !
Mar 08 19:57:15 raspberrypi librespot[568]: [2020-03-08T18:57:15Z INFO  librespot_playback::audio_backend::alsa] Using alsa sink
Mar 08 19:57:15 raspberrypi librespot[568]: [2020-03-08T18:57:15Z INFO  librespot_core::session] Country: "CH"
Mar 08 19:57:15 raspberrypi librespot[568]: [2020-03-08T18:57:15Z INFO  librespot_playback::player] Loading <Outta My Mind> with Spotify URI <spotify:track:4Zse2ewCiDdoBwe
lines 1-54 
```

my script file looks like the following:
```
#!/bin/bash
echo 'on 0' | cec-client -s -d 1
echo 'on 5' | cec-client -s -d 1
echo 'as' | cec-client -s -d 1
```
