### ISSUE TITLE
Updating url dependency

### ISSUE THREAD

**Issue by SirWindfield** [librespot-org/librespot#368]
Hey everyone!

Is there a particular reason why you guys stick to the 1.7.x versions of the `url` crate? I am using `librespot` in a project where I need to use the new 2.x version as the project uses serde 1.x.

If not, I would gladly create a PR to update the dependencies! :)

**Comment by ashthespy** [comment]
No particular reason, I am running 2.x for a while now with no issues (https://github.com/ashthespy/librespot/commit/0f959ce12eb93335176fdacb981525c34c4a5ea6)

**Comment by sashahilton00** [comment]
Feel free to upgrade to url `2.2` @SirWindfield if you need it, or any other dependencies for that matter.
