### ISSUE TITLE
Invisible after using with another account

### ISSUE THREAD

**Issue by hige-agusd** [librespot-org/librespot#372]
So the raspotify device can be discovered on any Device in my LAN, just like it should. If Account 1 plays Music, it disappears. Still fine. But if Account 1 disconnects from the raspotify by switching the playback device back to smartphone or what else, the raspotify keeps beeing visible only to devices logged in to account 1. Devices with other accounts can't see the raspotify and restarting the service doesn't seem to fix the issue

**Comment by linibou** [comment]
Same issue for me

**Comment by faabmaster** [comment]
Also affected by this. It's advertised that the device can be discovered on the same network, but I can only seem to connect to it when logged in to my account that I set Librespot up with.

**Comment by illtrick** [comment]
I hit this same issue with the Volumio plugin and posted my logs [here ](https://github.com/balbuze/volumio-plugins/issues/259)  No attention there yet either but I thought it might help whomever might be troubleshooting.

Oddly I do not have this issue at all with Ropieee XL, it handles multiple accounts flawlessly.

**Comment by roderickvd** [comment]
Fixed downstream in https://github.com/balbuze/volumio-plugins/issues/259.
If this still occurs in the latest `librespot` (and not just Volumio) then feel free to re-open.
