### ISSUE TITLE
Software Volume control vs hardware (alsa control)

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#38]
<a href="https://github.com/jsarcand"><img src="https://avatars0.githubusercontent.com/u/5246468?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jsarcand](https://github.com/jsarcand)**
_Thursday Nov 17, 2016 at 15:15 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/128_

----

Hey there! It seems like the volume control is modulating the sound amplitude of the songs in software instead of modifying the values of the sound card through ALSA.  Any thoughts on that?  Thanks for that amazing piece of software!! :+1:

**Comment by sashahilton00** [comment]
<a href="https://github.com/joerg-krause"><img src="https://avatars2.githubusercontent.com/u/6870896?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joerg-krause](https://github.com/joerg-krause)**
_Friday Nov 18, 2016 at 01:07 GMT_

----

This part is still missing. Have a look at my fork for a naive approach: https://github.com/joerg-krause/librespot/commit/9af911803eb2ceaf617c9ebb47e98d62f81e2d55.

**Comment by sashahilton00** [comment]
<a href="https://github.com/jsarcand"><img src="https://avatars0.githubusercontent.com/u/5246468?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jsarcand](https://github.com/jsarcand)**
_Sunday Nov 20, 2016 at 00:33 GMT_

----

I will, thanks!

**Comment by ComlOnline** [comment]
Please see #39 For more on this issue.
