### ISSUE TITLE
Travis builds timing out

### ISSUE THREAD

**Issue by ashthespy** [librespot-org/librespot#382]
Off late, most Travis builds seem to hang at: 
```
adding /home/travis/.cache/sccache to cache
creating directory /home/travis/.cache/sccache
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
```
The linked [FAQ](https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received) seems quite generic. Anyone with more Travis experience?

**Comment by devgianlu** [comment]
Have a look at [this](https://travis-ci.community/t/builds-timeout-during-or-shortly-after-creating-directory-home-travis-cache-sccache/5001).

**Comment by ashthespy** [comment]
Ah, Google pointed me to that as well, deleted the cache, and [Job # 578.1](https://travis-ci.org/librespot-org/librespot/jobs/595235726) seems to be building.
