### ISSUE TITLE
Docker build fails at alsa-sys crate on arm-unknown-linux-gnueabihf

### ISSUE THREAD

**Issue by tenortim** [librespot-org/librespot#389]
The alsa-sys crate seems to need to run pkg-config (missing from the Dockerfile) and pkg-config isn't architecture aware, so the contrib/docker-build.sh that tries to build five different architectures doesn't work correctly any longer.

I have a fairly simple patch. Will fork and send a PR, but will attach the diff here since it's pretty simple.

**Comment by tenortim** [comment]
Proposed fix:
```
ubuntu-server:contrib$ git diff
diff --git a/contrib/Dockerfile b/contrib/Dockerfile
index 0fcdaff..3a18589 100644
--- a/contrib/Dockerfile
+++ b/contrib/Dockerfile
@@ -22,6 +22,7 @@ RUN dpkg --add-architecture mipsel
 RUN apt-get update

 RUN apt-get install -y curl git build-essential crossbuild-essential-arm64 crossbuild-essential-armel crossbuild-essential-armhf crossbuild-essential-mipsel
+RUN apt-get install -y pkg-config
 RUN apt-get install -y libasound2-dev libasound2-dev:arm64 libasound2-dev:armel libasound2-dev:armhf libasound2-dev:mipsel

 RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
@@ -43,6 +44,7 @@ RUN mkdir /build && \

 ENV CARGO_TARGET_DIR /build
 ENV CARGO_HOME /build/cache
+ENV PKG_CONFIG_ALLOW_CROSS=1

 ADD . /src
 WORKDIR /src
diff --git a/contrib/docker-build.sh b/contrib/docker-build.sh
index cd5ef46..301e8d6 100755
--- a/contrib/docker-build.sh
+++ b/contrib/docker-build.sh
@@ -2,7 +2,11 @@
 set -eux

 cargo build --release --no-default-features --features alsa-backend
+export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
 cargo build --release --target aarch64-unknown-linux-gnu --no-default-features --features alsa-backend
+export PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig
 cargo build --release --target arm-unknown-linux-gnueabihf --no-default-features --features alsa-backend
+export PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabi/pkgconfig
 cargo build --release --target arm-unknown-linux-gnueabi --no-default-features --features alsa-backend
+export PKG_CONFIG_PATH=/usr/lib/mipsel-linux-gnu/pkgconfig
 cargo build --release --target mipsel-unknown-linux-gnu --no-default-features --features alsa-backend
```

**Comment by ashthespy** [comment]
Sorry, this was me - https://github.com/librespot-org/librespot/pull/245#issuecomment-430247445
I never pushed the fix, will do it now.

**Comment by tenortim** [comment]
Hi @ashthespy,
I think you still need the docker-build.sh changes too. Otherwise the build fails because pkg-config isn't architecture-aware and the arm-linux-gnueabihf build fails at the link stage. Do you want to add that separately, or should I generate a new PR?

**Comment by ashthespy** [comment]
@tenortim I didn't have all the changes in this commit, need to keep better track of all my branches! 
Added a new commit that sets the individual `PKG_CONFIG_PATH` for each triple.

**Comment by ashthespy** [comment]
From my quick experiments, `crossbuild-essential-arm64` and `crossbuild-essential-mipsel` seem to work fine, however, both `crossbuild-essential-armel` and `crossbuild-essential-armhf` need some help.   That being said, there *shouldn't* be much harm setting the right [environment variables](https://github.com/rust-lang/pkg-config-rs#external-configuration-via-target-scoped-environment-variables) for each target triple.
