### ISSUE TITLE
librespot does not release the device

### ISSUE THREAD

**Issue by dubo-dubon-duponey** [librespot-org/librespot#398]
I'm running different receivers for different protocols on a single node:
 * RAAT (using [Roon Bridge](https://kb.roonlabs.com/RoonBridge)) (best for Roon)
 * Airport (using [shairport-sync](https://github.com/mikebrady/shairport-sync)) (best when using a mac for random stuff)

And I would love to be able to run librespot as well (best for Spotify with portability in mind).

Both RAAT and Airport will acquire/release the device *when they need to play sound*, and play nice with each other.

Librespot on the other hand tries to lock the device at startup, and will NOT release it unless stopped.
Unfortunately, this makes it not practical to run librespot alongside other stacks sharing /dev/snd.

I'm not familiar with the low level details here, neither with librespot implementation. Is the problem I'm describing specific to rodio?

Or am I missing something?

Thanks for librespot either way!

**Comment by kingosticks** [comment]
Yes, it is specific to rodio. The ALSA backend does not behave this way (see #68).

**Comment by dubo-dubon-duponey** [comment]
\o/

Compiling now.

THANKS!

**Comment by dubo-dubon-duponey** [comment]
Confirmed working ok with alsa backend.
Thanks again!
