### ISSUE TITLE
Can not compile on Arch Linux with pulseaudio backend.

### ISSUE THREAD

**Issue by MrKinauJr** [librespot-org/librespot#399]
Hello i have a problem compiling librespot with pulseaudio backend.

Errorlog:
Compiling unreachable v1.0.0
   Compiling base64 v0.5.2
   Compiling shannon v0.2.0
error[E0503]: cannot use state because it was mutably borrowed
    --> /home/kinau/.cargo/registry/src/github.com-1ecc6299db9ec823/getopts-0.2.14/src/lib.rs:1008:33
     |
955  |     let mut machine = |cont: &mut bool, (i, c): (usize, char)| {
     |                       ---------------------------------------- borrow of state occurs here
...
959  |         state = match (state, whitespace, limit) {
     |                        ----- borrow occurs due to use of state in closure
...
1008 |     while cont && match state { B | C => true, A => false } {
     |                                 ^ use of borrowed state
1009 |         machine(&mut cont, (fake_i, ' '));
     |         ------- borrow later used here

error: aborting due to previous error

For more information about this error, try rustc --explain E0503.
error: could not compile getopts.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by ashthespy** [comment]
What version of Rust are you on?

**Comment by MrKinauJr** [comment]
I am on rustc 1.39.0 (4560ea788 2019-11-04)

**Comment by ashthespy** [comment]
Not sure why you have such an old version of `getopts` though - 0.2.14 is from 2015. Current `Cargo.lock` uses `0.2.19`.

**Comment by MrKinauJr** [comment]
idk too. i just git cloned it. After that downloaded cargo via pacman -S cargo rustup and then tried to compile it.

**Comment by ashthespy** [comment]
We [recommend](https://github.com/librespot-org/librespot/wiki/Compiling#rust) using rustup directly,  from https://rustup.rs/. 
You normally don't need to install cargo separately, as its bundled with rustup

**Comment by MrKinauJr** [comment]
yeah idk anything about rust. I just want to use it cause its headless so i can do some stuff with it via remote control and the spotify api.

**Comment by MrKinauJr** [comment]
well sorry. had the wrong librespot repo D; this is the reason. sorry im a idiot xD

**Comment by MrKinauJr** [comment]
fuck it. new error. compiled with `cargo build --release --features pulseaudio-backend`.

cant use the pulseaudio backend tho.
`
[2019-11-10T19:18:15Z INFO  librespot] librespot  (). Built on 2019-11-09. Build ID: BGt9RQk2
Available Backends : 
- portaudio (default)
- rodio
- pipe

`

**Comment by ashthespy** [comment]
You still have the wrong repo - `portaudio` hasn't been default for quite a while now.. Check out the wiki on compilation.

**Comment by MrKinauJr** [comment]
oh fuck im just a idiot. sorry never compiled something with rust. I thought it will get install instantly. but i needed to get the binary. Well sorry D; but thanks for pointing that out.
