### ISSUE TITLE
Stop pulseaudio sink when not in use

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#40]
<a href="https://github.com/ipha"><img src="https://avatars3.githubusercontent.com/u/924797?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ipha](https://github.com/ipha)**
_Saturday Jan 14, 2017 at 21:26 GMT_
_Originally opened as https://github.com/plietar/librespot/pull/146_

----

I've implemented the open() and close() functions so that the sink will be closed when notin use.

This is my first time working with rust, so I'm not 100% sure I'm handling the pointers correctly.

----

_**[ipha](https://github.com/ipha)** included the following code: https://github.com/plietar/librespot/pull/146/commits_

**Comment by sashahilton00** [comment]
<a href="https://github.com/ComlOnline"><img src="https://avatars1.githubusercontent.com/u/25977690?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ComlOnline](https://github.com/ComlOnline)**
_Monday Jan 29, 2018 at 00:58 GMT_

----

Hey @ipha, Just so you know this was implemented here librespot-org/librespot#1

**Comment by ComlOnline** [comment]
As above.
