### ISSUE TITLE
onevent / onstart alternative behaviour

### ISSUE THREAD

**Issue by hifiberry** [librespot-org/librespot#406]
I need to run a script before music playback is started. While "onvent" seems to be the correct option for this, the problem is that it is started in background. This causes the playback to start before the script has been finished. I need librespot to wait until the script has been finished.
It would be good to have some "synchronous" option for onevent or at least for the "start" event.

**Comment by ashthespy** [comment]
@hifiberry I managed to including the Sink events, but its on a different branch. I will get my computer and dig it out in a few hours. 
Out of curiosity, what does the script have to do?

**Comment by hifiberry** [comment]
It stops other players that have exclusive access to the sound card.

**Comment by ashthespy** [comment]
Had the same issue for Volumio, so check out of if my version modified - [Vollibrespot](https://github.com/ashthespy/Vollibrespot) works for you. It exposes a udp socket that reports these events.
