### ISSUE TITLE
armhf build not working / connecting

### ISSUE THREAD

**Issue by praul** [librespot-org/librespot#408]
Hi there, 
I've tried to build librespot via the docker image for armhf with various flags.
None of the builds are working. Librespot does not connect and stops at
`2019-12-07T08:31:54Z INFO  librespot] librespot f67a38d (2019-12-03). Built on 2019-12-04. Build ID: d6Ol89kL
[2019-12-07T08:31:54Z DEBUG librespot_connect::discovery] Zeroconf server listening on 0.0.0.0:42450
`
I want to use pipe backend (for snapcast) and user/password authentication

> ./librespot -n testname -u email@mail.com -p secretpass --disable-audio-cache -v --backend "pipe" --device /tmp/snapfifo &

Also: librespot does not respond to ctrl+c at that point

Any help?
Amd64 build is connecting and works as it should. Likewise the java version of librespot - but I would prefer the native build.

**Comment by ashthespy** [comment]
@praul Did you ever figure out what was going on?
