### ISSUE TITLE
expire cached audio files

### ISSUE THREAD

**Issue by azrdev** [librespot-org/librespot#412]
As I read `dev/core/src/cache.rs` it seems the `cache_path` is filled with audio files and read from, but never expired, so eventually the disk will run full.
I can manually expire old cache entries that have not been used in a time, e.g. with a daily cronjob running `find $CACHE_DIR -type f -atime +30 -delete`, but maybe you consider pruning the cache in scope?

**Comment by sashahilton00** [comment]
I seem to remember there was an older issue that looked at this. There were some nuances involved, though I can't find it right now. Will look again later and try to link to it.
