### ISSUE TITLE
Active Device

### ISSUE THREAD

**Issue by devsquaaa** [librespot-org/librespot#414]
Hello, 
I was wondering if there was a way to start the client/player as an "active" device (according to [this api](https://developer.spotify.com/documentation/web-api/reference/player/get-a-users-available-devices/)), directly from the runtime options, because I haven't found any programmatical way (the only other way is to run librespot, then use the officiel client/online client to make a music play from this device, using Spotify Connect).
If this option isn't available I'd be glad if it could be added :)

**Comment by michaelherger** [comment]
There are API calls to transfer playback from whatever it is on to your librespot device (https://developer.spotify.com/documentation/web-api/reference/player/transfer-a-users-playback/) as well as starting/resuming playback if it was already there (https://developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback/)

**Comment by bluepuma77** [comment]
In the examples there seems to be a [demo](https://github.com/librespot-org/librespot/blob/dev/examples/play.rs) how to trigger Spotify playback.
