### ISSUE TITLE
librespot with Spotify Free accounts (server sided limitation?)

### ISSUE THREAD

**Issue by Seegee** [librespot-org/librespot#415]
Hi guys,

I've read over issue #261, and from what I understand, the 'premium account' restriction is in librespot to comply with Spotify's TOS. 

Is it technically possible to stream songs on a free account using the same approach as librespot, or is this a server side limitation by Spotify? I ask because I'd like to use librespot as a base to make a custom player for an embedded device that supports free accounts. Ideally, I'd be able to integrate ad breaks, skip limits, and everything else needed to comply with Spotify free. I just want to know if librespot is a good starting point for me, or if whatever APIs it utilizes are limited by Spotify to only premium accounts.

**Comment by sashahilton00** [comment]
Technically it's possible. There are no server side limitations that I know of, and @plietar mentioned that there is a minor change that can be made to the current code to support free accounts. I haven't done enough reverse engineering to work out what that is though, nor has anyone looked at reversing the limited plays/adverts/metrics/etc. functionality that would also need to be implemented as far as I know. Nothing stopping you though if you want to add support for free accounts from a technical standpoint.

**Comment by coxackie** [comment]
I am curious as to why this is open. Is there actually any prospect to free accounts being supported? I would happy if yes, and also understand if you do not want to do this, in order not to piss off spotify. Howevern, in the latter case should you not close this issue?
