### ISSUE TITLE
Usage Ask: build a stream for foobar2k

### ISSUE THREAD

**Issue by kmahyyg** [librespot-org/librespot#419]
I'm gonna ask for some details and about its legality:

- Firstly, it's just used by myself and will NOT share to public, I have a premium account and just gonna use this repo to build a stream to pass to stream and try to play it via foobar2k.
- Which output should I select? mixer? pcm? or something else?
- Is this operation considered as piracy?

If possible, could you please give me some suggestion of implementation? Thank you.

**Comment by devgianlu** [comment]
As long as you use it for yourself it's fine
