### ISSUE TITLE
Spotify track symlinks not resolved

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#42]
<a href="https://github.com/XDjackieXD"><img src="https://avatars1.githubusercontent.com/u/4963868?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [XDjackieXD](https://github.com/XDjackieXD)**
_Wednesday Feb 08, 2017 at 22:10 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/153_

----

Some songs in Spotify "symlink" to the actual song and therefore can't be played by librespot.
This does not happen when using spirc as the spotify client already resolves these links.
When supplying the URI directly, librespot panics.
One of those songs is spotify:track:4mu8svGkGaO2dgAcTlo0FK but there are many more.

**Comment by sashahilton00** [comment]
<a href="https://github.com/plietar"><img src="https://avatars0.githubusercontent.com/u/1489775?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [plietar](https://github.com/plietar)**
_Thursday Feb 09, 2017 at 00:55 GMT_

----

What are you using to load the track ?
Some tracks have restrictions which prevent them from being played in certain countries. They however have a list of "alternatives" which can be used instead.

The player includes support for this. If the track is not available, it will use an alternative instead. This is implemented as the `find_available_alternative ` function: https://github.com/plietar/librespot/blob/master/src/player.rs#L165-L191

The track you've listed as an example loads just fine in the player for me (even when bypassing spirc). If you are not using the provided `Player` but are downloading and decrypting the file manually, you may need a similar logic to find the right file.

**Comment by sashahilton00** [comment]
<a href="https://github.com/XDjackieXD"><img src="https://avatars1.githubusercontent.com/u/4963868?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [XDjackieXD](https://github.com/XDjackieXD)**
_Thursday Feb 09, 2017 at 07:32 GMT_

----

I did not remove the find alternative from the player and I'm just bypassing spirc (getting the spotify IDs from a FiFo file).
This track plays fine on the normal spotify client and it plays fine when using spirc. When printing out the spotify id thta is getting sent by spirc, it correspomds to the same song inside an other album.

**Comment by ComlOnline** [comment]
@XDjackieXD Did you ever solve this problem?

**Comment by XDjackieXD** [comment]
I didn't solve it but it seems like it was fixed in recent librespot versions (at least I didn't encounter it anymore after updating the librespot version I based my project upon)

**Comment by ComlOnline** [comment]
Thats good news! Just open a new issue if you come across it again.
