### ISSUE TITLE
Move Travis CI over to Github Actions

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#428]
I'm not too familiar with Github Actions, but from what I've seen, it's basically Travis but built into Github. We should move across to that when we get a chance as it's more streamlined & removes the dependency on a 3rd party platform. If someone is familiar with the Github Action markdown and wants to rewrite the `.travis.yml`, it would be much appreciated, otherwise I'll give it a go when I get some time to read up on it.

**Comment by SirWindfield** [comment]
I can tackle this down. We completely moved to GA over at https://github.com/Spotifyd/spotifyd.

**Comment by sashahilton00** [comment]
Would be great if you could. I'm also busy until at least mid February. Also, not sure if it's the reason spotifyd isn't on crates.io yet, but librespot is now published, so it should be possible to publish spotifyd if desired.

**Comment by SirWindfield** [comment]
Yes, it was the reason. We did publish our latest two versions on [crates.io](https://crates.io/crates/spotifyd) :)

**Comment by sashahilton00** [comment]
ah right, I'm blind

**Comment by SirWindfield** [comment]
Oh, btw: Is there some tracking issue for the work to split librespot into a library and a daemon? I couldn't really find a branch that you guys started nor an issue for it

**Comment by sashahilton00** [comment]
I was just thinking about that funnily enough. There is one I believe, though I'll have to search for it a bit (currently out of office). As it currently stands, the work to separate out the library/application aspect is mostly done - the individual packages are listed on crates.io and ready to use. There is a separate repo ([librespotd](https://github.com/librespot-org/librespotd)) that is intended for the daemon, but no work has begun on it yet. What will likely happen is the application part of librespot will be moved across to that repo in due course, with the intent of this repo being primarily a library, perhaps with a barebones application that just contains the basic features. 

I believe we discussed this either on Gitter or in an issue briefly, but there is likely to be significant overlap between spotifyd and librespotd in terms of functionality, so it might be worth looking into combining efforts into one or the other.

**Comment by SirWindfield** [comment]
Ye, we briefly discussed it in the "looking for maintainer" issue. Maybe I'm remembering stuff wrong but I thought the idea was to split the audio backend into a daemon and let the library be a pure implementation of the protocol without all the audio implementations. Applications would then use the library to receive and send PCM data to the daemon.

~I might just mix up stuff at this point though.~

> Based on the past x years of maintaining librespot, a chunk of the issues have been at the audio output level, ie. pulseaudio et al(sa), which have required multiple patches which added nothing to the core functionality of the program. The plan was to split librespot and librespotd, with the latter being a daemon that ran at system boot or similar, and dealt with the audio output bloat, along with the bells and whistles features, eg. zeroconf, websockets api for control, etc. librespot would then be the core library, with the aim of being as stable as possible, whose job it was to handle interaction with spotify servers and return data and pcm. If this were to be done, the benefits of a wrapper for various languages are negligible, as it would be simpler to just control via something like a unix sockets or websocket api, whilst also avoiding detracting from development time to maintain wrappers.

`spotifyd` does provide some other stuff as well though like password manager support and media key support using OS specific protocols. Not sure if that is stuff that might want to go into librespot itself. I'm generally in favour of merging as I think that would greatly benefit both projects. A lot of stuff is moving right now inside of the Rust ecosystem, especially the whole async/await and futures 0.3 related stuff, which probably needs larger code changes anyway.

**Comment by sashahilton00** [comment]
Apologies, I should have been clear. The basic features would have essentially been the pipe output. W.r.t what goes into librespotd, I think the general consensus was that all the various bells and whistles go into librespotd. That would include things like password manager support and media keys, websocket servers and audio backends. Given how easy it is to use feature flags in rust, so long as we use them for the various bells and whistles, people can just compile in the functionality that they want.

**Comment by SirWindfield** [comment]
Ah, so the library would then, for example, fetch PCM data from Spotify and pipe it into librespotd. Then, depending on the backend the user would receive audio data. Is that correct?
