### ISSUE TITLE
Why is multiroom not supported?

### ISSUE THREAD

**Issue by gijswijs** [librespot-org/librespot#431]
I saw a previous issue about multiroom referring to Snapcast.

I totally understand how snapcast could be a solution to multiroom, but it seems slight overkill.

The way I understand Spotify Connect, is that clients announce that they support multiroom. With multiple multiroom devices discovered, the Spotify app will show the option to play on all multiroom devices at the same time.

Couldn't Librespot support this "announcing" of multiroom support that now seems part of the Spotify Connect API?

**Comment by devgianlu** [comment]
Do you know of a brand/device that does this? I have never seen such a thing on Spotify.

**Comment by gijswijs** [comment]
My Raumfeld-s support it see: https://blog.teufelaudio.com/spotify-multiroom-with-raumfeld/
Urbanears: https://support.urbanears.com/hc/en-us/articles/115002243069-How-to-Speakers-Play-in-Multi-Mode-via-Spotify-Connect

But I've don some more investigation, and I think those devices use an approach similar to Snapcast. 
So the device itself sets up a multiroom "server", and then announces the multiroom server as a spotify connect client.

Spotify announced last December that they have no plans right now for supporting this. (https://community.spotify.com/t5/Live-Ideas/Connect-Multiple-Speakers-Devices-simultaneously/idi-p/614088)

Thank you for replying, I now know and understand more.
