### ISSUE TITLE
Podcasts not working

### ISSUE THREAD

**Issue by JPW21** [librespot-org/librespot#432]
I cant play podcasts.
When im already playing a podcast on another device, the librespot device is grayed out in the connect menu.
If i start a podcast when already connected to librespot, the controls are frozen and the last song plays without a way to stop it.

Maybe its connected to this issue:
https://github.com/librespot-org/librespot/issues/90
(i commented a few days ago, but i was thinking opening a new issue would be better for visibility)

Im using raspotify on the raspberry pi 4 4gb and the version is:
0.13.1~librespot.20190416T173925Z.5d2cb32
alsa backend, quality 320, outputdevice hifiberry dac+ pro

I love this program but it would be even better if podcasts would work too.
Thank you.

**Comment by shanemeagher** [comment]
I'm not familiar with raspotify but looks like you are using a very old version of librespot (20190416 - April last year). Podcast support was added in #381 last October.

**Comment by JPW21** [comment]
that makes sense, somehow i was thinking installing raspotify would get me the latest version... :/

**Comment by JPW21** [comment]
I compiled the latest version of librespot and overwrote /usr/bin/librespot, its working now.
Thanks for pointing me in the right direction.

**Comment by ashthespy** [comment]
FWIW, using librespot should be as easy as `cargo install librespot` now :-)
