### ISSUE TITLE
Linear Volume not working with alsa mixer

### ISSUE THREAD

**Issue by JPW21** [librespot-org/librespot#433]
Hi,
Im using a HifiBerry DAC on a raspberry pi with librespot's alsa mixer option.
I'm noticing logarithmic volume control even with --linear-volume enabled.
This means 0-80% volume is extremly quiet. The volume in alsamixer is inconsistent with the spotify connect volume (see screenshots).

If i omit --linear-volume the problem is even worse, meaning 0-95% is quiet...
Almost if its doing log compensation twice, what makes me think that this might be a bug. 

Options:
--backend alsa --device hw:0,0 --mixer alsa --mixer-name Digital --linear-volume --enable-volume-normalisation --initial-volume=40

![alsamixer](https://user-images.githubusercontent.com/60467184/74476090-f7f93c80-4ea8-11ea-87e0-c7c904ea36ab.PNG)
Note that 50% is only 13% in alsa.

![alsamixer2](https://user-images.githubusercontent.com/60467184/74476112-ffb8e100-4ea8-11ea-9fe1-c2f552e6b2c8.PNG)
To reach ~50% i need to almost max-out the spotify volume.

Is my understanding wrong? I thought enabling --linear-volume would mean 50% in spotify corresponds to 50% in alsa.

**Comment by ashthespy** [comment]
Ah, I now see (https://github.com/librespot-org/librespot/pull/245#issuecomment-430247445) that I never got down to merging the stuff from vollibrespot in here. I'll get down to opening a PR soon(ish)

**Comment by JPW21** [comment]
Awesome, thanks for your work!

**Comment by ashthespy** [comment]
PS - if you are in a hurry - I should have some pre-compiled stuff over at [`ashthespy/Vollibrespot`](https://github.com/ashthespy/Vollibrespot/releases) that you can play with in the meantime..

**Comment by JPW21** [comment]
Take your time, at the moment i checked out https://github.com/librespot-org/librespot/pull/430 to test gapless playback anyways.

**Comment by JPW21** [comment]
I have just found out that this problem isnt librespot exclusive:
If i use amixer -q sset Digital 50%
the gets set to 14%.

So it doesnt seem like this is a bug in librespot, sorry.

Any idea how i can fix this?

**Comment by ashthespy** [comment]
@JPW21 you should check out the `-M` aka mapped volume.

**Comment by JPW21** [comment]
@ashthespy Any news for that PR? :)

**Comment by ashthespy** [comment]
@JPW21 haven't made/found the time yet - next week should be possible!
