### ISSUE TITLE
Option to not release alsa after playback

### ISSUE THREAD

**Issue by JaeeonRyoo** [librespot-org/librespot#451]
Apologies if this is already possible, but I could not find any mention of this.

The DAC I'm using seems to go to sleep when ALSA is released and takes a few second to respond when the playback starts again. Is it possible to not release ALSA even when no music is playing?

Thanks :)

**Comment by Malvineous** [comment]
You'd be better off disabling this feature in ALSA as it affects all programs, not just librespot.  You can also investigate disabling power saving features on the sound card which can cause a similar delay.  There is lots of detail about this online as it's a common problem.
