### ISSUE TITLE
Fixed volume

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#46]
<a href="https://github.com/mattiash"><img src="https://avatars0.githubusercontent.com/u/588898?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mattiash](https://github.com/mattiash)**
_Thursday Mar 09, 2017 at 18:13 GMT_
_Originally opened as https://github.com/plietar/librespot/pull/161_

----

Add a --fixed-volume setting that keeps volume at 100%. The volume used in the spotify connect communication is logged.

I am running librespot on a raspberry pi connected to an external amplifier with an API. I want the raspberry pi to always output sound at full volume and then I will adjust the volume on the external amplifier based on the logged volume from librespot.

----

_**[mattiash](https://github.com/mattiash)** included the following code: https://github.com/plietar/librespot/pull/161/commits_

**Comment by sashahilton00** [comment]
<a href="https://github.com/romerod"><img src="https://avatars1.githubusercontent.com/u/3213790?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [romerod](https://github.com/romerod)**
_Monday Mar 13, 2017 at 05:41 GMT_

----

I think it might make more sense to add a mixer which ignores volume requests and has no filter, you get the same result with less if statements

**Comment by sashahilton00** [comment]
<a href="https://github.com/jsopenrb"><img src="https://avatars0.githubusercontent.com/u/19466116?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jsopenrb](https://github.com/jsopenrb)**
_Monday Mar 13, 2017 at 08:01 GMT_

----

+1 for the custom mixer, the same as MPD "null" mixer option.

**Comment by sashahilton00** [comment]
<a href="https://github.com/mattiash"><img src="https://avatars0.githubusercontent.com/u/588898?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mattiash](https://github.com/mattiash)**
_Monday Mar 13, 2017 at 20:37 GMT_

----

> I think it might make more sense to add a mixer which ignores volume requests and has no filter, you get the same result with less if statements

Good idea. I'll give it a try in a separate PR.

**Comment by sashahilton00** [comment]
<a href="https://github.com/mfonville"><img src="https://avatars0.githubusercontent.com/u/6221544?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mfonville](https://github.com/mfonville)**
_Friday Apr 07, 2017 at 07:48 GMT_

----

When doing the 100% volume in the other PR, maybe it would be possible to offer a parameter option to set at least the volume that librespot starts with?

Because I have a device where I would the default volume of librespot want to be a bit lower, instead of the 100%

**Comment by ComlOnline** [comment]
Please see #48
