### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by basedtho** [librespot-org/librespot#466]
both on stable and nightly. both on 0.1.1 and git

```
error[E0308]: mismatched types
  --> protocol/build.rs:45:39
   |
45 |         let p = parse_and_typecheck(&["proto"], &[src]).expect("protoc");
   |                                       ^^^^^^^ expected struct `std::path::Path`, found `str`
   |
   = note: expected reference `&std::path::Path`
              found reference `&'static str`

error[E0308]: mismatched types
  --> protocol/build.rs:45:51
   |
45 |         let p = parse_and_typecheck(&["proto"], &[src]).expect("protoc");
   |                                                   ^^^ expected struct `std::path::Path`, found struct `std::string::String`
   |
   = note: expected reference `&std::path::Path`
              found reference `&std::string::String`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `librespot-protocol`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `librespot v0.1.1 (/home/tho/dev/rs/librespot)`, intermediate artifacts can be found at `/home/tho/.cargo/lib`

Caused by:
  build failed
```

must be something on my end, but i cannot solve this for the life of me

**Comment by basedtho** [comment]
solved by setting `--features "pulseaudio-backend,with-vorbis"`

**Comment by basedtho** [comment]
how do i solve this?

![image](https://user-images.githubusercontent.com/60894565/79696945-4fcc6f00-826f-11ea-815c-8f09ea979ebb.png)

**Comment by basedtho** [comment]
when i only do `--features "pulseaudio-backend"` (without `with-vorbis`), it's still the same error as in the first post

**Comment by ashthespy** [comment]
This is a dupe of #460 and is caused by a breaking change in the protobuf crate.. https://github.com/librespot-org/librespot/pull/463 should fix it..

**Comment by basedtho** [comment]
sorry for the bother. couldn't find it

**Comment by ashthespy** [comment]
Can you confirm if that PR fixes it?

**Comment by basedtho** [comment]
it does! thank you

**Comment by basedtho** [comment]
please merge that PR into master, i can't build spotifyd because the fix is only on dev

**Comment by ashthespy** [comment]
> 
> 
> please merge that PR into master,

I'm not sure how the versioning with cargo and master work, so will leave that to others. 

>
> i can't build spotifyd because the fix is only on dev (if that's possible)

Have a look into Cargo's [`patch`](https://doc.rust-lang.org/edition-guide/rust-2018/cargo-and-crates-io/replacing-dependencies-with-patch.html) or use spotifyd's [`Cargo.lock`](https://github.com/Spotifyd/spotifyd/blob/bf77d9543dba84cadb9abc14e7d45ac4e1e04b1c/Cargo.lock#L1350-L1358) and build it with `cargo build --locked` as possible interim solutions..
