### ISSUE TITLE
MQTT Mixer

### ISSUE THREAD

**Issue by romerod** [librespot-org/librespot#469]
I've contributed the mixer selection (a long time ago) with the idea to implement a mixer which could control external HW.

I think the most generic approach would be a mixer which works over MQTT. Easy to integrate with node-red for example. Open for other ideas.

As this would need a new dependency (mqtt client) would you suggest a build flag or do you have another idea for some kind of plugin model?

**Comment by siebeclaes** [comment]
I just discovered this project today and have been using in on a Raspberry Pi 1 all day and loving it so far.
My first thought immediately was I needed some way to connect librespot with my old stereo to control volume and turn on/off the stereo automatically. MQTT integration would be ideal for this.

I already took a look through the code and adding an MQTT mixer doesn't seem to be too difficult. I'll give this a shot over the weekend and open a PR.

An indeed, putting this behind a feature flag is the right thing to do in my opinion.

**Comment by sashahilton00** [comment]
Not sure if this is is still of interest, but if so please put it in a PR, and we can see about it getting merged. At any rate, people can apply the PR manually as desired if it doesn't make it in. Sounds like a good candidate feature for librespotd though, whenever that happens.

**Comment by dersimn** [comment]
I have a use case for this as well. I would like to control the volume of my stereo directly, do avoid having multiple volume sliders. My stereo is already integrated into MQTT: <https://github.com/dersimn/DevilRemote>.
