### ISSUE TITLE
ALSA lib pcm.c:8382:(snd_pcm_set_params) Sample format not available for PLAYBACK: Invalid argument

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#47]
<a href="https://github.com/archphile"><img src="https://avatars0.githubusercontent.com/u/8850082?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [archphile](https://github.com/archphile)**
_Saturday Mar 11, 2017 at 09:44 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/162_

----

Hi,

I built librespot with alsa backend on Archlinuxarm:

https://aur.archlinux.org/packages/librespot-alsa-git/

When I try to start librespot with the following command:

librespot --cache /var/cache/librespot --name Test --bitrate 320 --username xxxxxx --password xxxxxx

I get the following error:

> ALSA lib pcm.c:8382:(snd_pcm_set_params) Sample format not available for PLAYBACK: Invalid argument
> thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:323
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

Any help is highly appreciated.

Many thanks,

Michael

**Comment by sashahilton00** [comment]
<a href="https://github.com/joerg-krause"><img src="https://avatars2.githubusercontent.com/u/6870896?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joerg-krause](https://github.com/joerg-krause)**
_Saturday Mar 11, 2017 at 10:19 GMT_

----

Looks like your ALSA device does not support the sample format `S16_LE`.

**Comment by sashahilton00** [comment]
<a href="https://github.com/archphile"><img src="https://avatars0.githubusercontent.com/u/8850082?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [archphile](https://github.com/archphile)**
_Saturday Mar 11, 2017 at 10:21 GMT_

----

My device is:

ard 1, ID `DAC', name `S16 USB DAC'
  Device 0, ID `USB Audio', name `USB Audio', 1 subdevices (1 available)
    2 channels, sampling rate 44100..384000 Hz
    Sample formats: S32_LE
      Subdevice 0, name `subdevice #0'

and indeed does not support S16_LE. 

So I assume there's no solution to this?

Many thanks for your immediate reply.

**Comment by sashahilton00** [comment]
<a href="https://github.com/joerg-krause"><img src="https://avatars2.githubusercontent.com/u/6870896?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joerg-krause](https://github.com/joerg-krause)**
_Saturday Mar 11, 2017 at 10:24 GMT_

----

You can set the ALSA device with the `--device` option. Try `--device=plughw:1`.

**Comment by sashahilton00** [comment]
<a href="https://github.com/joerg-krause"><img src="https://avatars2.githubusercontent.com/u/6870896?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joerg-krause](https://github.com/joerg-krause)**
_Saturday Mar 11, 2017 at 10:35 GMT_

----

librespot does use the default device. Your default device does not support S16_LE. If you do not want to set the device with `--device` you have to make `plughw:1` your default ALSA device. You can set this in ALSA config file. Google will help you :smile:

**Comment by sashahilton00** [comment]
<a href="https://github.com/archphile"><img src="https://avatars0.githubusercontent.com/u/8850082?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [archphile](https://github.com/archphile)**
_Saturday Mar 11, 2017 at 10:40 GMT_

----

Many thanks for everything.

I have already created an asound.conf file with the following configuration:

pcm.!default {
        type hw
        card 1
}

As it seems I have to search more for this.

**Comment by sashahilton00** [comment]
<a href="https://github.com/joerg-krause"><img src="https://avatars2.githubusercontent.com/u/6870896?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joerg-krause](https://github.com/joerg-krause)**
_Saturday Mar 11, 2017 at 10:43 GMT_

----

Try this:
```
pcm.!default {
type plughw
card 1
}
```

**Comment by sashahilton00** [comment]
<a href="https://github.com/archphile"><img src="https://avatars0.githubusercontent.com/u/8850082?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [archphile](https://github.com/archphile)**
_Saturday Mar 11, 2017 at 11:11 GMT_

----

Thank you very much for everything Joerg.

Everything is up and running buy adding the device option on the systemd.service file.

**Comment by sashahilton00** [comment]
<a href="https://github.com/joerg-krause"><img src="https://avatars2.githubusercontent.com/u/6870896?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joerg-krause](https://github.com/joerg-krause)**
_Saturday Mar 11, 2017 at 11:15 GMT_

----

You are welcome!

**Comment by sashahilton00** [comment]
<a href="https://github.com/arthurlutz"><img src="https://avatars1.githubusercontent.com/u/108437?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [arthurlutz](https://github.com/arthurlutz)**
_Thursday Nov 16, 2017 at 20:45 GMT_

----

am getting this too, but with a FiiO USB DAC adding ```--device=plughw:1``` doesn't fix it. See my report on pimusicbox through which I am using librespot https://github.com/pimusicbox/pimusicbox/issues/453

**Comment by ComlOnline** [comment]
The last comment was a different issue. Closing as it was solved.
