### ISSUE TITLE
error: could not compile `librespot-protocol`

### ISSUE THREAD

**Issue by XeOS1977** [librespot-org/librespot#473]
What am I doing wrong? I'm on Ubuntu 20.04 with version rustc 1.43.1 (8d69840ab 2020-05-04) Installed the extra's (build-essential, libasound2-dev, pkg-config)
I've done reboots, uninstalls, clean-ups but can't get it to install. Errors are as follows:

   Compiling librespot-protocol v0.1.1
error[E0308]: mismatched types
  --> /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-protocol-0.1.1/build.rs:45:39
   |
45 |         let p = parse_and_typecheck(&["proto"], &[src]).expect("protoc");
   |                                       ^^^^^^^ expected struct `std::path::Path`, found `str`
   |
   = note: expected reference `&std::path::Path`
              found reference `&'static str`

error[E0308]: mismatched types
  --> /home/paul/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-protocol-0.1.1/build.rs:45:51
   |
45 |         let p = parse_and_typecheck(&["proto"], &[src]).expect("protoc");
   |                                                   ^^^ expected struct `std::path::Path`, found struct `std::string::String`
   |
   = note: expected reference `&std::path::Path`
              found reference `&std::string::String`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `librespot-protocol`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `librespot v0.1.1`, intermediate artifacts can be found at `/tmp/cargo-install2U3hao`

Caused by:
  build failed

**Comment by ashthespy** [comment]
Dupe of #460 are you on current `dev`?

**Comment by XeOS1977** [comment]
Yes I am, I used the suggestion of #460 cloning the repo and build from there and now it's working. Apologies for not finding #460 and thanks a million for Librespot

**Comment by ashthespy** [comment]
@XeOS1977 were you running `cargo install librespot` previously?

**Comment by XeOS1977** [comment]
Yes I was, with forementioned additions
