### ISSUE TITLE
Cargo install is broken

### ISSUE THREAD

**Issue by ashthespy** [librespot-org/librespot#477]
Thanks to a breaking change in `protobuf-pure`, our current master will not build with `cargo install`. 
A workaround is to pass the `--locked` flag i,e `cargo install --locked` as per https://github.com/rust-lang/cargo/issues/7169 

cc #473 #460

@awiouy @sashahilton00 Could you make a patch release with 6ee2dbaad4406628f77cd59adebb2ed3ed70fcaa in the meantime?

**Comment by awiouy** [comment]
What about vendoring the required crates and using only the vendored crates at build time? This way, the source code would be complete and consistent.
https://doc.rust-lang.org/cargo/commands/cargo-vendor.html

**Comment by ashthespy** [comment]
Doesn't vendoring requiring you to clone the repo first? 
You might as well just build it with `--locked` if you already cloned it right?

**Comment by TooLazyToMakeAName** [comment]
> What about vendoring the required crates and using only the vendored crates at build time? This way, the source code would be complete and consistent.
> https://doc.rust-lang.org/cargo/commands/cargo-vendor.html

could you not do that commit to master then rebase dev onto master ? A none compiling master seem the greater evil.

**Comment by EdoardoLaGreca** [comment]
If you're trying to compile it on a Raspberry Pi (as I did, expect 40m+ of compiling time) I'd suggest you to try this command: `cargo install --features alsa-backend -- librespot`.
