### ISSUE TITLE
build failing on FreeBSD due to 'hostname'

### ISSUE THREAD

**Issue by LeoSum8** [librespot-org/librespot#478]
Hi all,
I am trying to build librespot on FreeBSD 11.3.

So far I could successfully build the `v1.1.0` tag with `cargo build --no-default-features`.

However when I try to build the latest state of `dev` or `master` I get the following error:

````
root@build-system:/mnt/build_system/librespot # cargo build --no-default-features
   Compiling hostname v0.2.0
   Compiling librespot-protocol v0.1.1 (/mnt/build_system/librespot/protocol)
   Compiling librespot-core v0.1.1 (/mnt/build_system/librespot/core)
error[E0308]: mismatched types
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/hostname-0.2.0/src/nix.rs:51:13
   |
51 |             size,
   |             ^^^^ expected `i32`, found `usize`
   |
help: you can convert an `usize` to `i32` and panic if the converted value wouldn't fit
   |
51 |             size.try_into().unwrap(),
   |             ^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `hostname`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
````

**Comment by ashthespy** [comment]
Looks like something is up with [`libmdns`](https://github.com/librespot-org/libmdns/). Are you able to build that crate alone?

cc @willstott101

**Comment by willstott101** [comment]
Hm `libmdns 0.4+` uses `hostname 0.3`. Perhaps I should try bumping hostname in the `libmdns 0.2` too.

aha... in-fact https://github.com/svartalf/hostname/commit/63209523b3c3d1973d1683b37b3c4e1db6565af9

**Comment by willstott101** [comment]
So that is almost definitely the problem, I'll release new versions for libmdns 0.2 and 0.3 shortly. Then we can bump in librespot.

**Comment by willstott101** [comment]
PR here: https://github.com/librespot-org/librespot/pull/479

**Comment by LeoSum8** [comment]
Yup, I can confirm that you fixed it! Thank you!
