### ISSUE TITLE
Add mixer fixedvol

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#48]
<a href="https://github.com/mattiash"><img src="https://avatars0.githubusercontent.com/u/588898?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mattiash](https://github.com/mattiash)**
_Tuesday Mar 14, 2017 at 19:56 GMT_
_Originally opened as https://github.com/plietar/librespot/pull/163_

----

Add a new mixer that always outputs sound at 100% volume. To print the current volume that spotify requests, set RUST_LOG=librespot::mixer::fixedmixer=debug

This PR can be applied instead of PR #161 .

----

_**[mattiash](https://github.com/mattiash)** included the following code: https://github.com/plietar/librespot/pull/163/commits_

**Comment by ComlOnline** [comment]
@mattiash Could you please submit another PR to this repo? Thanks
