### ISSUE TITLE
Pass libogg library path?

### ISSUE THREAD

**Issue by fightwithcrayon** [librespot-org/librespot#480]
I'm currently building a Swift MacOS app, which wraps around and controls Spotify for a few audio playback features.

Using the `Process` feature, I can safely launch/control/terminate a librespot child process in sandbox mode. This seems perfect, but I'm reaching a stumbling block as it obviously relies upon the external libogg.0.dylib framework.

I've managed to move this to the app, add it to the build phases, and sign it, which allows it to be safely loaded within the sandbox. But obviously librespot does not know to look for it in the local project directory (infact, same directory as the librespot built executable).

Is there anyway to manually tell librespot where it should look for libogg? Whether that's at run time, build time, or perhaps even if I created a custom build with a change somewhere?

**Comment by ashthespy** [comment]
I might be mistaken, but if your building it with `lewton` for the decoder (the default one) it should be a pure rust implementation with the [`ogg`](https://github.com/RustAudio/ogg) crate?

**Comment by fightwithcrayon** [comment]
You're completely right, thanks – closing!
