### ISSUE TITLE
Are there methods to get Account information?

### ISSUE THREAD

**Issue by EliteDaMyth** [librespot-org/librespot#489]
E.G. Account Subscription,
FAmily invite link etc.

**Comment by ashthespy** [comment]
> E.G. Account Subscription,

Nope, since librespot works only with a Premium account to begin with, it's not required. That being said, nothing stopping you from reverse engineering and figuring out the right internal API endpoints to obtain this information.

**Comment by EliteDaMyth** [comment]
> > E.G. Account Subscription,
> 
> Nope, since librespot works only with a Premium account to begin with, it's not required. That being said, nothing stopping you from reverse engineering and figuring out the right internal API endpoints to obtain this information.

i have found some endpoints but the require the access token. is there a way to get the access token from the package?

also the endpoint is https://www.spotify.com/token-bounce/?url=/redirect/account-page for anyone interested with the following user agent: `  CONTENTTYPE "application/x-www-form-urlencoded" 
  HEADER "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko" 
  HEADER "Pragma: no-cache" 
  HEADER "Accept: */*" 
  HEADER "accept: application/json, text/plain;q=0.2, */*;q=0.1" 
  HEADER "accept-encoding: gzip;q=1.0, compress;q=0.5" 
  HEADER "accept-language: en-US;q=1.0" 
  HEADER "app-platform: iOS" 
  HEADER "content-length: 163" 
  HEADER "content-type: application/x-www-form-urlencoded" 
  HEADER "host: creator.wg.spotify.com" 
  HEADER "proxy-connection: keep-alive" 
  HEADER "spotify-app: S4A" 
  HEADER "spotify-app-version: 2.0.15" 
  HEADER "user-agent: S4A/2.0.15 (com.spotify.s4a; build:201500080; iOS 13.3.1) Alamofire/4.9.0" `
Its a POST rquest with the data `oauth_token=<accesstk>`

**Comment by ashthespy** [comment]
Have a look at [`keymaster.rs`](https://github.com/librespot-org/librespot/blob/dev/core/src/keymaster.rs)

PS: I was also referring to mercury endpoints :-)
