### ISSUE TITLE
Documentation.

### ISSUE THREAD

**Issue by EliteDaMyth** [librespot-org/librespot#490]
Is there documentation for the package? E.G. Functions, methods etc? so we can use in our own project?
something like the example folder

**Comment by ashthespy** [comment]
Most of the documentation in the wiki and docs folder are focused more on the protocol, and building and using librespot as a stand-alone player, and not a library. 
Other documentation is spread around in issues and PRs and not really compiled. Our resources are limited, thus PRs are always welcome :-)

**Comment by EliteDaMyth** [comment]
Interesting. Thanks for the reply. I'll try finding projects that use this and use them as examples to learn from them.

**Comment by EliteDaMyth** [comment]
@ashthespy can we have an separate gh-pagees branch for auto generated docs from cargo?
better than nothing. If yes LMK i'll open a PR

**Comment by EliteDaMyth** [comment]
@ashthespy bump

**Comment by ashthespy** [comment]
I'm not sure if I follow - we haven't written any docs currently for cargo to auto generate documentation..

**Comment by EliteDaMyth** [comment]
@ashthespy the default stuff doesnt seem to be working 
https://docs.rs/librespot-core/0.1.1/librespot_core/index.html (this is the link it redirects you to when you click on any one of the options on https://docs.rs/librespot/0.1.1/librespot/ )

**Comment by ashthespy** [comment]
It would seem when the [v0.1.1](https://github.com/librespot-org/librespot/releases/tag/v0.1.1) was published, the various workspace modules docs weren't built/uploaded. You could use [v0.1.0](https://docs.rs/librespot-core/0.1.0/librespot_core/index.html) docs instead, there shouldn't be too many API changes b/w the two..

FWIW, the docs at this stage aren't super helpful as all it does is expose the type information and function signatures. It's probably faster to use [rust-analyser](https://github.com/rust-analyzer/rust-analyzer) with the editor of your choice to give you the same hints..

**Comment by EliteDaMyth** [comment]
I already have rust analyzer installed. Thanks for the reply. I am gonna close this issue.
