### ISSUE TITLE
Add more to onevent.

### ISSUE THREAD

**Issue by purringChaos** [librespot-org/librespot#491]
Having a way to get Spotify API key from librespot would be nice for fetching song titles and stuff.
Alternatively provide all track info so you don't need to call the spotify API a 2nd time to fetch that info.

Example usage: Scrobbler script for libre.fm, notification daemon displaying current song, etc.

**Comment by ashthespy** [comment]
> Having a way to get Spotify API key from librespot would be nice for fetching song titles and stuff.

Have a look at [`keymaster.rs`](https://github.com/librespot-org/librespot/blob/dev/core/src/keymaster.rs) - it does exactly that.. 

>  Alternatively provide all track info so you don't need to call the spotify API a 2nd time to fetch that info.

Yes, this is an old discussion (https://github.com/librespot-org/librespot/issues/7) about liberspot (the library) vs [librespotd](https://github.com/librespot-org/librespotd) (the coming soon™,  full featured daemon) 

If you don't mind, will close this in favour of the older issues. Feel free to post specifics there!
