### ISSUE TITLE
Replace Panics with actual proper error code

### ISSUE THREAD

**Issue by EliteDaMyth** [librespot-org/librespot#496]
in https://github.com/librespot-org/librespot/blob/dev/core/src/connection/mod.rs#L121
when there is an error it returns an Panic. Instead of Panic Can an error code be returned?
*P.S. I'm using librespot as a library*

**Comment by ashthespy** [comment]
The overall issue of panics is already being tracked in #193, closing this in favour of that..

During the refactor to futures 0.3/async/await, this is one the low hanging fruits [that we are trying to grab as well..](https://github.com/librespot-org/librespot/pull/487/commits/eee8ada1bb4c29f77a8bb5b5e58b40cfcc9a88a9#diff-a28df30749bc2e5e613350e045ad3672R14-R20)
