### ISSUE TITLE
Panic with message "No space left on device"

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#51]
<a href="https://github.com/joerg-krause"><img src="https://avatars2.githubusercontent.com/u/6870896?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [joerg-krause](https://github.com/joerg-krause)**
_Friday Mar 17, 2017 at 09:51 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/166_

----

When playling long tracks on my embedded device with about 36MB of free RAM, librespot panics with: `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 28, message: "No space left on device" } }'`.

For example using [this](https://open.spotify.com/track/0Kbvz9ZjihrcE1Vd1dDCZh) track (45:31). Is there a way not to load the whole song into RAM?

**Comment by sashahilton00** [comment]
<a href="https://github.com/plietar"><img src="https://avatars0.githubusercontent.com/u/1489775?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [plietar](https://github.com/plietar)**
_Friday Mar 17, 2017 at 14:37 GMT_

----

Interesting, I never really considered very large tracks.
librespot doesn't load the whole song into RAM, but it downloads it into `/tmp`, which may be the same thing if that is mounted as a tmpfs.

As a temporary workaround, you can change [this line from `NamedTempFile::new()`](https://github.com/plietar/librespot/blob/eb49ff34f1fa5aa032d71573cb91101f315c1a34/src/audio_file.rs#L68) to `NamedTempFile::new_in("/somewhere/not/in/ram")`.

Ideally, if a cache directory is specified we can just use `$CACHE/temp` automatically for that.

**Comment by sashahilton00** [comment]
<a href="https://github.com/joerg-krause"><img src="https://avatars2.githubusercontent.com/u/6870896?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joerg-krause](https://github.com/joerg-krause)**
_Friday Mar 17, 2017 at 17:52 GMT_

----

Thanks, I will try this. In fact, this track is an extreme. It my also happen for tracks having a length of six or seven minutes, depending on the free RAM left.

**Comment by sashahilton00** [comment]
<a href="https://github.com/joerg-krause"><img src="https://avatars2.githubusercontent.com/u/6870896?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [joerg-krause](https://github.com/joerg-krause)**
_Thursday Mar 23, 2017 at 12:10 GMT_

----

On second thought, my system is NAND flash based. So, using anything else than the RAM for caching is not a good idea. So, I need a bigger RAM?

**Comment by sashahilton00** [comment]
<a href="https://github.com/plietar"><img src="https://avatars0.githubusercontent.com/u/1489775?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [plietar](https://github.com/plietar)**
_Thursday Mar 23, 2017 at 13:25 GMT_

----

Pretty much. A solution would be to change `librespot` to break up the files in blocks of say 500KB, and delete them automatically (if cache is disabled) once it has moved on to the next one. This is a large-ish change, so it's unlikely I'll be able to implement it anytime soon unfortunately.

**Comment by sashahilton00** [comment]
<a href="https://github.com/michaelherger"><img src="https://avatars3.githubusercontent.com/u/2789989?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [michaelherger](https://github.com/michaelherger)**
_Tuesday May 02, 2017 at 04:33 GMT_

----

I've modified librespot to disable the audio file-cache. See pull request #181.

**Comment by ComlOnline** [comment]
The final PR for this was closed. See [here](https://github.com/plietar/librespot/pull/204).

**Comment by plietar** [comment]
This is different from https://github.com/plietar/librespot/pull/204. The issue here is that librespot tries to download the entire file (whether or not cache is enabled), which may be impossible for long tracks and low memory devices.

**Comment by michaelherger** [comment]
Yep, I had to learn this the hard way: though I had the audio-cache disabled I still saw people with large files in TMPDIR. In my case I was able to work around this using the method mentioned by @plietar: have librespot write to some place outside in-memory storage. Setting `TMPDIR=/path/to/folder librespot ...` does the trick here.

**Comment by sashahilton00** [comment]
given that all spotify songs are downloaded in chunks, is there an easy way to discard chunks once they have been played when the cache is disabled?
