### ISSUE TITLE
is login required?

### ISSUE THREAD

**Issue by markfoodyburton** [librespot-org/librespot#513]
I assume that to make use of Librespot, you would need to provide a username and password for a Spotify premium account. All the examples I see (e.g. https://github.com/librespot-org/librespot#usage) dont mention this?
Indeed - does it make sense for Librespot to even start without a valid username/password?

Or maybe I have missed something? Is it only the account on the 'phone app' that is attempting the discovery that needs the premium account?  - (For now, I can't discover Librespot from a phone or a desktop app, but I dont have a premium account, so I expect it "not to work", but I expected to be able to 'discover' Librespot - but e.g. for the connection to fail, and maybe log something on the server)...

**Comment by kingosticks** [comment]
You need a premium account to use this software but there are multiple ways to login with that premium account, one of which is via zeroconf (using the logged in premium account on your phone/other device) and so there's no requirement to provide a username and password to start librespot. So yes, the behaviour makes sense.

I don't remember if you can discover librespot from your phone/device without a premium account logged in on the device. But isn't it up to the Spotify client on your phone to decide what it shows as available? If it's not going to work, seems sensible to hide it. Either way, that's up to Spotify's client to decide.

**Comment by markfoodyburton** [comment]
Thanks for the clarification.

**Comment by markfoodyburton** [comment]
Sorry to comeback on this. I now have a premium account, and am able to connect to librespot so long as (a) I enter the user/passwd on the command line, and (of course) connect from the same account.
In short, I can't get 'zeroconf' to work. Is there some magic there?
What I'm expecting is that anybody with an account "in the house" could connect to librespot, "own" it while they are playing music on it, and then, "release" it such that somebody else could connect to it....
Am I dreaming of functionality that isn't there?

**Comment by markfoodyburton** [comment]
To partially answer my own question, I think
Spotify doesn't directly support what I was expecting : see 
https://community.spotify.com/t5/Closed-Ideas/Connect-Multiple-Accounts-access-same-Device/idi-p/967099/page/14#

However, I think there are 2 solutions...

Solution 1:
- I have a problem with mdns. It's a bit painful to debug, I can see the requests arriving, but I can't see the replies that are sent in the trace. 
But, I believe that if I were to solve this problem, I could use a onevent to restart the server, deleting the cache directory in the process, such that the next connection would 'take over' the speaker. 

This solution is very course grained. One person controls the speaker at any one time.

Solution 2:
The second solution should work out of the box, but "costs". If I'm right, you could register a new account for your speaker (librespot). Select (and own) the speaker from that account. You no longer need mdns, as you can set the username and password. From that same account, start a "Group". Whenever somebody wants to control the speaker (and, of course, they will need the ability to join the group - e.g. the link), they simply join the group, and hey-presto.

This works, except the client doesn't seem to remember the groups you have access to....

possibly you could achieve the same sort of thing with a shared playlist, but you would still need an account for the speaker I guess....

**Comment by ashthespy** [comment]
The discovery ability is exactly what you describe - it broadcasts its presence via mdns to all (premium for librespot) clients on the same network. An active connection kills the old (playing or paused) connection, which can lead to some fun wars for control of the speaker within the network ;-)

**Comment by markfoodyburton** [comment]
Mmm, so I should sort out my mdns issues. I'm running librespot on a router that has a VPN, a couple of vlans and an ethernet (lan) connection. The router is running dnsmasq and firehol. From what I have understood, mdns will attempt to broadcast on all interfaces. In the trace log, I can see the broadcasts and request questions arriving (and the interfaces being discovered)
```sh
libmdns::fsm] sending packet to V4(224.0.0.251:5353)
libmdns::fsm] received question: IN _spotify-connect._tcp.local
```
But I dont see any responses being sent or anything else. What should I be looking for, and has anybody got some hits in terms of debug?

**Comment by ashthespy** [comment]
Not much help, but have you tried debugging on the same system?  I.e running `RUST_LOG=libmdns=trace librespot <args>`  and connect from a client on the same machine?

**Comment by markfoodyburton** [comment]
Nice idea :-( It's a headless server (with rather limited space, so I didn't install things like a browser....) .. I also suspect the firewall, but I haven't found the culprit yet - tried switching the firewall off, but that has some fairly nasty consequences in my case so the results were rather non-conclusive :-(

**Comment by markfoodyburton** [comment]
multicast packets were not going to the right device, for me, adding this helped,
ip route add 224.0.0.0/4 dev eth0
