### ISSUE TITLE
librespot_playback could not start/write audio

### ISSUE THREAD

**Issue by savchenkoElla** [librespot-org/librespot#515]
hi, 
I am using raspotify and librespot to make my raspberry pi to one spotify connect client. 
When I was using an USB-Headset, this has worked. Now I am trying to make this work with bluetooth speaker. I can play sound on raspberry pi with pulseaudio an thus, I have build the librespot with pulseaudio as backend.

When I start raspotify, I get this error:

Aug 03 14:41:42 raspberrypi librespot[1186]: [2020-08-03T12:41:42Z ERROR librespot_playback::player] Could not start audio: Connection refused
Aug 03 14:41:42 raspberrypi librespot[1186]: [2020-08-03T12:41:42Z ERROR librespot_playback::player] Could not write audio: Not connected to pulseaudio

Could someone help me with this? 

Thank you :)

**Comment by Malvineous** [comment]
This isn't a librespot problem.  If you can get your system to play audio from the device with other programs then librespot will also work.

It looks like you have configured librespot to use pulseaudio but you aren't running pulseaudio, so once you fix your audio config them librespot should start working.  Hopefully your Linux distro support can point you in the right direction there.

**Comment by savchenkoElla** [comment]
All the others playback programs are already working with pulseaudio. But I still have the same error with librespot..

**Comment by Malvineous** [comment]
In the same terminal as you are using to run librespot, what does the command "pacmd list-sinks" report?  This will ask PulseAudio to show which playback device it is using.
