### ISSUE TITLE
hear audio as normal user but not as root or system service

### ISSUE THREAD

**Issue by puccaso** [librespot-org/librespot#517]
I was unable to get the system service to run,
so i ran the librespot manually with --verbose
and i could see no major issue, and yet
i can run the app via a normal user and hear sound
but hear no sound when run in su, as sudo, or as the system service, 
also, as normal user - i was also unable to hear anything when setting cache location...

any ideas?

**Comment by Malvineous** [comment]
Probably your system is set to run Pulseaudio in user mode, so you have to run librespot as the same user or it won't have permission to play audio.  This is an issue with your distro and how you are running librespot as a system service, so you'll probably have to ask your distro for support as it's not really anything librespot has control over.
