### ISSUE TITLE
Poor error message when using free account

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#52]
<a href="https://github.com/Elronnd"><img src="https://avatars2.githubusercontent.com/u/11526194?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Elronnd](https://github.com/Elronnd)**
_Friday Mar 24, 2017 at 03:44 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/167_

----

I get `thread 'main' panicked at 'Authentication failed', /home/elronnd/librespot/target/debug/build/librespot-dfbb8235c1536a0f/out/lib.rs:365` when I try to run it.  I'm running with

    RUST_BACKTRACE=1 ./librespot -n "name" -u username -p password

[Backtrate](https://files.catbox.moe/fzvuvf.txt).

**Comment by sashahilton00** [comment]
<a href="https://github.com/plietar"><img src="https://avatars0.githubusercontent.com/u/1489775?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [plietar](https://github.com/plietar)**
_Tuesday Apr 25, 2017 at 15:57 GMT_

----

I'm not really sure what could be causing the `Authentication failed` other than well an incorrect password. Are you using a free account ? librespot only works with premium.
cc @kcning

**Comment by sashahilton00** [comment]
<a href="https://github.com/kcning"><img src="https://avatars0.githubusercontent.com/u/19646772?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kcning](https://github.com/kcning)**
_Tuesday Apr 25, 2017 at 16:00 GMT_

----

Yes I'm using a free account. It's probably the cause.

**Comment by sashahilton00** [comment]
<a href="https://github.com/john3voltas"><img src="https://avatars1.githubusercontent.com/u/5383848?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [john3voltas](https://github.com/john3voltas)**
_Sunday Aug 13, 2017 at 04:57 GMT_

----

There is absolutely no way to realize that librespot needs a Spotify premium account in order to work.
Could you please add it to the readme so that others don't make the same mistake I did?
Oh, and thanks for making librespot and for sharing it with us. :-)
Cheers

**Comment by sashahilton00** [comment]
<a href="https://github.com/eladnava"><img src="https://avatars3.githubusercontent.com/u/4394189?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [eladnava](https://github.com/eladnava)**
_Thursday Oct 05, 2017 at 12:17 GMT_

----

@john3voltas I submitted a PR: #259.

**Comment by ComlOnline** [comment]
I would say that this still needs to be implemented if possible, however it is not a priority.
