### ISSUE TITLE
Duplicate event playing with "onevent"

### ISSUE THREAD

**Issue by all3kcis** [librespot-org/librespot#527]
I added "onenvent" param and when a test with something like : 
```sh
#!/bin/sh
echo Spotify event: --------------------------------------------- >> /install/test.log
echo PLAYER_EVENT: $PLAYER_EVENT >> /install/test.log
echo TRACK_ID:     $TRACK_ID >> /install/test.log
echo OLD_TRACK_ID: $OLD_TRACK_ID >> /install/test.log
```
I get : 
```sh
Spotify event: ---------------------------------------------
PLAYER_EVENT: paused
TRACK_ID: 7FEltWF1lj6brKHafmAEt0
OLD_TRACK_ID:
Spotify event: ---------------------------------------------
PLAYER_EVENT: playing
TRACK_ID: 7FEltWF1lj6brKHafmAEt0
OLD_TRACK_ID:
Spotify event: ---------------------------------------------
PLAYER_EVENT: playing
TRACK_ID: 7FEltWF1lj6brKHafmAEt0
OLD_TRACK_ID:
```

And if I change song : 
```
PLAYER_EVENT: change
TRACK_ID: 4SNtyKNyYJ8ERT7YLlnFBr
OLD_TRACK_ID: 1mweJExKILP5pxrPpIQwHQ
Spotify event: ---------------------------------------------
PLAYER_EVENT: playing
TRACK_ID: 4SNtyKNyYJ8ERT7YLlnFBr
OLD_TRACK_ID:
```

Why "playing" event is raised in the same time ?
I think I used V 0.1.3, but how can I check that ?

I would like to execute an action on "playing".
to turn on the amp with a CEC control
But if the event is raised twice, this can be a problem.

**Comment by JasonLG1979** [comment]
It's not a perfect solution but why not just throttle the playing event if all your getting is double events?

**Comment by all3kcis** [comment]
In the end, I didn't need the "playing" event for what I wanted to do, just start/stop.

But the question remains open about the duplication of the "playing" event.
Maybe it should sometimes be "on_playing" versus "start_playing".

**Comment by JasonLG1979** [comment]
> But the question remains open about the duplication of the "playing" event.
> Maybe it should sometimes be "on_playing" versus "start_playing".

I don't know, maybe it represents the latency between when it received the instruction to play vs when playback actually began?

**Comment by kingosticks** [comment]
`Playing` sounds like the wrong event for what you want:
https://github.com/librespot-org/librespot/blob/a2f832dff171914935f7e1a98a5da3d7c8a0b789/playback/src/player.rs#L104-L116

`Started` sounds more suited to your use-case:
https://github.com/librespot-org/librespot/blob/a2f832dff171914935f7e1a98a5da3d7c8a0b789/playback/src/player.rs#L85-L91

Do you see that initial `Started` event?

**Comment by all3kcis** [comment]
As I said, in my case yes, I used only the "started" event.

Thanks for the quotes, I conclude that even if it's astonishing it's the expected behaviour.

**Comment by kingosticks** [comment]
We can close this then.
