### ISSUE TITLE
discovery: allow setting port explicitly

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#53]
<a href="https://github.com/florolf"><img src="https://avatars2.githubusercontent.com/u/1835?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [florolf](https://github.com/florolf)**
_Monday Mar 27, 2017 at 19:13 GMT_
_Originally opened as https://github.com/plietar/librespot/pull/169_

----

Allow the user to specify the port used for the discovery service
manually, instead of it being chosen by the operating system.

This is useful when using an external mDNS responder, for example in a
setup where the clients and the librespot installation live in different
broadcast domains.

----

_**[florolf](https://github.com/florolf)** included the following code: https://github.com/plietar/librespot/pull/169/commits_

**Comment by ComlOnline** [comment]
Please see #91
