### ISSUE TITLE
Project Scope Question

### ISSUE THREAD

**Issue by SeanPedersen** [librespot-org/librespot#536]
Please forgive my ignorance but can this tool be used to dump my liked songs as MP3 or FLAC audio files?

**Comment by ashthespy** [comment]
Nope, that would be very much against Spotify's TOS.

**Comment by SeanPedersen** [comment]
I see... asking differently does this tool cache songs on disk? and if so in what format?

**Comment by ashthespy** [comment]
It's not a mater of semantics - this library isn't meant to do what you are looking for - in any form.

**Comment by SeanPedersen** [comment]
Alright, thanks for the quick response!
