### ISSUE TITLE
LibreELEC doesn't show up as 'Spotify Connect' Device anymore

### ISSUE THREAD

**Issue by woeisme** [librespot-org/librespot#544]
LibreELEC official 9.0.2 
Build Kodi 18.2 Git:newclock5_18.2-Lea
Librespot add-on version 9.0.115 

In the past 2 days I've lost the ability to cast select the LibreELEC device in Spotify. It no longer shows up in the list of devices within spotify desktop client or android client. Looking through the logs at $HOME/.kodi/kodi.log seems normal enough, service is started. Looking through kodi_crash.log shows some exceptions and Tracebacks with librespot but nothing within the last 2 days. 

Any ideas where else to look?

**Comment by sashahilton00** [comment]
You'd be better off looking in the LibreELEC forums. This is the repo for the library that the addon uses, and as such we can't provide support for the addon here.
