### ISSUE TITLE
Change of output device on macos doesn't affect librespot playback

### ISSUE THREAD

**Issue by hgvhgv** [librespot-org/librespot#547]
I just started using ncspot on macos 10.15.7. When I change the output device via macos (e.g., from speakers to bluetooth), ncspot continues playback over the original device and has to be restarted to switch.

I built librespot today and confirmed that it happens with a simple librespot server and spotify connect. When I run librespot with verbose output, nothing registers when I change the macos output device.

This was already reported on ncspot (https://github.com/hrkfdn/ncspot/issues/339). It is perhaps related to this rodio issue, but the rodio version included with librespot is earlier than this (https://github.com/RustAudio/rodio/issues/327).

If I have time, I might try building rodio and testing it directly there, though the version issue might complicate this.

**Comment by ashthespy** [comment]
FWIW, there is a WIP branch with newer Rodio #543

**Comment by hgvhgv** [comment]
OK so I recompiled librespot with portaudio backend, and the problem persisted. So it's possibly related to librespot, but is possibly a problem shared by rodio and portaudio. I've always had problems with pulseaudio on macos, so I'm not going to try that.

The recompilation did sound better, though, and I realized that I was experiencing some of the noise with rodio reported elsewhere (e.g., https://github.com/RustAudio/rodio/issues/225, https://github.com/hrkfdn/ncspot/issues/333).

**Comment by roderickvd** [comment]
Yes this is outside of the scope of `librespot`, and a consequence of how the backend crates open the playback devices.

**Comment by deed02392** [comment]
Thanks for the reply! But how do other userspace apps handle this so effectively? For example the Spotify desktop app happily and transparently simply starts to output audio to the new system default output device. Why aren't the userspace audio backends that librespot implements doing the same thing?

**Comment by aviwad** [comment]
still experiencing this problem.

**Comment by roderickvd** [comment]
For those who are experiencing this but did not read through the posts: yes this issue exists but belongs to a dependency of ours, not `librespot` itself. Repeating that it does not work here does nothing to further that.

**Comment by aviwad** [comment]
my bad. just checked the culprit was calp in rustaudio.

**Comment by jackwellsxyz** [comment]
There doesn't appear to be any movement on the cpal front to fix this bug in Mac OS at least. This has been open since January 2021. https://github.com/RustAudio/cpal/issues/528.

**Comment by sjdonado** [comment]
> There doesn't appear to be any movement on the cpal front to fix this bug in Mac OS at least. This has been open since January 2021. [RustAudio/cpal#528](https://github.com/RustAudio/cpal/issues/528). This means playback on Mac OS is a pretty poor experience since you're probably limited to playback through speakers only.

you can play on the airpods if they are connected before the service is started

**Comment by xartuu** [comment]
The problem continues to occur. I am using ncspot 1.1.0 (https://github.com/hrkfdn/ncspot/issues/339). When connecting an audio device, the music does not automatically switch to the new device.

Unfortunately, this is the only thing and also noticeable when using Spotify in cli, which is a shame. Has anything changed on this subject?

Unless I am mistaken this has been fixed in https://github.com/RustAudio/rodio/issues/225? Can portaudio backend also do this?
