### ISSUE TITLE
Cross compile section could be improved

### ISSUE THREAD

**Issue by jkiddo** [librespot-org/librespot#556]
I just fell across the guidelines for cross compiling this project from the retired project (plietar/librespot) on https://awesomeopensource.com/project/plietar/librespot and they still works. Shouldn't those cross compiling guidelines also be part of the current compile guidelines

**Comment by ashthespy** [comment]
Have you looked at the [wiki section on cross compiling?](https://github.com/librespot-org/librespot/wiki/Cross-compiling)

**Comment by jkiddo** [comment]
Now I have 👍
