### ISSUE TITLE
Restrict access to one spotify account?

### ISSUE THREAD

**Issue by kippenjongen** [librespot-org/librespot#562]
Is it possible to restrict access to librespot to just one spotify account? I've already got the username and password options set, but you can still access it from another account on the same network. Is there anything that I'm missing, or isn't this possible?

**Comment by ashthespy** [comment]
You probably want [`--disable-discovery`](https://github.com/librespot-org/librespot/wiki/Options)

**Comment by kippenjongen** [comment]
Thanks, that worked! I must have somehow missed that, sorry
