### ISSUE TITLE
alsa and alsa-sys defined 2 times in Cargo.lock

### ISSUE THREAD

**Issue by StopMotionCuber** [librespot-org/librespot#563]
Hey everyone,
there are 2 packages of alsa and alsa-sys defined in Cargo.lock, both with different versions. This is preventing me from building with alsa-backend enabled.

I wanted to ask whether this is intentional or happened accidentially (if the latter is given, I would happily create a PR for that)

**Comment by mdekstrand** [comment]
Also hit this trying to build the dev branch to work around #567. Release 0.1.3 works fine.
