### ISSUE TITLE
librespot panics! when authentication fails 

### ISSUE THREAD

**Issue by xou816** [librespot-org/librespot#565]
When authentication fails (bad credentials, non-premium account, etc), librespot panics! instead of returning a proper Result::Err. 

I see authenticate and Session::connect both return a io::Error instead of a custom result/error type. Is that intentional? If not, would you be open to a PR introducing a dedicated error type? (I suppose this would require some discussion in terms of implementation and potentially breaking changes).

(by the way, thank you very much for the outstanding work involved in this project!)

**Comment by ashthespy** [comment]
I dabbled a little with improving the error handling by converting to  [`thiserror`](https://docs.rs/thiserror/1.0.23/thiserror/) and the binary to [`anyhow`](https://docs.rs/anyhow/1.0.38/anyhow/). But didn't find the time to finish it up and open a PR..
It would be great if you want to give it a shot! :-)

**Comment by xou816** [comment]
Great, I'll have a look and see if I can figure something out :) thank you!

**Comment by xou816** [comment]
Hi @ashthespy, I opened a PR if you want to have a look! I went with `error-chain` since it was already part of the dependencies, I hope that's fine?
