### ISSUE TITLE
Request to add choice of Track Gain or Album Gain for volume normalisation.

### ISSUE THREAD

**Issue by slartibartfast3** [librespot-org/librespot#572]
I understand that the current implementation of volume normalisation is limited to Track Gain. One of the difficulties mentioned in an earlier issue is knowing when to use Album Gain rather than Track Gain in a playlist. 
One solution to this would be to offer the choice of either Track or Album Gain in the Volume Normalisation settings. 
I am sure this would be a welcome addition to those who still listen to complete albums.

**Comment by giggywithit** [comment]
Isn't there a way to do Album Gain when it's of the same album automatically. I seem to remember players that I used to use years ago with this capability.

**Comment by sashahilton00** [comment]
@giggywithit What do you mean by of the same album?

**Comment by giggywithit** [comment]
Sorry..
Tracks of the same album.

I suppose the easiest solution would be like the op says.. to have an album gain normalization setting. Another idea is to set the method based on normal playback or shuffle. Shuffle wouldn't need album gain normalization, whereas normal playback could imply album gain normalization.

**Comment by sashahilton00** [comment]
Solved by #573
