### ISSUE TITLE
How to check if librespot is currently playing a song

### ISSUE THREAD

**Issue by petrkutalek** [librespot-org/librespot#575]
I would like to ask you if there is any way how I can check via any API if librespot is currently playing a song. _I would like to put my PC into sleep in the evening, but only if and only if it is not currently playing. I plan to use systemd timer with Condition check._

Thanks!

**Comment by FrancisHGR** [comment]
You can check via the Spotify Web API, e.g. 

curl -s -X GET "https://api.spotify.com/v1/me/player" -H "Accept: application/json" -H "Authorization: Bearer $token" where token is a token you need to get from the Spotify Web API website that links to your Spotify account. 

Please refer to an implemented example in the following repo (file controlspotify): https://github.com/FrancisHGR/forked-daapd-raspotify

**Comment by petrkutalek** [comment]
Thank you @FrancisHGR , I appreciate that. Nevertheless, it is too complicated and it does not worth my while. I was wondering if data coming from `curl http://10.2.1.6:4370/?action=getInfo | jq .` could be used in some way.. Probably not. Nevermind.

**Comment by ashthespy** [comment]
@petrkutalek Take a look at [`Vollibrespot`](https://github.com/ashthespy/Vollibrespot) a little daemon I strapped together. It exposes a udp socket that you can listen for status updates and other such things..
