### ISSUE TITLE
Play Playlist by ID from shell

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#58]
<a href="https://github.com/tatoosh"><img src="https://avatars3.githubusercontent.com/u/3670907?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tatoosh](https://github.com/tatoosh)**
_Thursday May 25, 2017 at 07:08 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/188_

----

It would be nice to start a Playlist by parsing the Spotify ID by Argument.

**Comment by sashahilton00** [comment]
<a href="https://github.com/shaunmulligan"><img src="https://avatars1.githubusercontent.com/u/3915043?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shaunmulligan](https://github.com/shaunmulligan)**
_Sunday Jul 16, 2017 at 13:59 GMT_

----

+1 for this feature

**Comment by ComlOnline** [comment]
Control from the command line is out of scope for librespot but see here for external tools #105
