### ISSUE TITLE
Can librespot be used to cast to other spotify-apps, chromecast etc?

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#59]
<a href="https://github.com/kristoffernolgren"><img src="https://avatars2.githubusercontent.com/u/485125?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kristoffernolgren](https://github.com/kristoffernolgren)**
_Friday Jun 09, 2017 at 12:41 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/196_

----

I'm currently using home-assistants and trying to use the built in spotify-connect solution.

Spotifys connct is not working great for casting to initiate casting to new devices. You can basically just manipulate castings that are already up and running. I'm looking at the docs for librespot and can't find any way to start a casting or even play a song from command line. Is this possible? Are there any docs?

**Comment by ComlOnline** [comment]
Please see #105 for more information on this, But short answer is no librespot does not accept commands one running.
