### ISSUE TITLE
Hi I am trying to call Spotify with help of A2Display with google assistant

### ISSUE THREAD

**Issue by badshah424** [librespot-org/librespot#590]
Hi I am trying to call Spotify with help of A2Display with google assistant .
I am new to programming so can you please provide detailed instructions on installation of module in magic mirror such that I can play Spotify with with onboard speakers itself.

**Comment by ashthespy** [comment]
Don't mean to sound rude, but this isn't a support forum, but meant to track issues with the librespot library/binary. 
You would get better help over at the support forum for the other programs you mention..
