### ISSUE TITLE
Extra metadata beyond title/URI

### ISSUE THREAD

**Issue by micronova-jb** [librespot-org/librespot#592]
Hello! First, I'd like to say thanks creating and maintaining such a great project. I am using librespot as part of a different project I'm working on, and we're trying to get metadata from the songs played on Spotify. The typical console output is the song title, URI, and its length in milliseconds. Does Librespot itself gather more data than this? I'm having a difficult time figuring this out. I have found plenty of other projects that accomplish this goal, but they tend to be outside of the scope of what I'm working on. 

The metadata that would be great to have would be:

- [x] Song title
- [ ] Title of the album the song is from
- [ ] Name of the artist of the song
- [ ] Album cover art (not necessary, but would be cool)

Is it possible to accomplish this with just Librespot? Does Spotify keep that information hidden? I appreciate any help/answers you can provide!

**Comment by Johannesd3** [comment]
Are you using librespot as library in other Rust code, or are you just invoking the application?

**Comment by micronova-jb** [comment]
I'm calling it via something like "librespot -n 'test audio' --verbose".
I'm not integrating it into other rust code

**Comment by Johannesd3** [comment]
The simplest solution is probably to use the [official Web API](https://developer.spotify.com/documentation/web-api/reference/#category-player).

**Comment by ashthespy** [comment]
> Is it possible to accomplish this with just Librespot? Does Spotify keep that information hidden? I appreciate any help/answers you can provide!

Yeah it is (with `librespot` the library), but won't be added to Librespot the binary for reasons - #7


I wrapped Librespot into a [little daemon](https://github.com/ashthespy/Vollibrespot) a while back that exposes metadata on a udp socket. Currently all you seek should be included. There are some prebuilt releases, if you want to give it a whirl..
```
"track_id":
"track_name":
"artist_id":
"artist_name":
"album_id": 
"album_name":
"duration_ms": 
"albumartId": 
"position_ms": 
 ```

**Comment by micronova-jb** [comment]
Thank you both for the responses! I can try both of these out to see which works better for my team's project.
@ashthespy I think I will look into your project first :) I'm basically just using a Raspberry Pi as a Spotify Connect device - is it possible to use your daemon without installing Volumio?

**Comment by ashthespy** [comment]
Sure, you don't need Volumio. Pick the right release version based on which Pi your using (`armhf` vs `armv6`).
Have a look at this snippet on how you can [read the metadata with NodeJs](https://github.com/ashthespy/Volumio-SpotifyConnect/blob/next/SpotConnController.js)

**Comment by micronova-jb** [comment]
@ashthespy Sorry for the complete radio silence over the past few months! Things got really crazy at work, and I was working on a lot of the other features for our AmpliPi system (neglecting Spotify). I initially couldn't figure out the vollibrespot integration, but after more digging this week, it's working quite well for me! Your daemon does everything I wanted and more - full metadata (including album art), as well as play/pause/seek integration. Just wanted to come back to this issue to properly thank you for your awesome work :)

**Comment by kingosticks** [comment]
@micronova-jb are you distributing librespot with your system? Any sort of integration should include the [librespot disclaimer](https://github.com/librespot-org/librespot#disclaimer) so users know the risks and understand that what they are using is a reverse-engineered solution which may violate Spotfy's ToS. Everything built on librespot should do this but I think it's particuarly important if you are selling something. I assume you are supposed to pay Spotify a heap of cash to officially use their service in a product and then do so using their (non-public) software.

**Comment by micronova-jb** [comment]
@kingosticks Yes, we are planning on distributing Librespot as part of our open-source project [AmpliPi](https://github.com/micro-nova/AmpliPi). Our business model is to sell the hardware that the open-source software runs on. It is a hobbyist project, and our users understand the limitations; we have recently updated some of our documentation to make it clear that Spotify support is provided by Librespot, including a link to the project and disclaimer in our [README](https://github.com/micro-nova/AmpliPi/blob/master/README.md#features). The only units that currently exist in the field belong to AmpliPi developers.

**Comment by ashthespy** [comment]
@micronova-jb That is good to hear, I have a few more things to sort out regarding sharing of the sink, will happen when I find time ;-)

**Comment by pbattino** [comment]
I'm probably missing something but... Isn't it possible to get notified directly from librespot using the `--onevent=myscript.sh` parameter and then reading metadata from environment variables?

See doc
https://github.com/librespot-org/librespot/wiki/Events

https://github.com/librespot-org/librespot/blob/master/contrib/event_handler_example.py
