### ISSUE TITLE
support for offline playback

### ISSUE THREAD

**Issue by emekoi** [librespot-org/librespot#598]
i have seen #152, but what i am asking is would it be possible to add support for playing the encrypted files that an official client has saved for offline playback? i.e. i tell the spotify client to store its data in `~/Spotify` and later on tell librespot to play audio using that `~/Spotify`? or would that go against the TOS and put librespot at risk? or if not, would using the same folder for 2 separate players, just clobber the data in the folder like the official client does?

**Comment by devgianlu** [comment]
I don't believe anyone has reversed how the files are encrypted and stored to disk by the official client.

**Comment by emekoi** [comment]
so the way that files are encrypted on disk is different from how they are sent over the network? or am i mistaken in thinking that Spotify simply sends encrypted audio data to clients, and they cache and decrypt that audio data and play it back? i thought that since the official client's cache and storage directory file structures were superficially similar to the ones librespot generates that they were the same.

that aside, do you think it would be possible for someone with little to no reverse engineering knowledge or experience (me) to reverse how the official client encrypts and stores files to disk? and if i did, would librespot merge such a PR?
