### ISSUE TITLE
Added link to the Shannon reference implementation

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#60]
<a href="https://github.com/sashahilton00"><img src="https://avatars3.githubusercontent.com/u/4185362?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sashahilton00](https://github.com/sashahilton00)**
_Sunday Jun 11, 2017 at 23:52 GMT_
_Originally opened as https://github.com/plietar/librespot/pull/197_

----

Stumbled across the Qualcomm Shannon Cipher reference implementation whilst rewriting the authentication part of librespot, added a link to a copy of it in my repo.

----

_**[sashahilton00](https://github.com/sashahilton00)** included the following code: https://github.com/plietar/librespot/pull/197/commits_

**Comment by sashahilton00** [comment]
<a href="https://github.com/plietar"><img src="https://avatars0.githubusercontent.com/u/1489775?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [plietar](https://github.com/plietar)**
_Thursday Jun 29, 2017 at 14:59 GMT_

----

What's the original source for this ? I'd rather point to that instead

**Comment by sashahilton00** [comment]
<a href="https://github.com/sashahilton00"><img src="https://avatars3.githubusercontent.com/u/4185362?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sashahilton00](https://github.com/sashahilton00)**
_Thursday Jun 29, 2017 at 18:43 GMT_

----

So would I, but it was pulled from web.archive.org, which isn't the greatest place to rely on for long term hosting... https://web.archive.org/web/20081010141647/http://www.qualcomm.com.au/PublicationsDocs/Shannon-1.0.tgz the original url is http://www.qualcomm.com.au/PublicationsDocs/Shannon-1.0.tgz though it's long gone.

**Comment by ComlOnline** [comment]
Now found here: https://github.com/librespot-org/spotify-connect-resources/tree/master/Shannon-1.0

**Comment by sashahilton00** [comment]
For now, lets put everything in the wiki. Structure not too important. Once we've implemented the main features in the backlog & solved the major bugs, we need to discuss documentation.

**Comment by ComlOnline** [comment]
Done, as its now in the wiki I think that the docs folder should not be removed.

**Comment by sashahilton00** [comment]
Let's leave the docs folder for now, we'll clean it up later.
