### ISSUE TITLE
Include systemd-user service file

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#61]
<a href="https://github.com/WhyNotHugo"><img src="https://avatars1.githubusercontent.com/u/730811?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [WhyNotHugo](https://github.com/WhyNotHugo)**
_Tuesday Jun 13, 2017 at 18:15 GMT_
_Originally opened as https://github.com/plietar/librespot/pull/198_

----

Include a systemd.services file to run as a user

Also document both this and the pre-existing service file and how they should be used.

----

_**[WhyNotHugo](https://github.com/WhyNotHugo)** included the following code: https://github.com/plietar/librespot/pull/198/commits_

**Comment by sashahilton00** [comment]
<a href="https://github.com/maxx"><img src="https://avatars3.githubusercontent.com/u/2896?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maxx](https://github.com/maxx)**
_Thursday Jun 15, 2017 at 04:27 GMT_

----

Also, I believe you mean `systemctl enable` rather than `systemd enable` in the README addition.

Also, my system (raspbian) doesn't allow --now .. I simply `systemctl enable  librespot`

**Comment by sashahilton00** [comment]
<a href="https://github.com/WhyNotHugo"><img src="https://avatars1.githubusercontent.com/u/730811?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [WhyNotHugo](https://github.com/WhyNotHugo)**
_Thursday Jun 15, 2017 at 13:18 GMT_

----

Yup, you're right, it's `systemctl`, not `systemd`. My bad, good catch. 😅

**Comment by ComlOnline** [comment]
Closed as this is similar to #20. Please see there for more discussion.
