### ISSUE TITLE
Trait Errors

### ISSUE THREAD

**Issue by Stateford** [librespot-org/librespot#661]
Hello, I was trying to run the example from play and I tried to use the shorthand for error checking. I did get this error when trying to use it.

Is there any chance that these errors could inherit the Error trait? I don't mind taking a look at making the change myself.

```
error[E0277]: the trait bound `SpotifyIdError: std::error::Error` is not satisfied
  --> src\main.rs:36:49
   |
36 |     let track = SpotifyId::from_base62(&args[3])?;
   |                                                 ^ the trait `std::error::Error` is not implemented for `SpotifyIdError`
   |
   = note: required because of the requirements on the impl of `From<SpotifyIdError>` for `Box<dyn std::error::Error>`
   = note: required by `from`

error[E0277]: the trait bound `NoneError: std::error::Error` is not satisfied
  --> src\main.rs:38:44
   |
38 |     let backend = audio_backend::find(None)?;
   |                                            ^ the trait `std::error::Error` is not implemented for `NoneError`
   |
   = note: required because of the requirements on the impl of `From<NoneError>` for `Box<dyn std::error::Error>`
   = note: required by `from`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `foo`

To learn more, run the command again with --verbose.
```

**Comment by Johannesd3** [comment]
`NoneError` does not belong to us, it's from the standard library. `SpotifyIdError` would of course be possible, and there is certainly room for improvement in error handling.

But for now it's simpler if you use `Option::ok_or`, `Option::ok_or_else` and `Result::map_err`, or a separate error handling crate like `anyhow`.

**Comment by Stateford** [comment]
Yea, so the NoneError makes sense, however it would be a good idea to add it to SpotifyIdError. I'll look at how hard it would be to add.

**Comment by roderickvd** [comment]
@Stateford I took the liberty to assign this one to you, as you offered to look into it.

**Comment by Stateford** [comment]
@roderickvd sure, I don't mind taking a look when I get a chance.

**Comment by Johannesd3** [comment]
We switched to `thiserror` recently, which makes it an easy addition.

**Comment by roderickvd** [comment]
@Stateford is this still something you would like to pursue?

**Comment by roderickvd** [comment]
Fixed in `new-api` @ https://github.com/librespot-org/librespot/commit/62461be1fcfcaa93bb52f32cc2f88b7fdcd6ecd7.
