### ISSUE TITLE
mdns: Failed to register IPv6 receiver

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#67]
<a href="https://github.com/colinramsay"><img src="https://avatars2.githubusercontent.com/u/72954?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [colinramsay](https://github.com/colinramsay)**
_Thursday Jul 13, 2017 at 13:30 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/217_

----

This setup worked until recently. I run this on a Raspberry Pi powered by OSMC, so it could be related to their most [recent update](https://osmc.tv/2017/07/osmcs-june-update-is-here-2/), but it's hard to debug where the problem lies.

```
> /home/osmc/spotify/librespot --name pi --cache /tmp

INFO:librespot: librespot aa86ebf (2017-07-09). Built on 2017-07-13.
WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }
```

After that there's no more output and it doesn't show as a device to connect to. Previously this worked like a charm. Any pointers? Thanks!

**Comment by sashahilton00** [comment]
<a href="https://github.com/jurisv"><img src="https://avatars2.githubusercontent.com/u/643535?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jurisv](https://github.com/jurisv)**
_Thursday Aug 10, 2017 at 08:45 GMT_

----

Same error here.. On a MAC 10.12.6

**Comment by sashahilton00** [comment]
<a href="https://github.com/vkolotov"><img src="https://avatars3.githubusercontent.com/u/1161883?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [vkolotov](https://github.com/vkolotov)**
_Tuesday Sep 12, 2017 at 08:05 GMT_

----

Same error here. RPi with volumio: https://github.com/balbuze/volumio-plugins/issues/82

**Comment by sashahilton00** [comment]
<a href="https://github.com/CelsoSantos"><img src="https://avatars3.githubusercontent.com/u/1015506?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CelsoSantos](https://github.com/CelsoSantos)**
_Tuesday Sep 19, 2017 at 09:11 GMT_

----

I too have this issue on an RPi3 with latest OSMC installed.

**Comment by ComlOnline** [comment]
@CelsoSantos @vkolotov @jurisv @colinramsay Is this still an issue?

**Comment by CelsoSantos** [comment]
I'd need to check the logs to see the exact message but symptoms sound
about right with my not working installation

**Comment by ComlOnline** [comment]
Thank you

**Comment by sashahilton00** [comment]
I'm still seeing this, though I get a slightly diferent variant: ```WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 49, message: "Can\'t assign requested address" } }```

**Comment by johncalvinyoung** [comment]
@sashahilton00 I get the `code: 49` version on MacOS 10.13.2 at the moment, fresh build from master.

**Comment by dulakm** [comment]
Reporting the same issue here: `Mar 04 12:05:08 osmc librespot[12769]: WARN:mdns: Failed to register IPv6 receiver: Error { repr: Os { code: 19, message: "No such device" } }`

**Comment by moritzschaefer** [comment]
Any workaround so far?

**Comment by lrbalt** [comment]
I've had succes on a macbook by using a different mdns crate, i.e. using the ` with-dns-sd` feature

**Comment by virtastimo** [comment]
This fixed it for me:

    osmc@osmc:~$ connmanctl
    connmanctl> services
    *AO Wired                ethernet_xxxxxxxxxxxxx_cable
    connmanctl> config ethernet_xxxxxxxxxxxxx_cable --ipv6 auto
    connmanctl> quit

Apparently ipv6 was disabled for some reason.

**Comment by roderickvd** [comment]
Confirmed that this is fixed when switching to `dns-sd`.

**Comment by StarLabsCentral** [comment]
On MacOS, I built it using this command: 

cargo build --release --features with-dns-sd 

then ran librespot and it worked! Problem solved!

Used this as a reference: https://github.com/librespot-org/librespot/wiki/Compiling#addition-features
