### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by Johannesd3** [librespot-org/librespot#677]
When running Librespot (release mode) and skipping through playlists, the used memory increases slowly but steady. It starts with 2-3MB, but after a while I was able to reach 8MB. 

It seems to happen in both the `dev` and the `tokio_migration` branch.

**Comment by kingosticks** [comment]
8MB sounds like approx. two 'normal' length tracks worth of compressed audio data. Could this be the track prefetching working correctly?

**Comment by Johannesd3** [comment]
I just stopped at 8MB, probably it's possible to reach more. Every time I skip a track, memory usage grows by something between nothing and 0.5MB.

**Comment by kingosticks** [comment]
Maybe share your cache settings and which backend also.

**Comment by Johannesd3** [comment]
I'm using rodio-backend under Windows, no cache enabled.

I tried different configurations out, and it's possible (but I'm not really sure) this is an issue of lewton. With tremor it doesn't exceed 3MB permanently.

**Comment by Johannesd3** [comment]
Actually I think it's only an issue in `dev` and I just imagined the same thing happens in `tokio_migration` when the numbers rose a little. And in `dev` it happens with both `lewton` and `tremor`. So wherever the problem lies, it will probably be fixed by #665.
