### ISSUE TITLE
Error: could not compile protobuf

### ISSUE THREAD

**Issue by MW-SAND** [librespot-org/librespot#678]
I'm using Ubuntu 20.04 and I'm unable to compile librespot with the following command: sudo cargo build --release. If you need any more info please let me know.

error: could not compile `protobuf`.

Caused by:
  process didn't exit successfully: `rustc --crate-name protobuf /root/.cargo/registry/src/github.com-1ecc6299db9ec823/protobuf-2.14.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -Cembed-bitcode=no -C metadata=f69098f2fee967d7 -C extra-filename=-f69098f2fee967d7 --out-dir /home/ubuntu/Wekker/librespot/target/release/deps -L dependency=/home/ubuntu/Wekker/librespot/target/release/deps --cap-lints allow` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by Johannesd3** [comment]
Works fine for me. Did you try it several times or just once? You're log has a strange formatting, but it seems as if it was simply killed.

**Comment by MW-SAND** [comment]
I have tried it several times over the past few weeks.

Thank you for your suggestion. I only have 1 GB ram, however, the library has been compiled a couple of months ago. I tried disabling the overcommit of OOM, but this results in multiple errors, I couldn't even get to the library folder.

**Comment by MW-SAND** [comment]
Compiling librespot-metadata v0.1.6 (/home/ubuntu/Wekker/librespot/metadata)
error: could not compile `librespot-protocol`.

Caused by:
  process didn't exit successfully: `rustc --crate-name librespot_protocol --edi                                                                                             tion=2018 protocol/src/lib.rs --error-format=json --json=diagnostic-rendered-ans                                                                                             i,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -Cembe                                                                                             d-bitcode=no -C metadata=27e66b292c3d66e2 -C extra-filename=-27e66b292c3d66e2 --                                                                                             out-dir /home/ubuntu/Wekker/librespot/target/release/deps -L dependency=/home/ub                                                                                             untu/Wekker/librespot/target/release/deps --extern protobuf=/home/ubuntu/Wekker/                                                                                             librespot/target/release/deps/libprotobuf-f69098f2fee967d7.rmeta` (signal: 9, SI                                                                                             GKILL: kill)
warning: build failed, waiting for other jobs to finish...
error: build failed

okay so I've tried it once again and for some reason, protobuf compiled correctly but now it got an error on librespot-protocol. 

Is this a RAM issue or could it be something else?

**Comment by Johannesd3** [comment]
I really think it's a RAM issue. 
 1. You said yourself that you don't have much RAM.
2. The error does not occur deterministically.
3. The rust process is killed with SIGKILL and that's exactly what a OOM killer would do.
4. protobuf and librespot-protocol belong to the more resource-intensive crates while compiling, so it makes sense that it aborts there.

You could try to google for tricks to compile rust programs with little memory, or if you don't find anything, ask on users.rust-lang.org

**Comment by roderickvd** [comment]
1GB is enough to compile even with all features. Surely this is not a librespot bug.

**Comment by sashahilton00** [comment]
I believe I have encountered this before when I used to use a RPi 2 as a connect receiver. I'd suggest either cross compiling or a swap file of 2G or so, though this won't be great for the SD card if that's what you're running it off. Anyway, closing as this isn't a librespot bug from what I can tell.
