### ISSUE TITLE
There should be a "none" option for "--mixer" switch.

### ISSUE THREAD

**Issue by coderootme** [librespot-org/librespot#695]
When using librespot with a DAC which has no volume control, ``--mixer alsa`` does not work. Also, some people prefer to set their volume only the amplifier to achieve the highest transparency possible and not allow the player to change the volume whatsoever.

For example, mpd allows this by setting in ``/etc/mpd.conf``:

```
audio_output {
        type        "alsa"
        name        "DAC"
        device      "hw:1,0"
        mixer_type  "none"
}
```

Librespot should allow something similar too, i.e. adding another option, for example, ``--mixer none``, which would simply ignore any volume change request from spotify client, and just always send the track at 100% volume into the selected backend.

I reckon this should be extremely easy to implement to the current code, wouldn't break any other features, and would suit many audiophiles.

**Comment by ashthespy** [comment]
There should be a `fixed` option for `--volume-ctrl` does that not work for you?

**Comment by coderootme** [comment]
> There should be a `fixed` option for `--volume-ctrl` does that not work for you?

That is quite a good idea. It should be a valid workaround, but the solution still could be cleaner.

**Comment by roderickvd** [comment]
> > There should be a `fixed` option for `--volume-ctrl` does that not work for you?
> 
> That is quite a good idea. It should be a valid workaround, but the solution still could be cleaner.

I think @ashthespy means to say: `--volume-ctrl fixed` is already there. Combined with `--initial-volume 100 --mixer softvol` this leaves samples untouched. Yes it'd be easy to map this to `--mixer none`. Good opportunity to learn some Rust? 😉

**Comment by ashthespy** [comment]
The `--mixer ` flag is ALSA specific, while the `volume-ctrl` is one level higher. It is how the volume command from Spotify is handled.

You could add add a case to map a "none"  mixer, but I personally feel it's moot..

**Comment by roderickvd** [comment]
> The `--mixer ` flag is ALSA specific, while the `volume-ctrl` is one level higher. It is how the volume command from Spotify is handled, regardless of the backend.

Current behaviour:

```
    --mixer MIXER   Mixer to use (alsa or softvol)
-m, --mixer-name MIXER_NAME
                    Alsa mixer name, e.g "PCM" or "Master". Defaults to
                    'PCM'
```

If no mixer is specified, it defaults to `softvol`.

**Comment by ashthespy** [comment]
Oops, you are right! 

So `--volume-ctrl fixed --initial-volume 100` should result in no steam alteration.

I agree this isn't as succinct as `--mixer none` but don't think it it's worth adding! 
If someone has strong feelings, feel free to add a PR.. ;-)

**Comment by kingosticks** [comment]
The wiki could probably do with some love there, the wording "fixed volume scaling" is not very clear:
Option |   | volume-ctrl | [linear, log, fixed] Choose between a logarithmic  (default), linear, or fixed volume scaling.
-- | -- | -- | --

Something like:
> Choose between a logarithmic scale, linear scale, or fixed volume (no control). Default is logarithmic.

maybe?

**Comment by coderootme** [comment]
> The wiki could probably do with some love there

That would kinda help, but it would still be unclear that ``--volume-ctrl fixed --initial-volume 100`` should "result in no steam alteration", as claimed by @ashthespy. That fact should be stated also. Hardcore audiophiles don't like software volume control, no matter how "good" it is, and having a "fixed volume control set at 100%" still feels worse than having "no volume control", but if that fact was clearly explained somewhere, it could be good enough.

I don't see how complicating things like that is better than simply adding ``--mixer none`` however, especially considering how very little changes it requires and how, in fact, it changes nothing in the code base.

**Comment by Johannesd3** [comment]
You can see [here](https://github.com/librespot-org/librespot/blob/4fc3accc78768bdc995b4151439d368692704d68/playback/src/player.rs#L1158-L1280) and [here](https://github.com/librespot-org/librespot/blob/4fc3accc78768bdc995b4151439d368692704d68/playback/src/mixer/softmixer.rs#L38-L46) what happens to the PCM.

**Comment by JasonLG1979** [comment]
I changed the wiki to read:

Choose between a logarithmic (default), linear, or fixed (no volume control) volume scaling.

**Comment by JasonLG1979** [comment]
With all these options it might not be a bad idea to have a wiki page showing the proper args for a few basic use cases.

**Comment by roderickvd** [comment]
@JasonLG1979 would you like to work on the wiki? I think you've got a pretty good idea of what and how you'd like to document it. You should be able to edit it.

**Comment by JasonLG1979** [comment]
> @JasonLG1979 would you like to work on the wiki? I think you've got a pretty good idea of what and how you'd like to document it. You should be able to edit it.

I have some ideas as far as basically a "common use cases" page or section. 100% fixed volume control with no dynamic volume normalization is certainly a valid use case for faux "bit-perfect" audio from librespot. When the new API is figured out and Spotify rolls out the hifi tier and they presumably use a lossless format like FLAC it will be more compelling because it could actually be bit-perfect.

**Comment by roderickvd** [comment]
Great! I'll add your name to this one. Could do some preparations for the upcoming merge of #685 too.

**Comment by JasonLG1979** [comment]
> Great! I'll add your name to this one. Could do some preparations for the upcoming merge of #685 too.

Get that and the dithering merged and whatever else you want and release `0.3.0` and I'll even do a write up on optimal configurations on a Pi Zero also, being as though it's the official potato. I mean for under $50 someone can create a pretty decent complete Spotify Connect appliance with a Pi Zero that has the real potential to best commercially available off-the-shelf devices.

**Comment by roderickvd** [comment]
Just merged! Great if you could find the time and work on that documentation. Meanwhile we can give everyone some time to test the all the changes in `dev`, then get a `0.3.0` out the door later.

**Comment by JasonLG1979** [comment]
> Just merged! Great if you could find the time and work on that documentation. Meanwhile we can give everyone some time to test the all the changes in `dev`, then get a `0.3.0` out the door later.

Good deal. I'll do it this weekend.

**Comment by roderickvd** [comment]
Thanks for adding this to the [wiki](https://github.com/librespot-org/librespot/wiki/FAQ) @JasonLG1979.

**Comment by JasonLG1979** [comment]
> Thanks for adding this to the [wiki](https://github.com/librespot-org/librespot/wiki/FAQ) @JasonLG1979.

Your welcome but I totally didn't,lol!!! @coderootme did.
