### ISSUE TITLE
Strange inconsistency in song names in INFO log.

### ISSUE THREAD

**Issue by coderootme** [librespot-org/librespot#702]
This is a very low priority bug, but a strange occurrence nonetheless which should probably be looked at either way.

See this `librespot` output:

> [2021-03-23T21:02:37Z INFO  librespot_playback::player] Loading \<Fool **For** Waiting\> with Spotify URI <spotify:track:2ISrBfPX4YBkwiMgvdbV4V>
> [2021-03-23T21:02:37Z INFO  librespot_playback::player] \<Fool **for** Waiting\> (243192 ms) loaded

EDIT: Another one:

> [2021-03-23T23:18:56Z INFO  librespot_playback::player] Loading \<Thank You\> with Spotify URI <spotify:track:1etEtoewwBygCeVD34yEcM>
> [2021-03-23T23:18:56Z INFO  librespot_playback::player] \<Thank You - Original\> (238151 ms) loaded

EDIT: Another even, even stranger:

> [2021-03-24T14:36:56Z INFO  librespot_playback::player] Loading \<Everywhere - Live in Cologne\> with Spotify URI <spotify:track:4ug1cvK9DrXTIWBwHNncII>
> [2021-03-24T14:36:56Z INFO  librespot_playback::player] \<Everywhere - Live in Chicago\> (194946 ms) loaded

How/why did this inconsistency happen and may it cause any other unexpected problems somewhere in the code?

**Comment by Johannesd3** [comment]
Remove this lines:

https://github.com/librespot-org/librespot/blob/4925adb4f103cea20f38eee1db9f09b0d3e07e75/playback/src/player.rs#L675-L681

and look what happens.

**Comment by sashahilton00** [comment]
As @Johannesd3 points out, this is expected behaviour, it's simply the alternative track name.
