### ISSUE TITLE
Feature flag for no backend

### ISSUE THREAD

**Issue by codetheweb** [librespot-org/librespot#706]
This may seem like a bit of an odd request, but would it be possible to add a feature flag for no backend? My use case is that I'm piping the output from librespot somewhere else and don't need alsa / Pulse / whatever.

**Comment by ashthespy** [comment]
So backend `pipe`?

**Comment by shanemeagher** [comment]
Would compiling with  `--no-default-features` do?
https://github.com/librespot-org/librespot/wiki/Compiling#optional-features

**Comment by codetheweb** [comment]
Thank you, that does the trick.
Like I said, still new to the ecosystem. :)

**Comment by ashthespy** [comment]
Doh. I knew i was forgetting something. Sorry for the noise!
