### ISSUE TITLE
Exception when using `~` in cache path

### ISSUE THREAD

**Issue by snadorp** [librespot-org/librespot#707]
librespot is throwing an exception when initializing with a `~` sign in the path.

cache_path = "~/.cache/spotify"

```
Loading config from "/home/user/.config/spotifyd/spotifyd.conf"
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Location: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-core-0.1.5/src/cache.rs:30

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by Johannesd3** [comment]
Using `~` in the path works for me. It's probable another problem: Does the directory `~/.cache` already exist? Librespot 0.1.5 is not able to create multiple dirs in a row for the cache dir, but this is fixed on the `dev` branch.

**Comment by Johannesd3** [comment]
Please reopen if my explanation is wrong.

**Comment by damif94** [comment]
Hi @Johannesd3 I am having the same error message when running `spotifyd --no-daemon`. 

How is this related to a cache directory?
Can you help me solve it 🙏 ?
