### ISSUE TITLE
Distorted audio when using dynamic normalisation

### ISSUE THREAD

**Issue by rbuch** [librespot-org/librespot#745]
Audio sounds highly distorted and seems to be clipping when using the current default dynamic normalisation added in https://github.com/librespot-org/librespot/pull/660. Changing back to using basic normalisation or disabling normalisation altogether fixes the issue.

(Discovered via `ncspot`, the corresponding issue there is: https://github.com/hrkfdn/ncspot/issues/522.)

**Comment by roderickvd** [comment]
Could you please provide the following information:

 1. Complete debug logs;
 2. Whether the issue also occurs on vanilla `librespot`, all else being equal (same pregain, attack, threshold, knee, and so on);
 3. As above, but now also using `--backend alsa` or `--backend rodio` instead of PulseAudio or PipeWire.

Finally, please explain what its meant by "even when in-app volume is set to 0%" in that downstream issue. As I understand it, the audio is distorted even when volume is set to 0 or mute? Does the distortion differ depending on the volume setting?

**Comment by Johannesd3** [comment]
And if you use PipeWire, which backend? IIRC ALSA, Jack, GStreamer, Pulseaudio, or Rodio would be possible.

**Comment by rbuch** [comment]
I did a bit of digging, I couldn't get this to reproduce in vanilla `librespot` with any backend or options. Comparing debug output between `librespot` and `ncspot` uncovered the issue, the `normalisation_threshold` in `ncspot` is incorrect.

`ncspot` initializes `librespot_playback::config::PlayerConfig` with the following code:

```rust
        let player_config = PlayerConfig {
            gapless: cfg.values().gapless.unwrap_or(false),
            bitrate: bitrate.unwrap_or(Bitrate::Bitrate320),
            normalisation: cfg.values().volnorm.unwrap_or(false),
            normalisation_pregain: cfg.values().volnorm_pregain.unwrap_or(0.0),
            ..Default::default()
        };
```

Thus, it uses the default value for `normalisation_threshold` (which is `-1.0`) directly,  whereas `librespot` passes the default value through `NormalisationData::db_to_ratio` when it constructs the object (resulting in `~0.8912509`). Explicitly passing in this adjusted value in the `ncspot` constructor fixes the issue.

So I suppose the question now is can the logic to convert the value from dB to ratio be pushed into an object creation function for `PlayerConfig` to avoid this problem?

**Comment by Johannesd3** [comment]
Why can't ncspot use NormalisationData::db_to_ratio themselves?

**Comment by rbuch** [comment]
> Why can't ncspot use NormalisationData::db_to_ratio themselves?

It can, of course, but it feels like a leaky abstraction for an external application to have to pull a default value out, transform it, and then explicitly pass it back in when it just wants it to be default initialized.

**Comment by roderickvd** [comment]
I agree @rbuch the default should just make sense. This was an oversight on my end. I'll update it later this weekend.

**Comment by roderickvd** [comment]
Thanks for digging around 😅 I was getting worried.

**Comment by roderickvd** [comment]
@rbuch could you please verify #749 and report back there?

**Comment by rbuch** [comment]
> @rbuch could you please verify #749 and report back there?

Building `ncspot` with #749 does indeed fix the default value issue and it all sounds like it should. Thanks for the quick fix!
