### ISSUE TITLE
:Z for docker container on SELinux-enabled distros

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#76]
<a href="https://github.com/axelsimon"><img src="https://avatars3.githubusercontent.com/u/1172256?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [axelsimon](https://github.com/axelsimon)**
_Tuesday Aug 01, 2017 at 15:32 GMT_
_Originally opened as https://github.com/plietar/librespot/pull/230_

----

Added a comment to help run the cross-compile docker container on SELinux-enabled distros (ie: add :Z at the end of the docker volume argument).

----

_**[axelsimon](https://github.com/axelsimon)** included the following code: https://github.com/plietar/librespot/pull/230/commits_

**Comment by ComlOnline** [comment]
Add to the wiki

**Comment by ComlOnline** [comment]
Added.
