### ISSUE TITLE
Can't turn repeat off

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#79]
<a href="https://github.com/D54"><img src="https://avatars1.githubusercontent.com/u/6825569?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [D54](https://github.com/D54)**
_Friday Aug 25, 2017 at 14:51 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/237_

----

Is there any way to make librespot stop playback at the end of a playlist?
It gets `spirc: kMessageTypeRepeat`, but nothing changes when the playlist ended, starts it again.

**Comment by sashahilton00** [comment]
<a href="https://github.com/herrernst"><img src="https://avatars2.githubusercontent.com/u/20795?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [herrernst](https://github.com/herrernst)**
_Saturday Aug 26, 2017 at 09:42 GMT_

----

I'm also not happy with the current behavior (a playlist or album loops endlessly). I guess it wouldn't be hard to implement the Repeat All/Repeat 1/Repeat None feature like in the official Spotify client, but I have not looked into it yet.

**Comment by sashahilton00** [comment]
<a href="https://github.com/herrernst"><img src="https://avatars2.githubusercontent.com/u/20795?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [herrernst](https://github.com/herrernst)**
_Saturday Aug 26, 2017 at 17:21 GMT_

----

I've opened a pull request which changes the hardcoded behaviour to not repeat: #239

**Comment by sashahilton00** [comment]
<a href="https://github.com/D54"><img src="https://avatars1.githubusercontent.com/u/6825569?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [D54](https://github.com/D54)**
_Saturday Aug 26, 2017 at 21:28 GMT_

----

Thank you, I appreciate your fast response and solution!
My main problem has been solved, but it would be great if we can toggle repeat as @herrernst wrote.

**Comment by ComlOnline** [comment]
Please see #81 I think that has solved this issue.
