### ISSUE TITLE
Cannot use librespot if there are multiple librespot devices on the same network with discovery enabled.

### ISSUE THREAD

**Issue by coderootme** [librespot-org/librespot#793]
My current setup is:

- one raspberry pi with librespot connected to my speakers
- another raspberry pi with librespot connected to my headphones

Both devices are on the same network and both devices have discovery enabled and no credentials provided.

When I have both devices online and one is playing music, I am unable to switch playing to the other. I can see it in the spotify app as an available device, but as soon as I choose it, it starts playing for a second, then automatically switches back to the previous device.

I have to shutdown the first device to have the other device start playing successfully.

I can provide more info if anyone tells me what you need.

Thanks!

**Comment by JasonLG1979** [comment]
I can't reproduce either. I run 2 or 3 simulations instances, sometimes on the same machine all the time while testing things and never have any trouble.

Purely anecdotal but some routers don't play well with mDNS. I had nothing but trouble with my wifi router to the point that I ended up just getting a cheap standalone router/switch and just using it as a wireless AP. If you have an old router laying around that's a different brand or can barrow one you might try switching it out to see if it clears things up. At the very least I would check with Google to see if anyone else has had mDNS issues with your router.

**Comment by roderickvd** [comment]
Cannot reproduce and no further replies.
