### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#80]
<a href="https://github.com/krooarbo"><img src="https://avatars2.githubusercontent.com/u/31365711?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [krooarbo](https://github.com/krooarbo)**
_Saturday Aug 26, 2017 at 08:38 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/238_

----

Hi,

First of all sorry for my english.
Yesterday libresport is working, but today not working. There isnt any changes on the system.

RUST_BACKTRACE=1 librespot --backend alsa -n raspotify --username  $MYUSER --password $MYPASS
INFO:librespot: librespot ddfc28f (2017-08-04). Built on 2017-08-07. Build ID: N5RcEuis
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 19, message: "No such device" } }', /checkout/src/libcore/result.rs:860
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: __libc_start_main

Please help!
Thanks in advance!

Br,

**Comment by sashahilton00** [comment]
<a href="https://github.com/krooarbo"><img src="https://avatars2.githubusercontent.com/u/31365711?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [krooarbo](https://github.com/krooarbo)**
_Saturday Aug 26, 2017 at 08:39 GMT_

----

0-12 is \<unknown\>

**Comment by sashahilton00** [comment]
<a href="https://github.com/chimpy"><img src="https://avatars3.githubusercontent.com/u/380577?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chimpy](https://github.com/chimpy)**
_Tuesday Sep 12, 2017 at 22:18 GMT_

----

I have the same error.

**Comment by ComlOnline** [comment]
@krooarbo @chimpy Do you still have this with the latest raspotify released today?

**Comment by chimpy** [comment]
Hey, I’m not sure what was causing this but I have been happily using Raspotify for a while now :) It must have been an error in my config.

**Comment by ComlOnline** [comment]
In that case Ill close it and just reopen it if @krooarbo is still having issues.
