### ISSUE TITLE
alsa dmixer device breaks librespot

### ISSUE THREAD

**Issue by Mitschmaster** [librespot-org/librespot#812]
I have configured a mixer device via asound.conf to allow multiple programs to play audio simultanially through my raspberry equipped with a optical audio out hat. that used to work fine but recently i did a git pull and rebuild librespot. now i get the following error when playing something via librespot:
librespot_playback::player] Fatal error, could not start audio sink: AlsaSink Hardware Parameters Error, ALSA function  'snd_pcm_hw_params_set_periods' failed with error 'EINVAL: Invalid argument'
when i remove the dmixer plugin it works fine. i dont know what commit i was on when it worked. it was something in january or febuary i think.
thanks for help

**Comment by roderickvd** [comment]
@JasonLG1979 could you take a look at this, it might have been introduced by #789.

**Comment by JasonLG1979** [comment]
@Mitschmaster What does your `asound.conf` look like?

That function really should not fail. We ask for a buffer with 4 periods, worse case it should set it the closest thing to 4 or in the case of `dmix` whatever you have `dmix` configured to as far as the buffer setting. I can't reproduce on real hardware or going though `dmix` either though the default or with a [custom `asound.conf`]( https://gist.github.com/JasonLG1979/f29cb0f14218a3b20db5d32c2cfae5ed)

Could you also provide the output of `aplay -Dhw:x,x --dump-hw-params /usr/share/sounds/alsa/Front_Right.wav` Where `hw:x,x` is the actual device you're trying to use. It will probability throw an error but it will give us the device's capabilities.

**Comment by JasonLG1979** [comment]
@Mitschmaster Well I guess I can reproduce if I set the periods to under 4 in `dmix`. I'm pretty sure I know how to fix it. I'll be back with a test branch and if it works for you I'll put in a PR.

**Comment by JasonLG1979** [comment]
Still curious what your `asound.conf` looks like though.

**Comment by JasonLG1979** [comment]
@Mitschmaster try [this branch](https://github.com/JasonLG1979/librespot/tree/alsa_buffer_hot_fix) I'm pretty sure it will fix the issue. If it does I will put in a PR and I'm sure @roderickvd will merge it pretty quickly.

**Comment by JasonLG1979** [comment]
@roderickvd I'm going to go ahead and put in a PR. I tested this by setting a ridiculously small buffer as far as period time and period count and were it crashed before, with that very small change in that branch it does not.

I think my mistake was explicitly asking for 4 periods and assuming people would not do weird things in their `asound.conf `,lol!!!

**Comment by Mitschmaster** [comment]
The fix from @JasonLG1979 works for me. Thank you very much.
Besides, my asound.conf is not that weird. i just have a dmixer plugin. i dont even set buffer sizes or so. (maybe i should)

**Comment by JasonLG1979** [comment]
> my asound.conf is not that weird. i just have a dmixer plugin.

Strange that it would set the period size/count to be less than 4 by default? That seems broken to me.

>  i dont even set buffer sizes or so. (maybe i should)

If it ain't broke don't fix it.

But generally the safe norm is around 4 125ms periods for a total buffer size of around 500ms. A really small buffer will hammer your CPU and really huge buffer will lead to a noticeable delay between pausing and unpausing and manually changing tracks because the PCM has to play out what's in it's buffer before it can do what you actually want it to.

If you notice underruns, distortion or glitches I'd up the period count until it goes away. But I'd keep the buffer under 1000ms otherwise you'll notice that delay I was talking about.

**Comment by JasonLG1979** [comment]
There's your problem. If you don't specify any buffer setting I'm pretty sure it defaults to the device's min.

**Comment by roderickvd** [comment]
I've done nothing with my dmix and it gives me a period size of 1024 and buffer size of 16384 regardless of your PR.

**Comment by JasonLG1979** [comment]
> I've done nothing with my dmix and it gives me a period size of 1024 and buffer size of 16384 regardless of your PR.

See the above comment.

**Comment by JasonLG1979** [comment]
> I've done nothing with my dmix and it gives me a period size of 1024 and buffer size of 16384 regardless of your PR.

So it did not change since the PR or not?

**Comment by roderickvd** [comment]
That's right it was working before, and is working after, with no effect on the period and buffer sizes. But see my other comment over at the PR because it does do something to the sizes for `hw` and `plughw`.

**Comment by JasonLG1979** [comment]
@Mitschmaster I forgot to say thank you for shaking that bug out.

**Comment by Mitschmaster** [comment]
Thanks for fixing it.
