### ISSUE TITLE
warning: redundant linker flag specified for library `portaudio`

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#83]
<a href="https://github.com/montvid"><img src="https://avatars0.githubusercontent.com/u/23270059?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [montvid](https://github.com/montvid)**
_Wednesday Aug 30, 2017 at 19:15 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/241_

----

While compiling latest git version 

> ddfc28f99f283caa81951c63dd03fa913af1b8de

I get this warning. Don't know if I should report it but I did. :)

**Comment by ComlOnline** [comment]
Warning is still present in current builds but is only a warning so nothing to worry about.
