### ISSUE TITLE
Dockerfile to create a docker file for the RPI

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#84]
<a href="https://github.com/romerod"><img src="https://avatars1.githubusercontent.com/u/3213790?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [romerod](https://github.com/romerod)**
_Saturday Sep 02, 2017 at 11:51 GMT_
_Originally opened as https://github.com/plietar/librespot/pull/242_

----

Multistage dockerfile to create a docker image which can be run on the RPI

----

_**[romerod](https://github.com/romerod)** included the following code: https://github.com/plietar/librespot/pull/242/commits_

**Comment by sashahilton00** [comment]
<a href="https://github.com/superlupo12"><img src="https://avatars3.githubusercontent.com/u/19894285?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [superlupo12](https://github.com/superlupo12)**
_Saturday Sep 02, 2017 at 15:31 GMT_

----

What's the use case for this? Why would you want that?

**Comment by sashahilton00** [comment]
<a href="https://github.com/maxx"><img src="https://avatars3.githubusercontent.com/u/2896?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [maxx](https://github.com/maxx)**
_Saturday Sep 02, 2017 at 15:56 GMT_

----

@romerod  I was interested in this at one point, but I found it very difficult to get sound out of a docker container. You would need to use pulse audio sockets or something like that.  Or did you find a better way?

**Comment by sashahilton00** [comment]
<a href="https://github.com/romerod"><img src="https://avatars1.githubusercontent.com/u/3213790?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [romerod](https://github.com/romerod)**
_Saturday Sep 02, 2017 at 18:22 GMT_

----

I'm using this image on a RPI which runs hypriot and is connected by HDMI to my onkyo receiver.

By passing all the devices into the docker instance,  sound works without any problems and by using "host" as network discoverable mode works too

**Comment by ComlOnline** [comment]
This is outside the scope of librespot but its soon to be be sister project librespotd, may handle it eventually? #20.
I'm closing this for now.
