### ISSUE TITLE
Playlist::get panics if the playlist contains tracks from Local Files

### ISSUE THREAD

**Issue by RainbowCookie32** [librespot-org/librespot#845]
Seems like SpotifyId::from_base62() can't handle tracks from local files, since it returns Err. 

This leads to the unwrap() on the [parse function](https://github.com/librespot-org/librespot/blob/e27992a754b840e9c4591ebd32838cadaf51ebe8/metadata/src/lib.rs#L129) called from Playlist::get ([here](https://github.com/librespot-org/librespot/blob/e27992a754b840e9c4591ebd32838cadaf51ebe8/metadata/src/lib.rs#L297)) to cause a panic and crash my application with:

```
thread 'main' panicked at 'called 'Result::unwrap()' on an 'Err' value: SpotifyIdError', /home/rainbowcookie/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-metadata-0.2.0/src/lib.rs:296:54
```

It'd be nice for the error to be handled instead of just panicking. I don't know if handling local files is possible, but even just ignoring tracks whose SpotifyId returns Err would be a better stop-gag solution in my case.

**Comment by roderickvd** [comment]
Yeah, seems right. Do you know your way around Rust to submit a PR? I see more than one Rust project listed on your GitHub profile 😉

**Comment by RainbowCookie32** [comment]
I can give it a spin. Would replacing
```
SpotifyId::from_base62(uri_parts[2]).unwrap()
```
with
```
if let Ok(id) = SpotifyId::from_base62(uri_parts[2]) {
  track
}
```
be good enough in your opinion? Not gonna lie, I've barely used map() (or most functions with iterators) in my time with Rust.

**Comment by ashthespy** [comment]
Try looking at [`filter_map`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.filter_map) :-)

**Comment by RainbowCookie32** [comment]
I knew there had to be a nicer way 😅 

Seems to work fine, will PR it. Thanks for the help guys!
