### ISSUE TITLE
Failed to enable unit: File spotify.service: Invalid argument

### ISSUE THREAD

**Issue by razserv2010** [librespot-org/librespot#847]
I installed openhabian OS on Raspberry Pi 4B
I added a user named ledfx and on it I installed liberspot and I can not install service
when I do:
`sudo systemctl enable spotify.service
`
I get an error:
`Failed to enable unit: File spotify.service: Invalid argument
`
this is the location of the service:
`sudo nano /etc/systemd/system/spotify.service
`
and this is the service:

```
[Unit]
 
Description=Spotify Server Service 
After=network.target sound.target 
StartLimitIntervalSec=0
 
[Service]
 
Type=simple 
Restart=always 
RestartSec=3 
User=ledfx
Group=audio 
Environment=XDG_RUNTIME_DIR=/run/user/1000 
ExecStart=/home/ledfx/.cargo/bin/librespot \ 
        -n ledfx \ 
        -b 320 \ 
        --volume-ctrl=linear \ 
        --device-type=avr \ 
        --initial-volume=90 
        --mixer-card=hw:0,0 
 #     --mixer=softvol \ 
 #     --mixer-name=HDMI 

[Install] 
WantedBy=multi-user.target 
```

Would appreciate help

**Comment by kingosticks** [comment]
Use https://github.com/dtcooper/raspotify

**Comment by roderickvd** [comment]
Yeah, please try that. I think there's something up with your `spotify.service` permissions, but we don't provide Linux system support here. Feel free to try on [Gitter](https://gitter.im/librespot-org/spotify-connect-resources) though.
