### ISSUE TITLE
How to install the binaries from GitHub 

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#85]
<a href="https://github.com/1liminal1"><img src="https://avatars2.githubusercontent.com/u/10505942?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [1liminal1](https://github.com/1liminal1)**
_Tuesday Sep 05, 2017 at 02:18 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/244_

----

Hi guys, 

How do I install this, found a fork with the compiled binaries, but no idea how to get this install on a headless Pi Zero

Thanks

**Comment by sashahilton00** [comment]
<a href="https://github.com/1liminal1"><img src="https://avatars2.githubusercontent.com/u/10505942?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [1liminal1](https://github.com/1liminal1)**
_Wednesday Sep 06, 2017 at 03:17 GMT_

----

Hi guys, 

```
wget https://github.com/herrernst/librespot/releases/download/v20170717-910974e/librespot-linux-armhf-raspberry_pi.zip
```

Here is a fork with compiled binaries, running wget will download this for you, then just unzip the file and run. 

Hope this can help someone :)

**Comment by ComlOnline** [comment]
Closed as solved.

**Comment by KhomZ** [comment]
i'm also trying to know this??
Anyone please share how to install i=binaries in github??

**Comment by roderickvd** [comment]
We don't provide precompiled binaries. If this ever worked by getting the artefacts from the test workflow, than that is something we don't support.
