### ISSUE TITLE
What changes are needed for free support ?

### ISSUE THREAD

**Issue by Velka-DEV** [librespot-org/librespot#853]
Hello guys, after reading the issues #261 and #415, I would have liked to know if anyone finally took care of doing the reverse engineering work for free account support. I would be happy to help with the integration of pubs, limited skips etc. I'm not very good at reverse engineering, so would require some help. (Also i think the spotify-analyze, is not really up to date (or maybe i'm too much retarded to use it aha))

Any help would be appreciated, thanks

**Comment by roderickvd** [comment]
No, and the [README ](https://github.com/librespot-org/librespot/commit/2541f123bcbb69454de901f48785988df61a7d68#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) has been clarified to read that we won't support this:

> Note: librespot only works with Spotify Premium. This will remain the case. We will not support any features to make librespot compatible with free accounts, such as limited skips and adverts.

If you would be willing to donate your time, then we can use all the help to implement the [new API](https://github.com/librespot-org/librespot/tree/new-api) with support for social play and the groundwork for Spotify HiFi in the future!

**Comment by roderickvd** [comment]
Also you're right that `spotify-analyze` is out-of-date. It could use a refresh. In the meantime, I resort to [`librespot-java`](https://www.google.com/search?q=librespot-java&oq=librespot-java&aqs=edge.0.69i59j0i30l3j69i60l3.1208j0j9&sourceid=chrome&ie=UTF-8) as an authoritative reference of the new Spotify API.

**Comment by Velka-DEV** [comment]
> Also you're right that `spotify-analyze` is out-of-date. It could use a refresh. In the meantime, I resort to [`librespot-java`](https://www.google.com/search?q=librespot-java&oq=librespot-java&aqs=edge.0.69i59j0i30l3j69i60l3.1208j0j9&sourceid=chrome&ie=UTF-8) as an authoritative reference of the new Spotify API.

If i'm not wrong @roderickvd, librespot-java don't support free accounts too.

**Comment by roderickvd** [comment]
> > Also you're right that `spotify-analyze` is out-of-date. It could use a refresh. In the meantime, I resort to [`librespot-java`](https://www.google.com/search?q=librespot-java&oq=librespot-java&aqs=edge.0.69i59j0i30l3j69i60l3.1208j0j9&sourceid=chrome&ie=UTF-8) as an authoritative reference of the new Spotify API.
> 
> If i'm not wrong @roderickvd, librespot-java don't support free accounts too.

That's right, member of the same "librespot organisation". I was referring to `librespot-java` for the new API, not for free accounts.

> What is the process to reverse the spotify app ? Do you have any methods to get endpoints etc ?

Others are better at that than me. For the most part, it's inspecting Mercury frames, running Wireshark, and looking at web socket traffic. Myself, I look at `librespot-java` and try to port it.

**Comment by Velka-DEV** [comment]
Does librespot-java use the new API ? Because when i sniff the HTTP requests on the mobile application i find differents endpoints like "{base}/playplay/{hash}" that i don't find in the librespot-java. I know librespot is based on the desktop application but it should be the same SDK for both i think.

I need to work on my reverse skills, i'm really week aha

**Comment by devgianlu** [comment]
They do not use the same API. There's also a new new API which is entirely HTTP and I haven't fully implemented (there are a couple of PRs open for that). @roderickvd is referring to the new API, which includes some HTTP and WS, but not as much as the new new API.

**Comment by Velka-DEV** [comment]
> They do not use the same API. There's also a new new API which is entirely HTTP and I haven't fully implemented (there are a couple of PRs open for that). @roderickvd is referring to the new API, which includes some HTTP and WS, but not as much as the new new API.

Thanks for you precions, your help is really appreciated. Do have you any recommendations for reversing the android app ?

**Comment by devgianlu** [comment]
> > They do not use the same API. There's also a new new API which is entirely HTTP and I haven't fully implemented (there are a couple of PRs open for that). @roderickvd is referring to the new API, which includes some HTTP and WS, but not as much as the new new API.
> 
> Thanks for you precions, your help is really appreciated. Do have you any recommendations for reversing the android app ?

MITM is your best friend in my opinion m

**Comment by Velka-DEV** [comment]
> > > They do not use the same API. There's also a new new API which is entirely HTTP and I haven't fully implemented (there are a couple of PRs open for that). @roderickvd is referring to the new API, which includes some HTTP and WS, but not as much as the new new API.
> > 
> > 
> > Thanks for you precions, your help is really appreciated. Do have you any recommendations for reversing the android app ?
> 
> MITM is your best friend in my opinion.

Yeah i already started using an HTTP sniffer for that (If it's what you mean), i got endpoints but the problem is to get the data. For the protobuff i tried to use https://github.com/marin-m/pbtk and that work on the desktop app but not on the mobile app it's a bit strange. Maybe if i'm lucky the proto are the same as desktop version.

**Comment by 89z** [comment]
Regarding ProtoBuf, I have a package here:

https://github.com/89z/parse/tree/master/protobuf

it works with quite complex responses, even with deprecated StartGroup tags. However its not Python, so I dont know if you will be able to use it.
