### ISSUE TITLE
Audio slider on Spotify client always set to max volume

### ISSUE THREAD

**Issue by cosileone** [librespot-org/librespot#854]
When I try to change the volume on Spotify it snaps back to 100% volume

![spotify volume](https://user-images.githubusercontent.com/1733876/134593654-9e4dc923-cb6a-464d-9ad5-0d05e8b889fe.gif)

**Comment by roderickvd** [comment]
Please provide the full command line you are launching `librespot` with, as well as a full verbose log.

**Comment by cosileone** [comment]
This might not be the right place to bring up the issue then since I'm using this client which is a menu bar app

https://widgetworx.com/projects/libre_spot.html

**Comment by roderickvd** [comment]
Yes, that is unrelated to this project.
