### ISSUE TITLE
Volume 100 too low

### ISSUE THREAD

**Issue by AndreKR** [librespot-org/librespot#855]
I have adjusted alsamixer in a way that other players on the system, like Rhasspy, Mopidy, `aplay`, etc. are each playing with a reasonable volume range. With Librespot however when I turn the volume in Spotify to maximum the actual volume coming out of the speakers is more like what would be 20-30% in e.g. Mopidy.

**Comment by roderickvd** [comment]
Please provide:

1. the full command line you are launching librespot with;
2. the full verbose log;
3. your Alsa configuration file.

Also, the Alsa mixer has been completely rewritten in `dev`. Is there any difference between the latest `dev` and currently released `0.2.0`?

**Comment by AndreKR** [comment]
`/usr/bin/librespot --name Kitchen --device-type speaker --backend alsa --bitrate 160 --cache /var/cache/raspotify --enable-volume-normalisation --normalisation-pregain 6 --volume-ctrl linear --initial-volume=50 --username [redacted] --password [redacted]`

I added the `--normalisation-pregain 6` later in order to get louder output, but it didn't really work too well.

```text
Sep 27 16:56:40 raspberrypi systemd[1]: Starting Raspotify...
Sep 27 16:56:40 raspberrypi systemd[1]: Started Raspotify.
Sep 27 16:56:40 raspberrypi librespot[1511]: [2021-09-27T15:56:40Z INFO  librespot] librespot (raspotify v0.16.0) 0adb851 (2020-12-15). Built on 2020-12-30. Build ID: KLdkAvgt
Sep 27 16:56:40 raspberrypi librespot[1511]: [2021-09-27T15:56:40Z INFO  librespot_core::session] Connecting to AP "gew1-accesspoint-a-bsrj.ap.spotify.com:4070"
Sep 27 16:56:40 raspberrypi librespot[1511]: [2021-09-27T15:56:40Z INFO  librespot_core::session] Authenticated as "[redacted]" !
Sep 27 16:56:40 raspberrypi librespot[1511]: [2021-09-27T15:56:40Z INFO  librespot_playback::audio_backend::alsa] Using alsa sink
Sep 27 16:56:40 raspberrypi librespot[1511]: [2021-09-27T15:56:40Z INFO  librespot_core::session] Country: "DE"
Sep 27 17:07:00 raspberrypi librespot[1511]: [2021-09-27T16:07:00Z INFO  librespot_playback::player] Loading <Watashi No Uso (Your Lie in April Original Soundtrack)> with Spotify URI <spotify:track:08hlaHY7ssHzr2MvBKyKvt>
Sep 27 17:07:00 raspberrypi librespot[1511]: [2021-09-27T16:07:00Z WARN  librespot_playback::player] Reducing normalisation factor to prevent clipping. Please add negative pregain to avoid.
Sep 27 17:07:00 raspberrypi librespot[1511]: [2021-09-27T16:07:00Z INFO  librespot_playback::player] <Watashi No Uso (Your Lie in April Original Soundtrack)> (240071 ms) loaded
```

If you mean `/etc/asound.conf`, it's:
```
defaults.pcm.card 1
defaults.ctl.card 1
defaults.pcm.ipc_perm 0666
```

The first two lines set the default soundcard, the last line allows playback from Docker containers.

**Comment by ashthespy** [comment]
You don't seem to be using the hardware mixer in this example. 
So the volume in the librespot (0 - 100) is mapped to the current alsa mixer volume.

**Comment by AndreKR** [comment]
Correct, none of my applications is controlling the hardware mixer, it is set to a fixed value.

But still "volume 100%" in Mopidy is blowing my eardrums and "volume 100%" in Raspotify/librespot is calm background noise.

**Comment by ashthespy** [comment]
AFAIK, if nothing is touching the mixer, then the software mixer should just map 100 to the current volume. 
So if you set the mixer to 80% - then 100% in librespot is 80% of the actual mixer. 

But, again I could be wrong with the new revamped implementation. You could confirm with a simple experiment with `amixer`, mopidy and librespot..

**Comment by roderickvd** [comment]
@ashthespy is correct, I have nothing to add to that.

Your `asound.conf` is plain & simple so I don't understand what you mean by "I have adjusted alsamixer in a way that other players on the system". But I am sure that you will need to either use:
 1. `--mixer alsa` (if Raspotify supports that -- I just don't know) or
 2. pump up `alsamixer` to 100% and then control volume using `librespot` `softvol`.

Raspotify documents this too: https://github.com/dtcooper/raspotify#troubleshooting

> My volume on Spotify is 100% and it's still too quiet!
>> Have you tried turning the volume up using the command alsamixer?

I'm closing this for now because I'm 99% certain that this isn't a bug in `librespot` and either of above options will do what you want.

**Comment by roderickvd** [comment]
As a follow-up, unless you have some specific requirement I think you'll want to use a `log` volume control and not `linear`. Also see: https://github.com/librespot-org/librespot/wiki/Options#volume-control

**Comment by AndreKR** [comment]
What I meant is: I have deliberately set `alsamixer` to 45%. Because then, when I play with Mopidy at 100% volume, it is the absolute maximum volume that I want to put my speakers, ears and neighbors through. If I then play the same song from Spotify with Raspotify/librespot at 100% it is so quiet you can talk comfortably in the room.

Now you could say it's just that the MP3 that I'm playing with Mopidy is very very loud, but it's always the same, whether I play an MP3 or play from YouTube (with Mopidy) or play a voice announcement with Rhasspy or `aplay` or play from Bluetooth with [bt-speaker](https://github.com/lukasjapan/bt-speaker). It's only Raspotify that is so quiet, all other sources share about the same idea of "100% volume".

**Comment by ashthespy** [comment]
Not sure what mopidy is doing, but open up `alsamixer `  and confirm thet they both don't touch your mixer. 

Another check can be to completely turn off volume control via librespot and confirm nothing funky is going on..

**Comment by AndreKR** [comment]
> Not sure what mopidy is doing, but open up alsamixer and confirm thet they both don't touch your mixer.

I can confirm that, it stays at 45 the entire time.

> As a follow-up, unless you have some specific requirement I think you'll want to use a log volume control and not linear. 

I tried both and I liked `linear` better. With linear the "good" volumes are distributed over a wider range, so if for example I give a voice command "louder", which will increase the volume by 5%, it's always a good amount. With the `log` volume control going from 95% to 100% has a too strong effect and but going from 45% to 50% has almost no effect.

**Comment by roderickvd** [comment]
Can you try the latest `librespot` by compiling from `dev`?

Also curious what happens if you disable normalisation altogether. I'm not sure which `librespot` Raspotify v0.16.0 is based 
on, but from the basic logs it seems like it's on `librespot` 0.1.x. That only has the basic limiter and not the new dynamic limiter. If so, upping the pregain will do the opposite from what you want, because it will drop the volume of the entire track based on the highest peak +6 dB.

Finally, that full verbose log would be good.

**Comment by AndreKR** [comment]
Yeah, I'll set up a build and check again, maybe it's just the old version.

The log I posted isn't the one you were looking for?

**Comment by roderickvd** [comment]
I don't think Raspotify is at `librespot` 0.2.0 yet: https://github.com/dtcooper/raspotify/issues/394, maybe @JasonLG1979 can tell - he's an avid Raspotify user.

Please launch with `--verbose` for a full debug log.

Have you tried without normalisation?

**Comment by JasonLG1979** [comment]
@AndreKR I suspect that normalization is the issue. Refer to @roderickvd's comments. Without any sort of dynamic effects (limiting/compression) just lowering the volume by just a few dB is pretty noticeable as -6dB is the equivalent to 1/2 the wattage and -10dB is about half the perceived volume.

**Comment by AndreKR** [comment]
Progress report: I'm [having trouble](https://github.com/dtcooper/raspotify/issues/429) building Raspotify. Instead I'll build librespot myself. Unlike Python/pip I do actually know Rust/cargo.

**Comment by JasonLG1979** [comment]
> Progress report: I'm [having trouble](https://github.com/dtcooper/raspotify/issues/429) building Raspotify. Instead I'll build librespot myself. Unlike Python/pip I do actually know Rust/cargo.

You can always just install raspotify and then replace the binary with a version you build yourself. That's what I do when I'm doing prolonged tests on things. You have to make sure to use [the proper args though](https://github.com/librespot-org/librespot/wiki/Options) in `/etc/default/raspotify`. They have changed since the version that is included in raspotify.
