### ISSUE TITLE
No Autoplay Similar Songs

### ISSUE THREAD

**Issue by fruitofgeorge** [librespot-org/librespot#856]
I've selected the appropriate option in my settings but when playing to my raspotify device, it never autoplays similar songs when the queue ends.

**Comment by roderickvd** [comment]
Maybe you should file this issue report with Raspotify. I certainly never had issues with autoplay but I run `librespot` as-is. 

If the issue persists then please try running `librespot` yourself and post the full command line and verbose logs here.

**Comment by roderickvd** [comment]
I'm closing this for now, as I can't reproduce this and have received no feedback. Please feel free to re-open if the issue persists and you can provide the information requested above.
