### ISSUE TITLE
Allow avahi support using dns-sd for Discovery

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#86]
<a href="https://github.com/shanemeagher"><img src="https://avatars3.githubusercontent.com/u/2144292?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [shanemeagher](https://github.com/shanemeagher)**
_Tuesday Sep 05, 2017 at 15:13 GMT_
_Originally opened as https://github.com/plietar/librespot/pull/246_

----

rust-mdns is still the default but can also be specified explicitly with
`--feature "with-internal-mdns"` switch at build time.

Added `--feature "with-external-mdns"` switch to build librespot to use
avahi for discovery using dns-sd package.

This commit does not provide option for building without mdns.

This pull request replaces pull request https://github.com/plietar/librespot/pull/201 started by @awiouy  and has been rebased on the current master branch.

----

_**[shanemeagher](https://github.com/shanemeagher)** included the following code: https://github.com/plietar/librespot/pull/246/commits_

**Comment by sashahilton00** [comment]
<a href="https://github.com/shanemeagher"><img src="https://avatars3.githubusercontent.com/u/2144292?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [shanemeagher](https://github.com/shanemeagher)**
_Wednesday Sep 06, 2017 at 14:00 GMT_

----

@plietar,
It seems I'm still having an issue when building with `--no-default-features`. As mdns is optional and not a dependency of an enabled feature (`with-internal-mdns`) in `cargo.toml`, cargo doesn't pass it to rustc. 

In `src/lib.rs`, I've used `cfg-if` to reference mdns:
```
cfg_if! {
    if #[cfg(feature = "with-internal-mdns")] {
        extern crate mdns;
    } else if #[cfg(feature = "with-external-mdns")] {
        extern crate dns_sd;
    } else {
        extern crate mdns;
    }
}
```
resulting in this error: https://travis-ci.org/plietar/librespot/jobs/272099406#L929

In the PR201, you asked:
> Did you use `#[cfg(mdns)]` around the `extern crate mdns` ?
Would this not have just checked if the dependency `mdns` was enabled? Which it isn't?

Is there a way to make one of the features a default requirement if none is specified?

**Comment by awiouy** [comment]
Documentation for #13 
Could be closed

**Comment by ComlOnline** [comment]
Thank you @awiouy.
