### ISSUE TITLE
Play Queue inconsistencies with Android and librespot.

### ISSUE THREAD

**Issue by theBertrum** [librespot-org/librespot#861]
Hello good people,

I have come over from the community at the moOde Forum to report some behaviour we have spotted when using the Spotify Android app in conjunction with librespot.  The discussion relating to this can be read here: https://moodeaudio.org/forum/showthread.php?tid=4215 (some useful screenshots at post 10).

To reproduce the issue, first start playing a playlist (or album) by playing the first item in the playlist, this should start playing and then add the subsequent tracks into the queue as "next from".
Now connect the session to librespot (in our case via moOde) and browse to the play queue using the Android app, you will find all the "next from" items are inert.
Connect to the same session using a different Spotify client (the Spotify Web Player for example) and browse to the play queue, those same "next from" items can be interacted with.
Finally disconnect from librespot, or connect to another connect device and notice that the items are no longer inert even on the Android app.

**Comment by roderickvd** [comment]
I can confirm this. In part #701 is the same issue. I'm not sure we can get this to work under the current Spotify API, so I'm tagging this as work to be done under the `new-api` efforts.

**Comment by theBertrum** [comment]
Thanks for looking, I thought #701 had a similar feel.  I'll report back on the moOde forum and we shall wait patiently.
