### ISSUE TITLE
HDMI sound only, never on jack (default rpi audio output)

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#89]
<a href="https://github.com/CelsoSantos"><img src="https://avatars3.githubusercontent.com/u/1015506?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [CelsoSantos](https://github.com/CelsoSantos)**
_Tuesday Sep 19, 2017 at 09:46 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/249_

----

I don't know if this is somehow related to #217 but for some reason I can't make audio output through jack on my RPi3 with latest OSMC installed. Only HDMI works.

I've tried running with `--device hw:0` without success.

After some reading around, I've tried checking my output devices with `aplay -L` having the following output:

```
osmc@osmc:~/.kodi$ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
sysdefault:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device
dmix:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample mixing device
dmix:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample mixing device
dsnoop:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct sample snooping device
dsnoop:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct sample snooping device
hw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Direct hardware device without any conversions
hw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Direct hardware device without any conversions
plughw:CARD=ALSA,DEV=0
    bcm2835 ALSA, bcm2835 ALSA
    Hardware device with all software conversions
plughw:CARD=ALSA,DEV=1
    bcm2835 ALSA, bcm2835 IEC958/HDMI
    Hardware device with all software conversions
```

From this I've already tried a bunch of different configurations where the `--device` parameter will contain any of the names present in this list. I still can't make the sound output go through Jack.

How can I achieve this? It's really important to me to keep the TV off while playing music so I don't want to rely on HDMI for audio output as I have a set of speaker only for this.

**Comment by sashahilton00** [comment]
<a href="https://github.com/awiouy"><img src="https://avatars0.githubusercontent.com/u/9913019?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [awiouy](https://github.com/awiouy)**
_Wednesday Sep 20, 2017 at 20:18 GMT_

----

https://www.raspberrypi.org/documentation/configuration/audio-config.md
Have you tried the following command:
`amixer cset numid=3 0`

**Comment by sashahilton00** [comment]
<a href="https://github.com/CelsoSantos"><img src="https://avatars3.githubusercontent.com/u/1015506?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [CelsoSantos](https://github.com/CelsoSantos)**
_Friday Sep 22, 2017 at 18:25 GMT_

----

Hello @awiouy , Yes I have, I still only get HDMI sound :(

I'm using OSMC and I really don't see a way I can get the audio through the default jack to work unfortunately..

**Comment by sashahilton00** [comment]
<a href="https://github.com/berrnd"><img src="https://avatars2.githubusercontent.com/u/2161815?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [berrnd](https://github.com/berrnd)**
_Sunday Oct 01, 2017 at 15:13 GMT_

----

Hi,

had the same problem ... for me the in the [Raspberry Pi documentation](https://www.raspberrypi.org/documentation/configuration/audio-config.md) referenced commands worked ... see [my comment](https://github.com/dtcooper/raspotify/issues/22#issuecomment-333382941) in dtcooper/raspotify#22.

**Comment by ComlOnline** [comment]
@CelsoSantos Do you still get this issue?

**Comment by CelsoSantos** [comment]
Hello, to be really honest I can't remember but I think I did though I
can't recall how.
However the plugins seems to have stopped working meanwhile and I haven't
tested back yet since as I've been flooded with work and school.

I can recheck but that will take me a while to have the time to do it.

Best Regards.

**Comment by ComlOnline** [comment]
If you could re check that would be great! Ill leave this open for now.

**Comment by sashahilton00** [comment]
@CelsoSantos have you had a chance to try it out?

**Comment by bspans** [comment]
This works for my Rpi2 running OSMC.
