### ISSUE TITLE
Can't play Podcasts

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#90]
<a href="https://github.com/michaelherger"><img src="https://avatars3.githubusercontent.com/u/2789989?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [michaelherger](https://github.com/michaelherger)**
_Friday Sep 22, 2017 at 08:21 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/250_

----

I can't play Spotify's Podcasts on librespot. When playing in the desktop app, librespot based clients would be visible in the "Devices Available" list, but greyed out. And when a librespot based client is active, I can't start playback of podcasts. 

Trying to play a podcast to librespot wouldn't log anything in librespot, not even in verbose mode. I must assume that Spotify wouldn't send any data for whatever reason.

**Comment by sashahilton00** [comment]
<a href="https://github.com/herrwusel"><img src="https://avatars1.githubusercontent.com/u/8242787?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [herrwusel](https://github.com/herrwusel)**
_Wednesday Oct 25, 2017 at 06:59 GMT_

----

Doesn't seem to be a problem of librespot alone:
https://www.google.com/search?q=spotify+connect+problems+podcast

**Comment by sashahilton00** [comment]
<a href="https://github.com/funtax"><img src="https://avatars0.githubusercontent.com/u/419376?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [funtax](https://github.com/funtax)**
_Monday Nov 13, 2017 at 18:23 GMT_

----

To support Podcasts, one has to add "audio/episode" into the supported methods, beside eg. "audio/track".
Once done, the tracks sent by Spotify have not "gid" but an "uri" instead.

Right now I have no idea how to handle them, maybe some more investigation via the sniffing-tools can bring light on this.

**Comment by Schluggi** [comment]
One year later and nothing happens?
Is there no one with an idea how to implement this feature?

**Comment by devgianlu** [comment]
@Schluggi I've started implementing this in `librespot-java` (see https://github.com/librespot-org/librespot-java/pull/65). It's far from complete, but the playback is working.

**Comment by ReasonableHippo** [comment]
I added a pull request with rudimentary podcast support. 
Someone with rust skills will have to implement it again, but it works for now.
https://github.com/librespot-org/librespot/pull/339

**Comment by beckerhe** [comment]
Hi, thank you very much for implementing that feature!
Works great so far.

**Comment by Schluggi** [comment]
Also a big thanks! You made my day!

**Comment by SirWindfield** [comment]
Looks like the work around isn’t working anymore: https://github.com/Spotifyd/spotifyd/issues/407

**Comment by ashthespy** [comment]
@SirWindfield which workaround? Just tried with https://github.com/librespot-org/librespot/pull/381 and seems to _still_ work? 
windows `1.1.17.545.g74ed9ff1` and `8.5.28.985` on Android

**Comment by SirWindfield** [comment]
Someone reported that it wouldn't work anymore. Maybe it's an issue on our side, which would be quite weird because we didn't change anything that might have impacted podcast playback.

I thought that some API change might be happening here. I'll double check and report back if I find something that indicates that podcast playback doesn't work in all cases.

**Comment by ReasonableHippo** [comment]
Hi,
I can confirm, that it is no longer working. It was working for me yesterday, when it was reported, but today it is not. I'm guessing, that the API change is slowly beeing rolled out. 
I did some digging, and found out that the URI changed to 
"spotify:collection:podcasts:episodes". 
After I added this, I could load podcasts again, if i switched from playing a regular song connected to librespot. I'm guessing that another new supported context is needed to get rid of the "can't connect" message.

**Comment by ReasonableHippo** [comment]
> @SirWindfield which workaround? Just tried with #381 and seems to _still_ work?
> windows `1.1.17.545.g74ed9ff1` and `8.5.28.985` on Android

The current build from #381 does not work anymore either.

**Comment by willstott101** [comment]
I've seen that URI before in #339 I think I was always getting it when playing from certain pages in the client,

**Comment by JPW21** [comment]
I just installed raspotify today, but podcast aren't working...
Is this another spotify API change or a problem with my installation?
thx for the software <3
