### ISSUE TITLE
API to retrieve song lyrics

### ISSUE THREAD

**Issue by gdesmott** [librespot-org/librespot#900]
Would be great to have an API to retrieve song lyrics, with proper time codes.
Looks like it's possible as [this js package does it](https://www.npmjs.com/package/spotify-lyrics-api).

**Comment by roderickvd** [comment]
This is in the `new-api` branch that is currently being developed: #891

Thanks for the link though, it's got a more basic HTTP lyrics endpoint as well as a search endpoint that I will implement.

**Comment by roderickvd** [comment]
The APIs are now in `dev` (see the `spclient`) and return a JSON response. I intend to add a native Rust struct in `metadata` later. Some work on this was already done in the `new-api` discussion, feel free to contribute! (also a great starting point for Rust or `librespot` newcomers)
