### ISSUE TITLE
Option for forcing port to listen on

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#91]
<a href="https://github.com/Robbiedobbie"><img src="https://avatars0.githubusercontent.com/u/4340484?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Robbiedobbie](https://github.com/Robbiedobbie)**
_Saturday Sep 23, 2017 at 11:11 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/253_

----

Currently, librespot listens on 5353 and a random port. This makes running it on a pc with firewall difficult. It would be nice if there was an option to select a specific port instead. 

I've never programmed in rust before, so I haven't made a PR for it. Currently locally I solved it by simply putting my port instead of 0 in the following piece of code: `TcpListener::bind(&"0.0.0.0:0".parse().unwrap(), handle)?;`.

**Comment by ComlOnline** [comment]
Runtime flag to be added
```
--zeroconf-port <int>
```

**Comment by sashahilton00** [comment]
This has been requested a few times, we should implement this as it's pretty trivial to do so. Runtime flag of ```--zeroconf-port``` suggested. Usage would be as follows: ```./librespot --name "Librespot" --zeroconf-port 5353``` one thing we must remember though is that any port number lower than 1024 are priviledged, so we should probably add some logic that rejects ports < 1024 and kicks out a warning that their chosen port has been ignored, then let the OS choose as it already does.

**Comment by michaelherger** [comment]
In addition to allowing specification of the port to listen on, librespot should not die if it fails to open that port. IMHO an error message logged should be good enough.

**Comment by michaelherger** [comment]
mdns is implemented using @plietar's own https://github.com/plietar/rust-mdns. I tried to change port by changing the hard-coded value in there to 5354. Unfortunately the Spotify client would no longer see it, as if it was expecting the service to run on 5353 and nothing else.

**Comment by sashahilton00** [comment]
Implemented with the ```-z``` or the ```--zeroconf-port```
