### ISSUE TITLE
couldn't parse packet from 192.168.4.113:59464: packet has non-zero reserved bits

### ISSUE THREAD

**Issue by asegarra** [librespot-org/librespot#911]
Using spotifyd  but I believe these messages originate in librespot, I'm getting quite a few of the above message, I suppose these are other clients in the network, anyway to quiet these down or some way I can fix whatever is wrong? Thanks.

**Comment by JasonLG1979** [comment]
Spotifyd uses an old version of librespot they would need to update from 0.2 to 3.1 to even be able to tell if this is still a valid issue.

**Comment by roderickvd** [comment]
Can you post the full log? I think this is from `libmdns`?

Also is this just a nuisance or is some behavior actually broken?

**Comment by JasonLG1979** [comment]
It's absolutely from `libmdns`:

https://github.com/librespot-org/libmdns/blob/acd405604d2fb589e9848d1292ce9404bd206d91/src/dns_parser/error.rs#L17

**Comment by asegarra** [comment]
> Spotifyd uses an old version of librespot they would need to update from 0.2 to 3.1 to even be able to tell if this is still a valid issue.

Sorry I didn't check the versions before hand, I saw a similar issue and it was redirected to librespot so I just came straight here.

> Can you post the full log? I think this is from `libmdns`?
> 
> Also is this just a nuisance or is some behavior actually broken?

That's pretty much all I see, just repeated many times. Not sure if it's an actual problem and if this may be related but I was often loosing connection through spotifyd necessitating a restart of the daemon, that's what led me to check the logs and this was pretty much all there was.

**Comment by roderickvd** [comment]
> > Can you post the full log? I think this is from `libmdns`?
> > Also is this just a nuisance or is some behavior actually broken?
> 
> That's pretty much all I see, just repeated many times.

Again please post the full log. Just copy paste everything.

> Not sure if it's an actual problem and if this may be related but I was often loosing connection through spotifyd necessitating a restart of the daemon, that's what led me to check the logs and this was pretty much all there was.

Please try stock `librespot` instead of `spotifyd` and see if you have the same issue. I think you will, but just to rule that out.

Then when we certify that this issue is with `libmdns` you should report it here: https://github.com/librespot-org/libmdns

**Comment by asegarra** [comment]
it’s a beacon in my home mesh network.

**Comment by asegarra** [comment]
> What device is 192.168.4.113?

It's a beacon in my home mesh network.

**Comment by asegarra** [comment]
> > > Can you post the full log? I think this is from `libmdns`?
> > > Also is this just a nuisance or is some behavior actually broken?
> > 
> > 
> > That's pretty much all I see, just repeated many times.
> 
> Again please post the full log. Just copy paste everything.
> 
I no longer have it but I'll reproduce it later today.

> > Not sure if it's an actual problem and if this may be related but I was often loosing connection through spotifyd necessitating a restart of the daemon, that's what led me to check the logs and this was pretty much all there was.
> 
> Please try stock `librespot` instead of `spotifyd` and see if you have the same issue. I think you will, but just to rule that out.
> 
> Then when we certify that this issue is with `libmdns` you should report it here: https://github.com/librespot-org/libmdns

Ok, I'll need some more time to figure out how to do this, will reply when I've done it.
Thanks.

**Comment by JasonLG1979** [comment]
> > What device is 192.168.4.113?
> 
> It's a beacon in my home mesh network.

Well either the beacon is misbehaving or very possibly `libmdns` is misbehaving or just being overly chatty in it's logs?

If it's not actually causing any trouble other that spamming the logs I would just drop the log level to warn or error.

Otherwise I would ask the `Spotifyd` team to help fix `libmdns`, it could use some love for sure, or alternatively maybe since `Spotifyd`'s stated goal is to be "An open source Spotify client running as a UNIX daemon." maybe they should use a different mdns implementation since they don't care about Windows compatibility?

**Comment by asegarra** [comment]
> Well either the beacon is misbehaving or very possibly `libmdns` is misbehaving or just being overly chatty in it's logs?

If it is then avahi and systemd-resolved don't seem to be bothered by it, I use both in different pc's. 

I actually stopped using spotify-tui/spotifyd due to the connection drops which may not be related to this but this was the only thing I could see in the logs, I also tried Spot that also uses librespot and had a similar problem and they are on 0.3.1 and don't think they have the same network spotify receiver feature that spotifyd/spotify-tui has. Please feel free to close this issue if you think it's a red herring, or for sure belongs in libmdns (I think it does).

**Comment by JasonLG1979** [comment]
> If it is then avahi and systemd-resolved don't seem to be bothered by it, I use both in different pc's.

`libmdns` is mostly functional but is a little rough around the edges. There have been other issues and talk of improving it, but in my mind the best option is to just hook into the underlying systems implementation (avahi in the case of Linux) and not have our own full mdns implementation. That was also in the works but stalled.

**Comment by roderickvd** [comment]
Please report this to the separate `libmdns` repo. In think it was @willstott101 who did excellent work on that but is not active anymore. I consider improving it as a nice challenge, but like @JasonLG1979 says, it’s mostly functioning now and I’ll be spending my time on many other `librespot` features first.
