### ISSUE TITLE
Like or Dislike unavailable when connecting to Spotify Connect

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#92]
<a href="https://github.com/Kia0ra"><img src="https://avatars0.githubusercontent.com/u/15661585?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Kia0ra](https://github.com/Kia0ra)**
_Wednesday Sep 27, 2017 at 06:02 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/254_

----

The Like or Dislike commands disappear from the player as soon as the Spotify Connect (using librespot/raspotify) device is chosen to play audio. Instead the Random / Repeat commands appear.

**Comment by sashahilton00** [comment]
<a href="https://github.com/derWeihnachtsmann"><img src="https://avatars0.githubusercontent.com/u/16196578?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [derWeihnachtsmann](https://github.com/derWeihnachtsmann)**
_Wednesday Sep 27, 2017 at 13:36 GMT_

----

Yes this is the default behaviour. If you want Like/dislike feature, you are free to write some lines in the evening hours and post a Pull request. xD

**Comment by sashahilton00** [comment]
<a href="https://github.com/Kia0ra"><img src="https://avatars0.githubusercontent.com/u/15661585?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Kia0ra](https://github.com/Kia0ra)**
_Wednesday Sep 27, 2017 at 17:06 GMT_

----

Default behavior of other Spotify player (PC App, Spotify Web Player, Chromecast, etc) is to put the thumb up/thumb down commands for radio playing when you can discover new artists and to put the Random/Repeat commands when you play a chosen artist.

Ahah, yeah it will need me quite a few evening hours to wrote this particular lines ;)

**Comment by ComlOnline** [comment]
I've just checked and this bug still exists

**Comment by sashahilton00** [comment]
Not a bug afaik, it requires implementation, it think it falls back to shuffle/repeat. Possibly linked to #57 as it came in with spotify radio?

**Comment by sashahilton00** [comment]
This behaviour no longer occurs.

**Comment by IiroP** [comment]
This issue is there again, build with latest commits. Exactly the same behaviour as in first post.
