### ISSUE TITLE
add support for jack audio connection kit

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#93]
<a href="https://github.com/loblik"><img src="https://avatars2.githubusercontent.com/u/1986927?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [loblik](https://github.com/loblik)**
_Thursday Oct 05, 2017 at 19:19 GMT_
_Originally opened as https://github.com/plietar/librespot/pull/260_

----

Hi, I've created simple JACK backend for librespot. It's just a simple initial implementation. But it works quite good. It seems to be better than
using portaudio (to access JACK) or pipe backend with jack-stdin.

Commit message follows.

This is initial support for JACK. It creates ports at startup and
keeps it connected while librespot is running. So when librespot
playback is stoped it writes silence (zeroes).

It uses jack crate (rust-jack) which needs libjack. To compile in
jack support use --features jackaudio-backend. And run librespot
with --backend jackaudio.

----

_**[loblik](https://github.com/loblik)** included the following code: https://github.com/plietar/librespot/pull/260/commits_

**Comment by ComlOnline** [comment]
@loblik could you create a pull request for this against this repo?
