### ISSUE TITLE
should stop using aes-ctr, aes-soft and aesni

### ISSUE THREAD

**Issue by gdesmott** [librespot-org/librespot#937]
The `aes-ctr`, `aes-soft` and `aesni` crates are no longer maintained, we should use `aes` instead, see [RUSTSEC-2021-0060](https://rustsec.org/advisories/RUSTSEC-2021-0060), [RUSTSEC-2021-0061 ](https://rustsec.org/advisories/RUSTSEC-2021-0061) and [RUSTSEC-2021-0059](https://rustsec.org/advisories/RUSTSEC-2021-0059).

Because of this, tools like `cargo deny check` will raise errors for all projects using `librespost`.

**Comment by roderickvd** [comment]
This has been fixed in `new-api` @ https://github.com/librespot-org/librespot/commit/89a5133bd70e68b1182592d6e98ff17fc1898fba.
