### ISSUE TITLE
Error in new-api branch when trying to get token

### ISSUE THREAD

**Issue by AbhayAysola** [librespot-org/librespot#941]
I ran the get_token example which throws this error - 
```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Unavailable, error: Response(MercuryResponse { uri: "hm://keymaster/token/authenticated?scope=streaming,user-read-playback-state,user-modify-playback-state,user-read-currently-playing&client_id=&device_id=b05ae3c8-5494-4496-a3ed-61f49d0c6921", status_code: 400, payload: [[123, 34, 99, 111, 100, 101, 34, 58, 50, 125]] }) }', examples\get_token.rs:25:62
stack backtrace:```

**Comment by roderickvd** [comment]
I see the `client_id` is empty. You are running the example as-is or have you got your own code? If it’s as-is I’ll see about fixing the example.

**Comment by AbhayAysola** [comment]
> I see the client_id is empty.

Yeah that's what I observed as well. After a little bit of digging it seems like the `client_id` isn't properly initialized in `Session::new`. 

I'm running the example code as-is.

**Comment by roderickvd** [comment]
This should be fixed in 0822af0.
