### ISSUE TITLE
Audio Sink Error when switching between two instances of librespot

### ISSUE THREAD

**Issue by coderootme** [librespot-org/librespot#946]
Tested on: ``librespot 0.3.1 4370aa1 (Built on 2021-12-22, Build ID: Ov05MEB1, Profile: release)``

This is probably a very unusual use case, but I am trying to open an issue, hopefully it leads to a good discussion, as usual.

I am running two instances of `librespot` on one device (Raspberry Pi 3).

Both are configured to output to the same `alsa` device. The meaning of this is that one instance is configured with `--normalisation-pregain "-9"` and is used when listening to music on headphones and the other instance is configured with `--normalisation-pregain "6"` and is used on speakers at night.

The problem is that when switching between them, for example from `headphones` to `speakers`, the new instance starts before the old instance stops and this creates an error with the alsa sink:

```
[2022-01-20T16:15:55Z ERROR librespot_playback::player] Audio Sink Error Connection Refused: <AlsaSink> Device hw:1,0 May be Invalid, Busy, or Already in Use, ALSA function 'snd_pcm_open' failed with error 'EBUSY: Device or resource busy'
```

Is there anything the devs can do with this? Maybe implement a small (configurable) delay somewhere in the chain, or is there a better way to handle this use case?

**Comment by roderickvd** [comment]
Sorry, but that is not something I am going to deal with. You may want to look at using PulseAudio as a backend, that can accept multiple sources at the same time.
