### ISSUE TITLE
Very high CPU in idle

### ISSUE THREAD

**Issue by agramner** [librespot-org/librespot#949]
I've built and run librespot (v0.3.1) on a linux machine (amd64) in docker. After a couple of minutes in idle top is showing 100% (1 core) for librespot. Ran it with -v flag but nothing is written to the log. I rebuilt librespot from tag v0.2.0 but same problem. Finally rebuilt librespot with [--no-default-features --features="alsa-backend"] and configured it to use alsa as backend. After this the problem disappeared and everything works fine.

**Comment by roderickvd** [comment]
That seems like a bug in Rodio then, perhaps in combination with Docker. Please report it upstream: https://github.com/RustAudio/rodio

**Comment by agramner** [comment]
Ok, that was my guess as well. Will report it, thanks!

**Comment by roderickvd** [comment]
If you want you can try 827b815 on `new-api` but if that doesn't work, not much more we can do.
