### ISSUE TITLE
Fork?

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#95]
<a href="https://github.com/Bebowi"><img src="https://avatars3.githubusercontent.com/u/21242387?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Bebowi](https://github.com/Bebowi)**
_Thursday Oct 26, 2017 at 14:57 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/263_

----

Is michaelherger's fork the official one?

**Comment by sashahilton00** [comment]
<a href="https://github.com/sashahilton00"><img src="https://avatars3.githubusercontent.com/u/4185362?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sashahilton00](https://github.com/sashahilton00)**
_Thursday Oct 26, 2017 at 14:58 GMT_

----

I think the plan was for Paul to nominate someone else as a maintainer so that we don't lose al issues/PR's by moving to a fork

**Comment by sashahilton00** [comment]
<a href="https://github.com/Bebowi"><img src="https://avatars3.githubusercontent.com/u/21242387?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Bebowi](https://github.com/Bebowi)**
_Thursday Oct 26, 2017 at 15:00 GMT_

----

I don't know but when I took a look at Fork it seems like this master has been merged to michaelherger's

**Comment by sashahilton00** [comment]
<a href="https://github.com/michaelherger"><img src="https://avatars3.githubusercontent.com/u/2789989?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [michaelherger](https://github.com/michaelherger)**
_Thursday Oct 26, 2017 at 15:05 GMT_

----

NO! I only forked it as the base to apply the few changes I need for my Spotty plugin. But I have close to zero Rust experience...

**Comment by sashahilton00** [comment]
<a href="https://github.com/Bebowi"><img src="https://avatars3.githubusercontent.com/u/21242387?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Bebowi](https://github.com/Bebowi)**
_Wednesday Nov 29, 2017 at 19:54 GMT_

----

At the moment there is nobody who wants to win. I'm new to Rust and I think many others too

**Comment by sashahilton00** [comment]
<a href="https://github.com/janLo"><img src="https://avatars0.githubusercontent.com/u/96146?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [janLo](https://github.com/janLo)**
_Wednesday Nov 29, 2017 at 20:00 GMT_

----

How about handing it into an organization of its own and invite known contributors as members. That would enable others than @plietar to approve and merge PullRequests.

**Comment by sashahilton00** [comment]
<a href="https://github.com/dtcooper"><img src="https://avatars0.githubusercontent.com/u/873944?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dtcooper](https://github.com/dtcooper)**
_Wednesday Nov 29, 2017 at 22:37 GMT_

----

That's where I'm at too, re: just learning rust. Not a bad idea, @janLo. Is @plietar responding to any librespot noise at able to do that?

**Comment by sashahilton00** [comment]
<a href="https://github.com/kingosticks"><img src="https://avatars2.githubusercontent.com/u/934824?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kingosticks](https://github.com/kingosticks)**
_Thursday Nov 30, 2017 at 02:49 GMT_

----

Nobody has stepped forward so there's nothing to respond to. I think that's the first step here.

**Comment by sashahilton00** [comment]
<a href="https://github.com/sashahilton00"><img src="https://avatars3.githubusercontent.com/u/4185362?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sashahilton00](https://github.com/sashahilton00)**
_Monday Jan 29, 2018 at 00:02 GMT_

----

@Bebowi @michaelherger @janLo @dtcooper we've forked librespot into an organisation as a successor and have begun cleanup/implementing PR's and bug fixes. It's available at https://github.com/librespot-org/librespot

**Comment by ComlOnline** [comment]
We're in the new fork.
