### ISSUE TITLE
alsa-mixer-control parameter seems to be ignored

### ISSUE THREAD

**Issue by fpicot** [librespot-org/librespot#953]
It seems that the parameter alsa-mixer-control is ignored under librespot 0.3.1
Configuration is passed via environment variables as follow :
```
LIBRESPOT_DEVICE="sysdefault:CARD=sndrpihifiberry"
LIBRESPOT_BACKEND="alsa"
LIBRESPOT_MIXER="alsa"
LIBRESPOT_ALSA_MIXER_CONTROL="Master"
```

The logs show : 
```
Jan 26 16:53:10 spotipy librespot[4971]: [2022-01-26T15:53:10Z INFO  librespot_playback::mixer::alsamixer] Mixing with Alsa and volume control: Linear for device: hw:CARD=sndrpihifiberry with mixer control: Master,0
Jan 26 16:53:10 spotipy librespot[4971]: [2022-01-26T15:53:10Z DEBUG librespot_playback::mixer::alsamixer] Alsa mixer control is softvol: true
```

Test confirm that the alsa mixer is ignored using the equalizer plugin (change 

This was working under librespot v0.1.3-37-g0adb851 with the parameter "--backend alsa --mixer alsa --mixer-name Master"

**Comment by roderickvd** [comment]
I don’t know what the issue is? You specified to use the `Master` mixer of Alsa and that’s what it is doing.

**Comment by fpicot** [comment]
I did not understand the meaning the log "Alsa mixer control is softvol: true" properly, but your comment on #948 made it clear, the mixer is Master and is doing software volume control. 

What I don't get however is why with the same /etc/asound.conf,  librespot 0.1.3 with parameters "--backend alsa --mixer alsa --mixer-name Master" is correctly going through the equalizer alsa plugin but librespot 0.3.1 with parameters "--device "sysdefault:CARD=sndrpihifiberry" --backend alsa --mixer alsa --alsa-mixer-control Master" is not.
