### ISSUE TITLE
Compilation error[E0460]: found possibly newer version of crate `log` which `librespot` depends on

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#96]
<a href="https://github.com/chriszirkel"><img src="https://avatars1.githubusercontent.com/u/950244?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chriszirkel](https://github.com/chriszirkel)**
_Friday Nov 03, 2017 at 16:53 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/264_

----

After I cloned and installed librespot on my RPi3 with cargo build, I tried to run the play.rs example with the following command:

`pi@raspberrypi:~/librespot/target/release $ rustc play.rs --extern librespot=liblibrespot.rlib && ./excecutable`

This results in the following error:

error[E0460]: found possibly newer version of crate 'log' which 'librespot' depends on
 --> play.rs:1:1
  |
1 | extern crate librespot;
  | ^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: perhaps that crate needs to be recompiled?
  = note: crate 'log' path #1: /home/pi/.rustup/toolchains/stable-armv7-unknown-linux-gnueabihf/lib/rustlib/armv7-unknown-linux-gnueabihf/lib/liblog-4df2ac3c730deffe.rlib
  = note: crate 'librespot' path #1: /home/pi/librespot/target/release/liblibrespot.rlib

error: aborting due to previous error

I don't really know what the problem is about. According to Cargo.toml, librespot has a dependency to log = "0.3.5", and the newest version is of log = "0.3.8". 
Do I need to update this specific crate?

**Comment by ComlOnline** [comment]
Hey @chriszirkel, Is there any reason you didn't run the binary directly? 
```
./librespot --name "speaker"
```

**Comment by sashahilton00** [comment]
Can we close this? I can't reproduce in either release or debug when compiling for RPi...

**Comment by plietar** [comment]
You should be building `play.rs` with cargo, not rustc.
```
cargo build --example play
```

**Comment by sashahilton00** [comment]
This feels like a non-issue, so closing for now. Feel free to reopen if you think I've closed this prematurely.
