### ISSUE TITLE
Pipe character in spotify login

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#97]
<a href="https://github.com/mentat-fr"><img src="https://avatars0.githubusercontent.com/u/284631?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mentat-fr](https://github.com/mentat-fr)**
_Friday Nov 17, 2017 at 18:47 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/265_

----

Hi 

Just find a problem, in my login name I have a pipe character ‘|’ so when you use the login in the script the system interpret it as a pipe. Just make the test with an other spotify account and it’s work well.

Can you fix this by protect the login during command line ?

Many thanks.

**Comment by sashahilton00** [comment]
<a href="https://github.com/kingosticks"><img src="https://avatars2.githubusercontent.com/u/934824?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kingosticks](https://github.com/kingosticks)**
_Friday Nov 17, 2017 at 18:48 GMT_

----

Can't you just quote it?

**Comment by ComlOnline** [comment]
Closed for non response.

**Comment by mherger** [comment]
That's a dupe of issue #69
