### ISSUE TITLE
Metadata again..

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#98]
<a href="https://github.com/frafall"><img src="https://avatars1.githubusercontent.com/u/8217925?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [frafall](https://github.com/frafall)**
_Saturday Nov 25, 2017 at 04:03 GMT_
_Originally opened as https://github.com/plietar/librespot/issues/266_

----

Metadata/tags has been sadly overlooked, as it is now every integration patches its own.

I suggest we address this by making metadata available in the audio_backend.

Ex. Pulseaudio has a more or less well defined API where it uses [properties](https://freedesktop.org/software/pulseaudio/doxygen/proplist_8h.html), Airplay supports its own tags, for the stdout backend we can continue to use stderr as the simple "Track loading" stuff does today but should be expanded with more tags. Currently metadata is not a part of the audio backend API at all as far as I can tell.

Also, all the basic tags should be available without having to lookup in Spotify again as that would push complexity into audio distribution (Pulseaudio, Snapcast). Adding a tag for Spotify reference would be nice to enable elaborate UI's (ex Kodi with a lot of track info) but basic info should be available without complexity. 

Any ideas?

**Comment by sashahilton00** [comment]
<a href="https://github.com/frafall"><img src="https://avatars1.githubusercontent.com/u/8217925?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [frafall](https://github.com/frafall)**
_Thursday Nov 30, 2017 at 07:16 GMT_

----

Hmm, is this maintained at all anymore? Or moved somewhere else?

Anyone?

**Comment by sashahilton00** [comment]
<a href="https://github.com/herrwusel"><img src="https://avatars1.githubusercontent.com/u/8242787?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [herrwusel](https://github.com/herrwusel)**
_Thursday Nov 30, 2017 at 07:37 GMT_

----

See the readme here:
https://github.com/plietar/librespot#unmaintained

**Comment by sashahilton00** [comment]
<a href="https://github.com/frafall"><img src="https://avatars1.githubusercontent.com/u/8217925?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [frafall](https://github.com/frafall)**
_Friday Dec 01, 2017 at 10:37 GMT_

----

Ye, have any1 come forward to take ownership or do we all fragment it into our own special versions?
It's a brilliant piece of code and I'd hate to see it fragment :(

**Comment by sashahilton00** [comment]
<a href="https://github.com/herrwusel"><img src="https://avatars1.githubusercontent.com/u/8242787?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [herrwusel](https://github.com/herrwusel)**
_Friday Dec 01, 2017 at 10:52 GMT_

----

Sorry but another url again:
https://github.com/plietar/librespot/issues/263#issuecomment-348066472

Maybe you step forward? :)

**Comment by sashahilton00** [comment]
<a href="https://github.com/frafall"><img src="https://avatars1.githubusercontent.com/u/8217925?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [frafall](https://github.com/frafall)**
_Saturday Dec 02, 2017 at 13:42 GMT_

----

Tempting but my rust skills are more than rusty *S* 
We are probably better off with someone who can evaluate pulls...

**Comment by sashahilton00** [comment]
<a href="https://github.com/sashahilton00"><img src="https://avatars3.githubusercontent.com/u/4185362?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [sashahilton00](https://github.com/sashahilton00)**
_Sunday Jan 28, 2018 at 23:58 GMT_

----

@frafall see https://github.com/librespot-org/librespot the recent successor.

**Comment by sashahilton00** [comment]
<a href="https://github.com/frafall"><img src="https://avatars1.githubusercontent.com/u/8217925?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [frafall](https://github.com/frafall)**
_Monday Jan 29, 2018 at 07:54 GMT_

----

This is good new indeed!

:+1:

**Comment by ComlOnline** [comment]
Please see #7 for continued discussion.
