### ISSUE TITLE
Random interruptions of playback

### ISSUE THREAD

**Issue by stenub** [librespot-org/librespot#982]
Hello,

I have random playback interruptions after 5-30 minutes. This is what my log says. How can i troubleshoot further?

Mar 20 22:57:50 raspberrypi librespot[913]: [2022-03-20T21:57:50Z DEBUG librespot_playback::player] command=Preload(SpotifyId { id: 161324305904036895493107911526969909648, audio_type: Track })
Mar 20 22:57:50 raspberrypi librespot[913]: [2022-03-20T21:57:50Z DEBUG librespot_playback::player] Preloading track
Mar 20 22:57:50 raspberrypi librespot[913]: [2022-03-20T21:57:50Z DEBUG librespot_core::session] Invalidating session[0]
Mar 20 22:57:50 raspberrypi librespot[913]: [2022-03-20T21:57:50Z ERROR librespot_playback::player] Unable to load audio item: MercuryError
Mar 20 22:57:50 raspberrypi librespot[913]: [2022-03-20T21:57:50Z DEBUG librespot_core::session] drop Dispatch
Mar 20 22:57:50 raspberrypi librespot[913]: [2022-03-20T21:57:50Z ERROR librespot_core::session] Connection reset by peer (os error 104)
Mar 20 22:57:50 raspberrypi librespot[913]: [2022-03-20T21:57:50Z ERROR librespot_connect::spirc] subscription terminated
Mar 20 22:57:50 raspberrypi librespot[913]: [2022-03-20T21:57:50Z DEBUG librespot_connect::spirc] drop Spirc[0]
Mar 20 22:57:50 raspberrypi librespot[913]: [2022-03-20T21:57:50Z DEBUG librespot_playback::player] Shutting down player thread ...
Mar 20 22:57:50 raspberrypi librespot[913]: [2022-03-20T21:57:50Z DEBUG librespot_playback::player] drop PlayerInternal[0]
Mar 20 22:57:50 raspberrypi librespot[913]: [2022-03-20T21:57:50Z DEBUG librespot_playback::player] PlayerInternal thread finished.
Mar 20 22:57:50 raspberrypi librespot[913]: [2022-03-20T21:57:50Z DEBUG librespot_core::session] drop Session[0]
Mar 20 22:57:50 raspberrypi librespot[913]: [2022-03-20T21:57:50Z DEBUG librespot_core::audio_key] drop AudioKeyManager
Mar 20 22:57:50 raspberrypi librespot[913]: [2022-03-20T21:57:50Z DEBUG librespot_core::channel] drop ChannelManager
Mar 20 22:57:50 raspberrypi librespot[913]: [2022-03-20T21:57:50Z DEBUG librespot_core::mercury] drop MercuryManager
Mar 20 22:57:50 raspberrypi librespot[913]: [2022-03-20T21:57:50Z WARN  librespot] Spirc shut down unexpectedly

**Comment by roderickvd** [comment]
There have been a lot of Mercury-related errors in the Spotify infrastructure lately. Please search around the repository for related reports and solutions.

If you feel that it is unrelated to those infrastructure problems, feel free to open with a complete log and description of hardware and internet setup.

**Comment by stenub** [comment]
Sorry, but i have searched around and i cant find (for the life of me) any related issues or suitable solutions. Also, i dont know what exactly Mercury is, or what it is responsible for. Can you give me a hint and/or a link to a related issue? Many thanks!
