### ISSUE TITLE
Free accounts

### ISSUE THREAD

**Issue by 89z** [librespot-org/librespot#989]
_Removed by maintainer._

**Comment by roderickvd** [comment]
Please stop posting this. The `README` clearly states we will only support paid subscriptions. I have told you why yesterday before I closed and removed the other issue.

**Comment by roderickvd** [comment]
Let me clarify to those who have missed yesterdays “conversation”, or to those who might judge us as villainous puppets of corporate overlords:

Within the admittedly grey area where this project is at, we abide by the Spotify ToS as best we can and do not condone piracy of any kind. So no saving of unencrypted files to disk, and no retransmission over another network, amongst others.

Also, trying to implement functionality as best we can mimicking the official client. For Free accounts this would also mean: limited skips and ads. Without those limitations, I don’t know where it says in the ToS, but I imagine we all feel that you’d be reaping the benefits without carrying the burden. 

Not only do we rather spend time on implementing other things, we take the stance that it’s a good thing to support Spotify and your artists financially by getting that paid subscription.

Doing so not only supports the music and podcast industry, it also protects this project and all of its users worldwide. Related projects that made different choices have been subject to legal action and takedowns. Even if they hadn’t, we very much intend to prevent all that. 

This is why we will not support free accounts, refrain from spreading information how that could be done, and actively remove any such information from this repository. Doing so, keeping this software available to thousands, perhaps millions of users worldwide ❤️
