### ISSUE TITLE
Added JSON output of metadata to make parsing independent of tags output

### ISSUE THREAD

**Issue by sashahilton00** [librespot-org/librespot#99]
<a href="https://github.com/frafall"><img src="https://avatars1.githubusercontent.com/u/8217925?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [frafall](https://github.com/frafall)**
_Thursday Nov 30, 2017 at 10:30 GMT_
_Originally opened as https://github.com/plietar/librespot/pull/267_

----

Just a small step of standardizing metadata by printing it as json, in this implementation I 
print artist/title but as output is json we can easily add more tags without breaking stdout parsing in integrations. 

ex:
metadata:{"ARTIST":"Pink Floyd","TITLE":"Money"}

----

_**[frafall](https://github.com/frafall)** included the following code: https://github.com/plietar/librespot/pull/267/commits_

**Comment by ComlOnline** [comment]
Please see #7 for continued discussion.
